SELECT PERSON.ID,
       PERSON.LAST_NAME,
       PERSON.FIRST_NAME
FROM PERSON
JOIN FACULTY ON PERSON.ID = FACULTY.FACULTY_ID
ORDER BY LAST_NAME

SELECT *
FROM TERMS




SELECT *
FROM PERPOSWG
WHERE PPWG_HRP_ID = '5109723'
AND PPWG_END_DATE IS NULL

SELECT * FROM FACULTY
WHERE FACULTY_ID = '5109723'

SELECT * FROM EMPLOYES
WHERE EMPLOYES_ID = '5109723'

SELECT * FROM STAFF
WHERE STAFF_ID = '5109723'

SELECT POSITION_ID,
       POS_TITLE,
       POS_EEO_RANK,
       POS_RANK,
       POS_CLASS,
       POS_DFLT_WORK_WEEK,
       POS_TYPE
       FROM POSITION

SELECT *
FROM PERSTAT
WHERE PERSTAT_HRP_ID = '5109723'

SELECT PERSTAT_HRP_ID,
       PERSTAT_PRIMARY_POS_ID,
       PERSTAT_TENURE_TYPE,
       PERSTAT_START_DATE,
       PERSTAT_END_DATE,
       PERSTAT_STATUS
FROM PERSTAT
WHERE PERSTAT_HRP_ID = '5109723'

SELECT
        PERSTAT_HRP_ID,
        PERSON.LAST_NAME,
        PERSON.FIRST_NAME,
        POS_EEO_RANK,
        PERSTAT_TENURE_TYPE,
        POS_CLASS,
        POSITION.POS_TITLE

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
WHERE PERSTAT_END_DATE IS NULL
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
ORDER BY POS_CLASS, LAST_NAME, FIRST_NAME





SELECT * FROM (SELECT FACULTY_ID,
                      CASE
                          WHEN FAC_CS_LOAD IS NULL OR FAC_CS_LOAD = 0 THEN 'Not-For-Credit'
                          ELSE 'For-Credit' END AS CREDIT_STATUS
               FROM FACULTY_SECTIONS_DETAILS_VIEW
                WHERE CS_TERM IN ('2024FA', '2025SP')) AS X
GROUP BY FACULTY_ID, CREDIT_STATUS
