SELECT * FROM PERSON

SELECT *
FROM TERMS

SELECT *

SELECT *
FROM STUDENT_ENROLLMENT_VIEW
WHERE ENROLL_TERM = '2024FA'

SELECT *
FROM STUDENT_ENROLLMENT_DETAIL_VIEW
WHERE ENROLL_TERM = '2024FA'


SELECT *
FROM COURSES


SELECT *
FROM STUDENT_TERM_FOR_CREDITS_VIEW

SELECT *
FROM PERPOSWG
WHERE PPWG_HRP_ID = '5109723'
AND PPWG_END_DATE IS NULL

SELECT * FROM FACULTY
WHERE FACULTY_ID = '5109723'

SELECT * FROM EMPLOYES
WHERE EMPLOYES_ID = '5109723'

SELECT * FROM STAFF
WHERE STAFF_ID = '5109723'

SELECT POSITION_ID,
       POS_TITLE,
       POS_EEO_RANK,
       POS_RANK,
       POS_CLASS,
       POS_DFLT_WORK_WEEK,
       POS_TYPE
       FROM POSITION

SELECT *
FROM POSITION
WHERE POS_CLASS != 'FAC'
ORDER BY POS_CLASS

SELECT POSITION_ID,
       POS_TITLE,
       POS_CLASS,
       POS_SOC_CODE
       FROM POSITION
WHERE POS_CLASS != 'FAC'
ORDER BY POS_CLASS

SELECT *
FROM PERSTAT
WHERE PERSTAT_HRP_ID = '5109723'

SELECT PERSTAT_HRP_ID,
       PERSTAT_PRIMARY_POS_ID,
       PERSTAT_TENURE_TYPE,
       PERSTAT_START_DATE,
       PERSTAT_END_DATE,
       PERSTAT_STATUS
FROM PERSTAT
WHERE PERSTAT_HRP_ID = '5109723'

SELECT
        PERSTAT_HRP_ID,
        PERSON.LAST_NAME,
        PERSON.FIRST_NAME,
        POSITION.POS_TITLE,
        POSITION.POS_SOC_CODE,
        SOC_CODES.SOC_DESC

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN SOC_CODES ON POSITION.POS_SOC_CODE = SOC_CODES.SOC_CODES_ID
WHERE PERSTAT_END_DATE IS NULL
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS != 'FAC'
ORDER BY POS_SOC_CODE, LAST_NAME, FIRST_NAME


SELECT
        PERSTAT_HRP_ID,
        PERSON.LAST_NAME,
        PERSON.FIRST_NAME,
        PERSTAT_START_DATE,
        PERSTAT_END_DATE,
        POSITION_ID,
        POSITION.POS_TITLE

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
WHERE PERSTAT_END_DATE IS NULL
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND PERSTAT_START_DATE BETWEEN '2023-11-01' AND '2024-11-01'
ORDER BY LAST_NAME, FIRST_NAME

