	SELECT EXPECTED_CLASS_IN_2025SP
			,COUNT(*) AS STUDENT_COUNT_REMAINING
		FROM (
			SELECT STUDENT_EXPECTED_CLASS.STUDENT_ID
					,EXPECTED_CLASS_IN_2025SP
			FROM
				(
					SELECT ID AS STUDENT_ID
						,CASE WHEN TERM = '2024FA' THEN 'Freshman'
								WHEN TERM = '2023FA' THEN 'Sophomore'
								WHEN TERM = '2022FA' THEN 'Junior'
								WHEN TERM LIKE '%FA' THEN 'Senior'
								WHEN TERM LIKE '%SP' THEN 'Non-Cohort'
								ELSE NULL END AS EXPECTED_CLASS_IN_2025SP
					FROM Z01_AAV_STUDENT_FIRST_MATRIC
				) AS STUDENT_EXPECTED_CLASS
			JOIN (
					SELECT DISTINCT STUDENT_ID
					FROM STUDENT_ENROLLMENT_VIEW
					WHERE ENROLL_TERM = '2025SP'
					AND ENROLL_CURRENT_STATUS IN ('New', 'Add')
				) as CURRENT_STUDENTS ON STUDENT_EXPECTED_CLASS.STUDENT_ID = CURRENT_STUDENTS.STUDENT_ID
		) AS X
	WHERE EXPECTED_CLASS_IN_2025SP IS NOT NULL
	GROUP BY EXPECTED_CLASS_IN_2025SP
	ORDER BY STUDENT_COUNT_REMAINING DESC