SELECT  POS_EEO_RANK,
        COUNT(*) AS NINE_MONTHS

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= (
          SELECT TOP 1 TERM_START_DATE
          FROM TERMS
          WHERE TERMS_ID = '2024FA'
          ))
AND PERSTAT_START_DATE <= '2024-11-01'
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND GENDER = 'M'
GROUP BY POS_EEO_RANK --Men
----------------------------------------------------------------------------------------------------------------------
SELECT  POS_EEO_RANK,
        COUNT(*) AS NINE_MONTHS

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= (
          SELECT TOP 1 TERM_START_DATE
          FROM TERMS
          WHERE TERMS_ID = '2024FA'
          ))
AND PERSTAT_START_DATE <= '2024-11-01'
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND GENDER = 'F'
GROUP BY POS_EEO_RANK --Women






