SELECT  POS_EEO_RANK,
        SUM(PPWG_ANNUALIZED_AMT) AS SALARY_OUTLAYS_NINE_MONTHS

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN PERPOSWG ON PERSTAT.PERSTAT_HRP_ID = PPWG_HRP_ID AND PERSTAT_PRIMARY_POS_ID = PERPOSWG.PPWG_POSITION_ID
WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= (
          SELECT TOP 1 TERM_START_DATE
          FROM TERMS
          WHERE TERMS_ID = '2024FA'
          ))
AND PERSTAT_START_DATE <= '2024-11-01'
AND PERSTAT_STATUS = 'FT'
AND POSITION.POS_CLASS = 'FAC'
AND GENDER = 'M'
AND PPWG_PAYCLASS_ID IS NOT NULL
AND (
    PPWG_END_DATE IS NULL
    OR PPWG_END_DATE > GETDATE()
    )
GROUP BY POS_EEO_RANK --Men
----------------------------------------------------------------------------------------------------------------------
SELECT  POS_EEO_RANK,
        SUM(PPWG_ANNUALIZED_AMT) AS SALARY_OUTLAYS_NINE_MONTHS

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN PERPOSWG ON PERSTAT.PERSTAT_HRP_ID = PPWG_HRP_ID AND PERSTAT_PRIMARY_POS_ID = PERPOSWG.PPWG_POSITION_ID
WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= (
          SELECT TOP 1 TERM_START_DATE
          FROM TERMS
          WHERE TERMS_ID = '2024FA'
          ))
AND PERSTAT_START_DATE <= '2024-11-01'
AND PERSTAT_STATUS = 'FT'
AND POSITION.POS_CLASS = 'FAC'
AND GENDER = 'F'
AND PPWG_PAYCLASS_ID IS NOT NULL
AND (
    PPWG_END_DATE IS NULL
    OR PPWG_END_DATE > GETDATE()
    )
GROUP BY POS_EEO_RANK --Women
