SELECT  PERSTAT_HRP_ID,
        PERSON.LAST_NAME,
        PERSON.FIRST_NAME,
        PERSTAT_TENURE_TYPE

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
WHERE PERSTAT_END_DATE IS NULL
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND GENDER = 'M'
ORDER BY PERSTAT_TENURE_TYPE, LAST_NAME, FIRST_NAME


