SELECT *
FROM STUDENT_ENROLLMENT_VIEW
WHERE STUDENT_ID = '5492566'

SELECT *
FROM STUDENT_ENROLLMENT_VIEW
WHERE SECTION_DEPARTMENT1 = 'NUR'

SELECT *
FROM SUBJECTS


SELECT ENROLL_CURRENT_STATUS,
       SECTION_COURSE_NAME,
       SECTION_COURSE_TITLE,
       SECTION_SUBJECT,
       SECTION_DEPARTMENT1,
       ENROLL_CREDITS,
       ENROLL_ATTEMPTED_CREDITS,
       ENROLL_COMPLETED_CREDITS,
       ENROLL_GPA_CREDITS,
       ENROLL_VERIFIED_GRADE,
       ENROLL_GRADE_POINTS,
       ENROLL_CUM_CONTRIB_GRADE_POINTS
FROM STUDENT_ENROLLMENT_VIEW
WHERE STUDENT_ID = '6188940'





SELECT STUDENT_ID,
       SUM(ENROLL_CUM_CONTRIB_GRADE_POINTS) / SUM(ENROLL_GPA_CREDITS) AS NURSING_GPA
FROM (SELECT STUDENT_ID,
             ENROLL_GPA_CREDITS,
             ENROLL_CUM_CONTRIB_GRADE_POINTS
      FROM STUDENT_ENROLLMENT_VIEW
      WHERE STUDENT_ID = '5492566'
        AND SECTION_DEPARTMENT1 = 'NUR') AS X
GROUP BY STUDENT_ID


SELECT ID,
       (SELECT SUM(ENROLL_CUM_CONTRIB_GRADE_POINTS) / SUM(ENROLL_GPA_CREDITS)
        FROM STUDENT_ENROLLMENT_VIEW
        WHERE STUDENT_ID = ID
        AND SECTION_DEPARTMENT1 = 'NUR') AS NURSING_GPA
FROM PERSON
WHERE ID = '6188940'