SELECT *
FROM STUDENT_ENROLLMENT_VIEW
WHERE STUDENT_ID = '5492566'





SELECT *
FROM STUDENT_ENROLLMENT_VIEW
WHERE SECTION_DEPARTMENT1 = 'NUR'

SELECT *
FROM SUBJECTS


SELECT STC_TITLE,
       STC_SUBJECT,
       STC_CRED,
       STC_CMPL_CRED,
       STC_GPA_CRED,
       STC_GRADE_SCHEME,
       STC_FINAL_GRADE,
       STC_VERIFIED_GRADE,
       STC_COURSE_NAME,
       STC_ATT_CRED,
       STC_CUM_CONTRIB_ATT_CRED,
       STC_CUM_CONTRIB_CMPL_CRED,
       STC_CUM_CONTRIB_GPA_CRED,
       STC_ALTCUM_CONTRIB_ATT_CRED,
       STC_ALTCUM_CONTRIB_GPA_CRED,
       STC_GRADE_PTS,
       STC_CUM_CONTRIB_GRADE_PTS,
       STC_ALTCUM_CONTRIB_GRADE_PTS
FROM STUDENT_ACAD_CRED
WHERE STC_PERSON_ID = '5492566'


SELECT TOP 5 ENROLL_CURRENT_STATUS,
       SECTION_COURSE_NAME,
       SECTION_COURSE_TITLE,
       SECTION_SUBJECT,
       SECTION_DEPARTMENT1,
       ENROLL_CREDITS,
       ENROLL_ATTEMPTED_CREDITS,
       ENROLL_COMPLETED_CREDITS,
       ENROLL_GPA_CREDITS,
       ENROLL_VERIFIED_GRADE,
       ENROLL_GRADE_POINTS,
       ENROLL_CUM_CONTRIB_GRADE_POINTS
FROM STUDENT_ENROLLMENT_VIEW
WHERE ENROLL_CURRENT_STATUS = 'Add'