SELECT X.ID, X.TERM
FROM (
SELECT DISTINCT APPL_APPLICANT     AS ID,
APPL_START_TERM                                                          AS TERM,
TERM_START_DATE,
ROW_NUMBER() OVER (PARTITION BY APPL_APPLICANT ORDER BY TERM_START_DATE) AS TERM_ORDER
FROM APPLICATIONS AS AP
JOIN STUDENT_ACAD_CRED AS AC
ON AP.APPL_APPLICANT = AC.STC_PERSON_ID AND AP.APPL_START_TERM = AC.STC_TERM
JOIN STC_STATUSES AS STAT ON AC.STUDENT_ACAD_CRED_ID = STAT.STUDENT_ACAD_CRED_ID AND POS = 1
JOIN TERMS ON APPL_START_TERM = TERMS_ID
WHERE APPL_DATE IS NOT NULL
--     AND APPL_WITHDRAW_DATE IS NULL (Should not use)
AND STC_STATUS IN ('A', 'N')
AND STC_CRED_TYPE IN ('INST')
          ) AS X
    WHERE TERM_ORDER = 1
AND TERM_START_DATE >= '08-01-2015'
