UPDATE TABLES
SET DESCRIPTION = 'ATP_ACYR File Suite'
WHERE NAME LIKE 'ATP_%'

UPDATE Variables
SET DESCRIPTION = '...', REVIEWED = GETDATE(), NOT_IN_REFERENCE = 1
WHERE TableName Like '%_LS' and Description is NULL


UPDATE Variables
SET DESCRIPTION = '...', REVIEWED = GETDATE(), NOT_IN_REFERENCE = 1
WHERE TableName Like '%_VIEW' and Description is NULL