SELECT Z01_PERSON.ID,
       CASE WHEN ALIEN_STATUS_DESC = 'Non-resident Alien' THEN 'Non-resident Alien'
        WHEN PERSON_ETHNIC_1_DESC = 'Hispanic/Latino' THEN 'Hispanic/Latino'
        WHEN PERSON_RACE_2 IS NOT NULL THEN 'Two or More Races'
        ELSE COALESCE(PERSON_RACE_1_DESC, 'Unknown') END AS RACE
FROM Z01_PERSON
LEFT JOIN SPT_FOREIGN_PERSON ON Z01_PERSON.ID = SPT_FOREIGN_PERSON.FOREIGN_PERSON_ID