SELECT *
FROM ODS_FA_TERM_AWARDS
------------------------------------------------------------------------------------------------------------------------
SELECT *
FROM Z01_BE_TUITION_REVENUE
WHERE STTR_STUDENT = '5079083'

SELECT *
FROM Z01_BE_DINING_REVENUE
WHERE STTR_STUDENT = '5079083'

SELECT *
FROM Z01_BE_FEE_REVENUE
WHERE STTR_STUDENT = '5079083'

SELECT *
FROM Z01_BE_FEE_REVENUE
WHERE STTR_TERM = '2024FA'


SELECT *
FROM Z01_BE_HOUSING_REVENUE_WITH_COHORTS
WHERE STTR_STUDENT = '5079083'

SELECT *
FROM Z01_AR_INVOICE
WHERE PERSON_ID = '5079083'

SELECT DISTINCT INVI_AR_CODE, ARC_DESC, INVI_DESC
FROM Z01_AR_INVOICE
JOIN Z01_AR_CODES ON Z01_AR_INVOICE.INVI_AR_CODE = Z01_AR_CODES.AR_CODES_ID
WHERE INVI_AR_CODE IN ('STUFE', 'ACTFE')
ORDER BY ARC_DESC



------------------------------------------------------------------------------------------------------------------------
SELECT *
FROM ODS_ACAD_CREDENTIALS

SELECT *
FROM ODS_FA_TERM_AWARDS

SELECT *
FROM Z01_AR_CODES


