SELECT *
FROM STUDENT_ENROLLMENT_VIEW
WHERE SECTION_DEPARTMENT1 = 'EDU'

SELECT *
FROM MAJORS


SELECT ID, STATUS
FROM (SELECT DISTINCT APPL_APPLICANT    AS ID,
                      APPL_ADMIT_STATUS AS STATUS,
                      ROW_NUMBER() OVER (PARTITION BY APPL_APPLICANT ORDER BY TERM_START_DATE DESC) AS RANK
      FROM APPLICATIONS
       JOIN TERMS ON APPL_START_TERM = TERMS_ID
      WHERE APPL_DATE IS NOT NULL
        AND EXISTS (SELECT 1
                    FROM STUDENT_ACAD_CRED AS STC

                    WHERE STC_PERSON_ID = APPL_APPLICANT
                      AND STC_TERM = APPL_START_TERM
)) AS X WHERE RANK = 1

SELECT ID, STATUS
FROM (SELECT DISTINCT APPL_APPLICANT    AS ID,
                      APPL_ADMIT_STATUS AS STATUS,
                      ROW_NUMBER() OVER (PARTITION BY APPL_APPLICANT ORDER BY TERM_START_DATE DESC) AS RANK
      FROM APPLICATIONS
       JOIN TERMS ON APPL_START_TERM = TERMS_ID
      WHERE APPL_DATE IS NOT NULL
        AND EXISTS (SELECT 1
                    FROM STUDENT_ACAD_CRED AS STC
                    JOIN STC_STATUSES AS STATUS ON STC.STUDENT_ACAD_CRED_ID = STATUS.STUDENT_ACAD_CRED_ID AND POS = 1
                    WHERE STC_PERSON_ID = APPL_APPLICANT
                      AND STC_TERM = APPL_START_TERM
                    AND STC_STATUS IN ('N', 'A')
                    AND STC_CRED_TYPE = 'INST'
)) AS X WHERE RANK = 1

SELECT *
FROM VALS

SELECT *
FROM ADMIT_STATUSES

SELECT *
FROM Z01_ALL_RACE_ETHNIC_W_FLAGS

