SELECT *
FROM ODS_FA_TERM_AWARDS
WHERE AWARD_CATEGORY_ID IN ('OUTSI', 'THRD')


SELECT DISTINCT AWARD_CATEGORY_DESC, AWARD_DESCRIPTION
FROM ODS_FA_TERM_AWARDS
WHERE AWARD_CATEGORY_ID IN ('OUTSI', 'THRD')

