SELECT *
FROM MAJORS

SELECT *
FROM STUDENT_ENROLLMENT_VIEW

SELECT *
FROM ACAD_PROGRAMS

SELECT *
FROM SUBJECTS

SELECT *
FROM DEPTS

SELECT *
FROM MINORS

SELECT *
FROM STPR_MINOR_LIST_VIEW

SELECT *
FROM STPR_SPECIALTIES

SELECT *
FROM STPR_SPECIALTIES_VIEW

SELECT *
FROM SPECIALIZATIONS

SELECT *
FROM STUDENT_ACAD_CRED

SELECT DISTINCT TERMS.TERMS_ID  AS TERM,
TERMS.TERM_START_DATE,
SPECIALIZATIONS.SPEC_DESC AS SPECIALIZATION,
STUDENT_ID
FROM SPECIALIZATIONS
CROSS JOIN TERMS
CROSS JOIN STUDENT_ACAD_PROGRAMS_VIEW AS SAPV
LEFT JOIN STPR_SPECIALTIES_VIEW AS STUDENT_SPECIALTIES
        ON SAPV.STUDENT_ID = STPR_STUDENT AND STP_ACADEMIC_PROGRAM = STPR_ACAD_PROGRAM
LEFT JOIN SPECIALIZATIONS AS STU_SPEC ON STUDENT_SPECIALTIES.STPR_SPECIALIZATIONS = STU_SPEC.SPECIALIZATIONS_ID
WHERE TERMS.TERM_START_DATE >= '2019-08-01'
AND TERMS.TERM_END_DATE < '2025-06-01'
AND (TERMS.TERMS_ID LIKE '%FA' OR TERMS.TERMS_ID LIKE '%SP')
AND STP_START_DATE <= TERMS.TERM_END_DATE
AND (STP_END_DATE >= TERMS.TERM_START_DATE OR STP_END_DATE IS NULL)
AND STP_CURRENT_STATUS != 'Did Not Enroll'
AND (
SPECIALIZATIONS.SPECIALIZATIONS_ID = STU_SPEC.SPECIALIZATIONS_ID
AND STPR_SPECIALIZATION_START <= TERMS.TERM_END_DATE
AND (STPR_SPECIALIZATION_END >= TERMS.TERM_START_DATE OR STPR_SPECIALIZATION_END IS NULL)
)
AND STP_PROGRAM_TITLE = 'Elementary Education'






