SELECT STTR_STUDENT,
       PERSON.LAST_NAME,
       PERSON.FIRST_NAME,
       STATE

FROM STUDENT_TERMS_VIEW
JOIN PERSON ON STTR_STUDENT = PERSON.ID
JOIN (SELECT *
           FROM (SELECT STUDENT_ID,
                        STP_ACADEMIC_PROGRAM,
                        STP_PROGRAM_TITLE,
                        STP_START_DATE,
                        STP_CURRENT_STATUS,
                        ROW_NUMBER() OVER (PARTITION BY STUDENT_ID
                            ORDER BY STP_START_DATE DESC) AS rn
                 FROM STUDENT_ACAD_PROGRAMS_VIEW
                 WHERE STP_CURRENT_STATUS != 'Changed Program'
                 AND STP_START_DATE <= '2024-12-12'
                 ) ranked
            WHERE rn = 1)
            AS SAPV ON STUDENT_TERMS_VIEW.STTR_STUDENT = SAPV.STUDENT_ID
JOIN Z01_AAV_STUDENT_FIRST_MATRIC AS FM ON STUDENT_TERMS_VIEW.STTR_STUDENT = FM.ID
LEFT JOIN (SELECT DISTINCT STPR_STUDENT, STPR_ADMIT_STATUS
           FROM (
               SELECT   STPR_STUDENT,
                        STPR_ADMIT_STATUS,
                        ROW_NUMBER() OVER (PARTITION BY STPR_STUDENT
                        ORDER BY STPR_ADMIT_STATUS) AS rn
               FROM STUDENT_PROGRAMS_VIEW
               WHERE STPR_ADMIT_STATUS IN ('FY', 'TR')
               ) ranked
               WHERE rn = 1)
    AS FIRST_ADMIT ON STUDENT_TERMS_VIEW.STTR_STUDENT = FIRST_ADMIT.STPR_STUDENT
LEFT JOIN PERSON_ADDRESSES_VIEW AS PAV ON STUDENT_TERMS_VIEW.STTR_STUDENT = PAV.ID
WHERE STUDENT_TERMS_VIEW.STTR_TERM = '2024FA'
AND STUDENT_TERMS_VIEW.STTR_ACAD_LEVEL = 'UG'
AND SAPV.STP_CURRENT_STATUS != 'Not Returned'
AND
(STP_PROGRAM_TITLE != 'Non-Degree Seeking Students'
AND FM.TERM = '2024FA'
AND STPR_ADMIT_STATUS = 'FY')
AND IS_PREFERRED_RESIDENCE = 'Y'


SELECT *
FROM APPLICATIONS

SELECT *
FROM INSTITUTIONS

SELECT *
FROM INSTITUTIONS_ATTEND


SELECT *
FROM INSTITUTIONS_ATTEND_VIEW

SELECT *
FROM [2024FA_SNAPSHOT].dbo.PERSON_ADDRESSES_VIEW

select *
from PERSON_ADDRESSES_VIEW
where ADDRESS_LINE1 LIKE '%Benton%'
AND IS_PREFERRED_RESIDENCE = 'Y'