SELECT DISTINCT APPL_APPLICANT     AS ID,
        APPL_START_TERM                    AS TERM
FROM APPLICATIONS AS AP
JOIN STUDENT_ACAD_CRED AS AC
ON AP.APPL_APPLICANT = AC.STC_PERSON_ID AND AP.APPL_START_TERM = AC.STC_TERM
JOIN STC_STATUSES AS STAT ON AC.STUDENT_ACAD_CRED_ID = STAT.STUDENT_ACAD_CRED_ID AND POS = 1
JOIN STUDENT_TERMS_VIEW AS STV ON AP.APPL_APPLICANT = STV.STTR_STUDENT AND APPL_START_TERM = STV.STTR_TERM
WHERE APPL_DATE IS NOT NULL
AND STC_STATUS IN ('A', 'N')
AND STC_CRED_TYPE = 'INST'
-------FFUG-------------------
AND APPL_ADMIT_STATUS = 'FY' --First Time--
AND STV.STTR_STUDENT_LOAD = 'F'  --Full Time--
AND APPL_STUDENT_TYPE = 'UG'   --Undergraduate--
------TERM---------------------
AND APPL_START_TERM = '2023FA'