--(Begin 1)-------------------------------------------------------------------------------------------------------------
SELECT DISTINCT STC_PERSON_ID AS ID,
                FIRST_NAME,
                LAST_NAME,
                COALESCE(SP.PROGRAM, 'Unknown') AS PROGRAM,
                ST.STUDENT_TYPE AS TYPE,
                PERSON.GENDER
FROM STUDENT_ACAD_CRED AS STC
LEFT JOIN STC_STATUSES AS STATUS ON STC.STUDENT_ACAD_CRED_ID = STATUS.STUDENT_ACAD_CRED_ID AND STATUS.POS = 1
LEFT JOIN STUDENT_COURSE_SEC AS SEC ON STC.STC_STUDENT_COURSE_SEC = SEC.STUDENT_COURSE_SEC_ID
JOIN PERSON ON STC.STC_PERSON_ID = PERSON.ID
LEFT JOIN (
    SELECT   STUDENT_ID,
             STP_PROGRAM_TITLE AS PROGRAM,
             ROW_NUMBER() OVER (PARTITION BY STUDENT_ID ORDER BY STP_START_DATE DESC) AS RANK
      FROM STUDENT_ACAD_PROGRAMS_VIEW AS SAPV
      WHERE STP_CURRENT_STATUS = 'Active'
      ) AS SP ON STC_PERSON_ID = SP.STUDENT_ID AND SP.RANK = 1
LEFT JOIN (
    SELECT STUDENTS_ID,
            STT_DESC AS STUDENT_TYPE,
            ROW_NUMBER() OVER (PARTITION BY STUDENTS_ID ORDER BY STU_TYPE_DATES DESC) AS RANK
    FROM STU_TYPE_INFO
    JOIN STUDENT_TYPES ON STU_TYPES = STUDENT_TYPES_ID
) AS ST ON STC_PERSON_ID = STUDENTS_ID AND ST.RANK = 1
WHERE STC_TERM = '2024FA'
AND STATUS.STC_STATUS IN ('N', 'A')
AND STC.STC_CRED > 0
--(End 1)---------------------------------------------------------------------------------------------------------------
ORDER BY LAST_NAME, FIRST_NAME