SELECT STUDENT_ID,
		LAST_NAME,
		FIRST_NAME,
		PERSON_EMAIL_ADDRESSES AS EMAIL,
		MINOR
FROM ( 
		SELECT CURRENT_MINORS.MINORS_DESC AS MINOR,
			   STUDENT_ID
		FROM MINORS AS CURRENT_MINORS
		CROSS JOIN (SELECT * FROM STUDENT_ACAD_PROGRAMS_VIEW WHERE STP_CURRENT_STATUS = 'Active') AS SAPV
		LEFT JOIN STPR_MINOR_LIST_VIEW ON SAPV.STUDENT_ID = STPR_MINOR_LIST_VIEW.STPR_STUDENT AND SAPV.STP_ACADEMIC_PROGRAM = STPR_MINOR_LIST_VIEW.STPR_ACAD_PROGRAM
		LEFT JOIN MINORS AS ADDED_MINOR ON STPR_MINOR_LIST_VIEW.STPR_MINORS = ADDED_MINOR.MINORS_ID
		WHERE 
		CURRENT_MINORS.MINORS_DESC = ADDED_MINOR.MINORS_DESC
		AND STPR_MINOR_LIST_VIEW.STPR_MINOR_END_DATE IS NULL
		GROUP BY CURRENT_MINORS.MINORS_DESC, STUDENT_ID
	) AS STUDENT_MINORS
JOIN PERSON ON STUDENT_MINORS.STUDENT_ID = PERSON.ID
JOIN PEOPLE_EMAIL ON STUDENT_MINORS.STUDENT_ID = PEOPLE_EMAIL.ID
WHERE PERSON_PREFERRED_EMAIL = 'Y'
ORDER BY MINOR, LAST_NAME, FIRST_NAME
				
