SELECT *
FROM SPT_STUDENT_PROGRAMS
JOIN ODS_TERMS AS GRADUATING_TERM ON TERMS_ID = '2025SP'
WHERE STPR_CURRENT_STATUS = 'G'
AND END_DATE <= GRADUATING_TERM.TERM_END_DATE
AND END_DATE >= GRADUATING_TERM.TERM_START_DATE


SELECT *
FROM Z01_GRADUATES
WHERE GRAD_TERM = '2025SP'

SELECT *
FROM SPT_ACAD_PROGRAMS