SELECT STTR_STUDENT,
        LAST_NAME,
        FIRST_NAME,
        STP_PROGRAM_TITLE


FROM STUDENT_TERMS_VIEW
JOIN PERSON ON STTR_STUDENT = PERSON.ID
JOIN (SELECT *
           FROM (SELECT STUDENT_ID,
                        STP_ACADEMIC_PROGRAM,
                        STP_PROGRAM_TITLE,
                        STP_START_DATE,
                        STP_CURRENT_STATUS,
                        ROW_NUMBER() OVER (PARTITION BY STUDENT_ID
                            ORDER BY STP_START_DATE DESC) AS rn
                 FROM STUDENT_ACAD_PROGRAMS_VIEW
                 WHERE STP_CURRENT_STATUS != 'Changed Program'
                 AND STP_START_DATE <= (
                     SELECT TOP 1 TERM_END_DATE
                     FROM TERMS
                     WHERE TERMS_ID = '2023FA')
                 ) ranked
            WHERE rn = 1)
            AS SAPV ON STUDENT_TERMS_VIEW.STTR_STUDENT = SAPV.STUDENT_ID
JOIN Z01_AAV_STUDENT_FIRST_MATRIC AS FM ON STUDENT_TERMS_VIEW.STTR_STUDENT = FM.ID
LEFT JOIN (SELECT DISTINCT STPR_STUDENT, STPR_ADMIT_STATUS
           FROM (
               SELECT   STPR_STUDENT,
                        STPR_ADMIT_STATUS,
                        ROW_NUMBER() OVER (PARTITION BY STPR_STUDENT
                        ORDER BY STPR_ADMIT_STATUS) AS rn
               FROM STUDENT_PROGRAMS_VIEW
               WHERE STPR_ADMIT_STATUS IN ('FY', 'TR')
               ) ranked
               WHERE rn = 1)
    AS FIRST_ADMIT ON STUDENT_TERMS_VIEW.STTR_STUDENT = FIRST_ADMIT.STPR_STUDENT
WHERE STUDENT_TERMS_VIEW.STTR_TERM = '2023FA'
AND STUDENT_TERMS_VIEW.STTR_ACAD_LEVEL = 'UG'
AND (STUDENT_TERMS_VIEW.STTR_STUDENT_LOAD NOT IN ('F', 'O')
         OR STUDENT_TERMS_VIEW.STTR_STUDENT_LOAD IS NULL)
AND SAPV.STP_CURRENT_STATUS != 'Not Returned'
AND (
    STP_PROGRAM_TITLE != 'Non-Degree Seeking Students'
    AND FM.TERM = '2023FA'
    AND STPR_ADMIT_STATUS = 'FY'
    ) --Previous Cohort


SELECT *
FROM (
SELECT STUDENT_TERMS_VIEW.STTR_STUDENT,
       CASE
           WHEN STILL_ENROLLED.STTR_STUDENT IS NULL THEN 0 ELSE 1 END AS STILL_ENROLLED,
        CASE
            WHEN SINCE_GRADUATED.STUDENT_ID IS NULL THEN 0 ELSE 1 END AS SINCE_GRADUATED

FROM STUDENT_TERMS_VIEW
JOIN PERSON ON STTR_STUDENT = PERSON.ID
JOIN (SELECT *
           FROM (SELECT STUDENT_ID,
                        STP_ACADEMIC_PROGRAM,
                        STP_PROGRAM_TITLE,
                        STP_START_DATE,
                        STP_CURRENT_STATUS,
                        ROW_NUMBER() OVER (PARTITION BY STUDENT_ID
                            ORDER BY STP_START_DATE DESC) AS rn
                 FROM STUDENT_ACAD_PROGRAMS_VIEW
                 WHERE STP_CURRENT_STATUS != 'Changed Program'
                 AND STP_START_DATE <= (
                     SELECT TOP 1 TERM_END_DATE
                     FROM TERMS
                     WHERE TERMS_ID = '2023FA')
                 ) ranked
            WHERE rn = 1)
            AS SAPV ON STUDENT_TERMS_VIEW.STTR_STUDENT = SAPV.STUDENT_ID
JOIN Z01_AAV_STUDENT_FIRST_MATRIC AS FM ON STUDENT_TERMS_VIEW.STTR_STUDENT = FM.ID
LEFT JOIN (SELECT DISTINCT STPR_STUDENT, STPR_ADMIT_STATUS
           FROM (
               SELECT   STPR_STUDENT,
                        STPR_ADMIT_STATUS,
                        ROW_NUMBER() OVER (PARTITION BY STPR_STUDENT
                        ORDER BY STPR_ADMIT_STATUS) AS rn
               FROM STUDENT_PROGRAMS_VIEW
               WHERE STPR_ADMIT_STATUS IN ('FY', 'TR')
               ) ranked
               WHERE rn = 1)
    AS FIRST_ADMIT ON STUDENT_TERMS_VIEW.STTR_STUDENT = FIRST_ADMIT.STPR_STUDENT
LEFT JOIN (
    SELECT STTR_STUDENT
    FROM STUDENT_TERMS_VIEW
    WHERE STTR_TERM = '2024FA'
) AS STILL_ENROLLED ON STUDENT_TERMS_VIEW.STTR_STUDENT = STILL_ENROLLED.STTR_STUDENT
LEFT JOIN (
    SELECT STUDENT_ID
    FROM STUDENT_ACAD_PROGRAMS_VIEW
    WHERE STP_CURRENT_STATUS_DATE >= (
                     SELECT TOP 1 TERM_START_DATE
                     FROM TERMS
                     WHERE TERMS_ID = '2023FA')
    AND STP_CURRENT_STATUS = 'Graduated'
) AS SINCE_GRADUATED ON STUDENT_TERMS_VIEW.STTR_STUDENT = SINCE_GRADUATED.STUDENT_ID
WHERE STUDENT_TERMS_VIEW.STTR_TERM = '2023FA'
AND STUDENT_TERMS_VIEW.STTR_ACAD_LEVEL = 'UG'
AND  (STUDENT_TERMS_VIEW.STTR_STUDENT_LOAD NOT IN ('F', 'O')
         OR STUDENT_TERMS_VIEW.STTR_STUDENT_LOAD IS NULL)
AND SAPV.STP_CURRENT_STATUS != 'Not Returned'
AND (
    STP_PROGRAM_TITLE != 'Non-Degree Seeking Students'
    AND FM.TERM = '2023FA'
    AND STPR_ADMIT_STATUS = 'FY'
    )) AS X
WHERE STILL_ENROLLED = 1 OR SINCE_GRADUATED = 1 --Previous Cohort Retained


SELECT * FROM STUDENT_TERMS_VIEW