SELECT ENROLL_TERM AS TERM
		,COUNT(*) AS ENROLLMENT
FROM (
		SELECT ENROLL_TERM
				,STUDENT_ID
		FROM STUDENT_ENROLLMENT_VIEW
		WHERE ENROLL_CURRENT_STATUS = 'New'
		GROUP BY ENROLL_TERM
				,STUDENT_ID
		) AS TERM_STUDENTS
WHERE ENROLL_TERM IN ('2022FA', '2023SP', '2023FA', '2024SP', '2024FA', '2025SP')
GROUP BY ENROLL_TERM
ORDER BY ENROLL_TERM

