SELECT *
FROM (
	SELECT	PERSON.ID
			,PERSON.LAST_NAME
			,PERSON.FIRST_NAME
			,TERM_2024SP.STUDENT_ID AS TERM_2024SP
			,TERM_2025SP.STUDENT_ID AS TERM_2025SP
			,LATEST_STATUS.STP_CURRENT_STATUS AS LATEST_STATUS
			,LATEST_STATUS.STP_CURRENT_STATUS_DATE AS LATEST_STATUS_DATE
	FROM PERSON
	JOIN (
			SELECT STUDENT_ID, STP_CURRENT_STATUS, STP_CURRENT_STATUS_DATE
			FROM (
				SELECT STUDENT_ID
				,STP_CURRENT_STATUS
				,STP_CURRENT_STATUS_DATE
				,ROW_NUMBER() OVER (PARTITION BY STUDENT_ID ORDER BY STP_CURRENT_STATUS_DATE DESC) AS rn
				FROM STUDENT_ACAD_PROGRAMS_VIEW
				WHERE STP_CURRENT_STATUS != 'Changed Program'
			) ranked
			WHERE rn = 1
			) AS LATEST_STATUS ON LATEST_STATUS.STUDENT_ID = PERSON.ID
	JOIN (
			SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW 
			WHERE ENROLL_TERM = '2024SP'
			AND ENROLL_CURRENT_STATUS NOT IN ('Deleted', 'Dropped', 'Withdrawn', 'Transfer Equiv Eval')
		  ) AS TERM_2024SP ON PERSON.ID = TERM_2024SP.STUDENT_ID
	LEFT JOIN (
				SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW 
				WHERE ENROLL_TERM = '2025SP'
				AND ENROLL_CURRENT_STATUS NOT IN ('Deleted', 'Dropped', 'Withdrawn', 'Transfer Equiv Eval')
			) AS TERM_2025SP ON PERSON.ID = TERM_2025SP.STUDENT_ID
	WHERE TERM_2025SP.STUDENT_ID IS NULL
) AS LOST_IN_2025
ORDER BY LATEST_STATUS, LATEST_STATUS_DATE, LAST_NAME, FIRST_NAME