

SELECT PERSON.ID,
		PERSON.LAST_NAME,
		PERSON.FIRST_NAME,
		(CASE WHEN TERM_2022FA.STUDENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS TERM_2022FA,
		(CASE WHEN TERM_2023SP.STUDENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS TERM_2023SP,
		(CASE WHEN TERM_2023FA.STUDENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS TERM_2023FA,
		(CASE WHEN TERM_2024SP.STUDENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS TERM_2024SP,
		(CASE WHEN TERM_2024FA.STUDENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS TERM_2024FA,
		(CASE WHEN TERM_2025SP.STUDENT_ID IS NOT NULL THEN 1 ELSE 0 END) AS TERM_2025SP
FROM (
		SELECT DISTINCT STUDENT_ID
		FROM STUDENT_ENROLLMENT_VIEW
		WHERE ENROLL_CURRENT_STATUS = 'New'
		AND ENROLL_TERM IN ('2022FA', '2023SP', '2023FA', '2024SP', '2024FA', '2025SP')
		) AS TERM_STUDENTS
JOIN PERSON ON TERM_STUDENTS.STUDENT_ID = PERSON.ID
LEFT JOIN (SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW WHERE ENROLL_TERM = '2022FA' AND ENROLL_CURRENT_STATUS = 'New') AS TERM_2022FA ON TERM_STUDENTS.STUDENT_ID = TERM_2022FA.STUDENT_ID
LEFT JOIN (SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW WHERE ENROLL_TERM = '2023SP' AND ENROLL_CURRENT_STATUS = 'New') AS TERM_2023SP ON TERM_STUDENTS.STUDENT_ID = TERM_2023SP.STUDENT_ID
LEFT JOIN (SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW WHERE ENROLL_TERM = '2023FA' AND ENROLL_CURRENT_STATUS = 'New') AS TERM_2023FA ON TERM_STUDENTS.STUDENT_ID = TERM_2023FA.STUDENT_ID
LEFT JOIN (SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW WHERE ENROLL_TERM = '2024SP' AND ENROLL_CURRENT_STATUS = 'New') AS TERM_2024SP ON TERM_STUDENTS.STUDENT_ID = TERM_2024SP.STUDENT_ID
LEFT JOIN (SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW WHERE ENROLL_TERM = '2024FA' AND ENROLL_CURRENT_STATUS = 'New') AS TERM_2024FA ON TERM_STUDENTS.STUDENT_ID = TERM_2024FA.STUDENT_ID
LEFT JOIN (SELECT DISTINCT STUDENT_ID FROM STUDENT_ENROLLMENT_VIEW WHERE ENROLL_TERM = '2025SP' AND ENROLL_CURRENT_STATUS = 'New') AS TERM_2025SP ON TERM_STUDENTS.STUDENT_ID = TERM_2025SP.STUDENT_ID
ORDER BY TERM_2022FA DESC
		 ,TERM_2023SP DESC
		 ,TERM_2023FA DESC
		 ,TERM_2024SP DESC
		 ,TERM_2024FA DESC
		 ,TERM_2025SP DESC
		 ,LAST_NAME
		,FIRST_NAME

