--(Begin 2)--------------------------------------------------------------------------------------------
SELECT CITY,
       [AR],
       [CA],
       [CK],
       [H],
       [MAI],
       [PHY]
FROM (
--(Begin 1)--------------------------------------------------------------------------------------------
SELECT DISTINCT STUDENT_ID,
                      CASE WHEN STATE IS NULL THEN 'Unknown' ELSE COALESCE(CITY, 'Unknown') END AS CITY,
                      ADDRESS_TYPE
      FROM STUDENT_ENROLLMENT_VIEW AS SEV
               JOIN PERSON_ADDRESSES_VIEW AS PAV ON SEV.STUDENT_ID = PAV.ID
      WHERE ENROLL_CURRENT_STATUS IN ('New', 'Add')
        AND (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
        AND ENROLL_TERM = '2024FA'
        AND (STATE = 'MT' OR STATE IS NULL)
--(End 1)----------------------------------------------------------------------------------------------
) AS X
PIVOT (COUNT(STUDENT_ID) FOR ADDRESS_TYPE IN (
        [AR],
       [CA],
       [CK],
       [H],
       [MAI],
       [PHY]
        )) AS X
--(End 2)--------------------------------------------------------------------------------------------


SELECT CITY,
       [AR],
       [CA],
       [CK],
       [H],
       [MAI],
       [PHY]
FROM (
SELECT DISTINCT STUDENT_ID,
                COALESCE(PAV.CITY, 'Unknown') AS CITY,
                ADDRESS_TYPE
FROM STUDENT_ENROLLMENT_VIEW AS SEV
JOIN PERSON_ADDRESSES_VIEW AS PAV ON SEV.STUDENT_ID = PAV.ID
LEFT JOIN (VALUES
('Alberton', 'Mineral'),
('Anaconda', 'Deer Lodge'),
('Arlee', 'Lake'),
('Ashland', 'Rosebud'),
('Baker', 'Fallon'),
('Belfry', 'Carbon'),
('Belgrade', 'Gallatin'),
('Belt', 'Cascade'),
('Big Sandy', 'Chouteau'),
('Big Timber', 'Sweet Grass'),
('Bigfork', 'Flathead'),
('Billings', 'Yellowstone'),
('Boulder', 'Jefferson'),
('Bozeman', 'Gallatin'),
('Bridger', 'Carbon'),
('Broadus', 'Powder River'),
('Broadview', 'Yellowstone'),
('Brockton', 'Roosevelt'),
('Browning', 'Glacier'),
('Busby', 'Big Horn'),
('Butte', 'Silver Bow'),
('Cascade', 'Cascade'),
('Charlo', 'Lake'),
('Chester', 'Liberty'),
('Chinook', 'Blaine'),
('Choteau', 'Teton'),
('Circle', 'McCone'),
('Clancy', 'Jefferson'),
('Clyde Park', 'Park'),
('Cohagen', 'Garfield'),
('Colstrip', 'Rosebud'),
('Columbia Falls', 'Flathead'),
('Columbia Fls', 'Flathead'),
('Columbus', 'Stillwater'),
('Conrad', 'Pondera'),
('Corvallis', 'Ravalli'),
('Culbertson', 'Roosevelt'),
('Cut Bank', 'Glacier'),
('Darby', 'Ravalli'),
('Deer Lodge', 'Powell'),
('Denton', 'Fergus'),
('Dillon', 'Beaverhead'),
('Dixon', 'Sanders'),
('Drummond', 'Granite'),
('Dutton', 'Teton'),
('E. Helena', 'Lewis and Clark'),
('East Helena', 'Lewis and Clark'),
('Ekalaka', 'Carter'),
('Ennis', 'Madison'),
('Eureka', 'Lincoln'),
('Fairfield', 'Teton'),
('Fairview', 'Richland'),
('Florence', 'Ravalli'),
('Forsyth', 'Rosebud'),
('Fort Benton', 'Chouteau'),
('Fort Harrison', 'Lewis and Clark'),
('Fort Peck', 'Valley'),
('Frenchtown', 'Missoula'),
('Fromberg', 'Carbon'),
('Geraldine', 'Chouteau'),
('Glasgow', 'Valley'),
('Glendive', 'Dawson'),
('Great Falls', 'Cascade'),
('Hamilton', 'Ravalli'),
('Hardin', 'Big Horn'),
('Harlem', 'Blaine'),
('Harlowton', 'Wheatland'),
('Havre', 'Hill'),
('Hays', 'Blaine'),
('Helena', 'Lewis and Clark'),
('Hot Springs', 'Sanders'),
('Huntley', 'Yellowstone'),
('Huson', 'Missoula'),
('Hysham', 'Treasure'),
('Jefferson City', 'Jefferson'),
('Jefferson Cty', 'Jefferson'),
('Joliet', 'Carbon'),
('Jordan', 'Garfield'),
('Judith Gap', 'Wheatland'),
('Kalispell', 'Flathead'),
('Kalipell', 'Flathead'),
('Laurel', 'Yellowstone'),
('Lewistown', 'Fergus'),
('Libby', 'Lincoln'),
('Livingston', 'Park'),
('Lodge Grass', 'Big Horn'),
('Lolo', 'Missoula'),
('Malta', 'Phillips'),
('Manhattan', 'Gallatin'),
('Marion', 'Flathead'),
('Mc Allister', 'Madison'),
('Miles City', 'Custer'),
('Missoula', 'Missoula'),
('Molt', 'Stillwater'),
('Montana City', 'Jefferson'),
('Nashua', 'Valley'),
('Park City', 'Stillwater'),
('Philipsburg', 'Granite'),
('Pinesdale', 'Ravalli'),
('Plains', 'Sanders'),
('Plentywood', 'Sheridan'),
('Polson', 'Lake'),
('Poplar', 'Roosevelt'),
('Power', 'Teton'),
('Raynesford', 'Judith Basin'),
('Red Lodge', 'Carbon'),
('Roberts', 'Carbon'),
('Ronan', 'Lake'),
('Roundup', 'Musselshell'),
('Ryegate', 'Golden Valley'),
('Scobey', 'Daniels'),
('Seeley Lake', 'Missoula'),
('Shelby', 'Toole'),
('Sheridan', 'Madison'),
('Sidney', 'Richland'),
('Simms', 'Cascade'),
('Somers', 'Flathead'),
('St Ignatius', 'Lake'),
('St. Ignatius', 'Lake'),
('Stanford', 'Judith Basin'),
('Stevensville', 'Ravalli'),
('Stockett', 'Cascade'),
('Sunburst', 'Toole'),
('Superior', 'Mineral'),
('Swan Lake', 'Lake'),
('Terry', 'Prairie'),
('Thompson Falls', 'Sanders'),
('Thompson Fls', 'Sanders'),
('Three Forks', 'Gallatin'),
('Townsend', 'Broadwater'),
('Trout Creek', 'Sanders'),
('Troy', 'Lincoln'),
('Twin Bridges', 'Madison'),
('Ulm', 'Cascade'),
('Valier', 'Pondera'),
('Victor', 'Ravalli'),
('W Yellowstone', 'Gallatin'),
('Walkerville', 'Silver Bow'),
('West Yellowstone', 'Gallatin'),
('White Sulphur Springs', 'Meagher'),
('Whitefish', 'Flathead'),
('Whitehall', 'Jefferson'),
('Wht Sphr Spgs', 'Meagher'),
('Wibaux', 'Wibaux'),
('Winifred', 'Fergus'),
('Wolf Point', 'Roosevelt'),
('Worden', 'Yellowstone')
) AS CITY_COUNTY(CITY, COUNTY) ON PAV.CITY = CITY_COUNTY.CITY
WHERE ENROLL_CURRENT_STATUS IN ('New', 'Add')
AND (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
AND ENROLL_TERM = '2024FA'
AND STATE = 'MT'
AND COUNTY IS NULL
) AS X
PIVOT (COUNT(STUDENT_ID) FOR ADDRESS_TYPE IN (
        [AR],
       [CA],
       [CK],
       [H],
       [MAI],
       [PHY]
        )) AS X

-----------------------------------------------------------------------------------------------------------------------


SELECT CITY,
       [AR],
       [CA],
       [CK],
       [H],
       [MAI],
       [PHY]
FROM (
SELECT DISTINCT STUDENT_ID,
                COALESCE(PAV.CITY, 'Unknown') AS CITY,
                ADDRESS_TYPE
FROM STUDENT_ENROLLMENT_VIEW AS SEV
JOIN PERSON_ADDRESSES_VIEW AS PAV ON SEV.STUDENT_ID = PAV.ID
LEFT JOIN (VALUES
('Absarokee', 'Stillwater'),
('Alberton', 'Mineral'),
('Anaconda', 'Deer Lodge'),
('Arlee', 'Lake'),
('Augusta', 'Lewis and Clark'),
('Bainville', 'Roosevelt'),
('Baker', 'Fallon'),
('Basin', 'Jefferson'),
('Belgrade', 'Gallatin'),
('Belt', 'Cascade'),
('Big Sky', 'Gallatin'),
('Big Timber', 'Sweet Grass'),
('Bigfork', 'Flathead'),
('Billings', 'Yellowstone'),
('Black Eagle', 'Yellowstone'),
('Boulder', 'Jefferson'),
('Box Elder', 'Hill'),
('Boyd', 'Carbon'),
('Bozeman', 'Gallatin'),
('Bridger', 'Carbon'),
('Broadview', 'Yellowstone'),
('Butte', 'Silver Bow'),
('Bynum', 'Teton'),
('Carter', 'Chouteau'),
('Cascade', 'Cascade'),
('Charlo', 'Lake'),
('Chester', 'Liberty'),
('Chinook', 'Blaine'),
('Choteau', 'Teton'),
('Circle', 'McCone'),
('Clancy', 'Jefferson'),
('Clinton', 'Missoula'),
('Clyde Park', 'Park'),
('Colstrip', 'Rosebud'),
('Columbia Falls', 'Flathead'),
('Columbus', 'Stillwater'),
('Condon', 'Pondera'),
('Conrad', 'Pondera'),
('Coram', 'Glacier'),
('Corvallis', 'Ravalli'),
('Cut Bank', 'Glacier'),
('Darby', 'Ravalli'),
('Deer Lodge', 'Powell'),
('Dillon', 'Beaverhead'),
('Drummond', 'Granite'),
('Dutton', 'Teton'),
('E Helena', 'Lewis and Clark'),
('E. Helena', 'Lewis and Clark'),
('East Helena', 'Lewis and Clark'),
('Elliston', 'Powell'),
('Ennis', 'Madison'),
('Eureka', 'Lincoln'),
('Fairfield', 'Teton'),
('Florence', 'Ravalli'),
('Floweree', 'Ravalli'),
('Forsyth', 'Rosebud'),
('Fort Benton', 'Chouteau'),
('Fort Harrison', 'Lewis and Clark'),
('Fort Peck', 'Valley'),
('Fort Shaw', 'Cascade'),
('Frenchtown', 'Missoula'),
('Ft Harrison', 'Lewis and Clark'),
('Gallatin Gateway', 'Gallatin'),
('Gardiner', 'Park'),
('Geyser', 'Judith Basin'),
('Gildford', 'Hill'),
('Glasgow', 'Valley'),
('Glendive', 'Dawson'),
('Great Falls', 'Cascade'),
('Hall', 'Granite'),
('Hamilton', 'Ravalli'),
('Hardin', 'Big Horn'),
('Harlowton', 'Wheatland'),
('Havre', 'Hill'),
('Heart Butte', 'Pondera'),
('Helena', 'Lewis and Clark'),
('Helmville', 'Powell'),
('Highwood', 'Chouteau'),
('Hilger', 'Fergus'),
('Hingham', 'Hill'),
('Hinsdale', 'Lewis and Clark'),
('Hobson', 'Judith Basin'),
('Huson', 'Missoula'),
('Jefferson City', 'Jefferson'),
('Joliet', 'Carbon'),
('Judith Gap', 'Wheatland'),
('Kalispell', 'Flathead'),
('Kinsey', 'Custer'),
('Lakeside', 'Flathead'),
('Lambert', 'Richland'),
('Laurel', 'Yellowstone'),
('Lewistown', 'Fergus'),
('Libby', 'Lincoln'),
('Lincoln', 'Lewis and Clark'),
('Livingston', 'Park'),
('Lolo', 'Missoula'),
('Manhattan', 'Gallatin'),
('Mc Allister', 'Madison'),
('Miles City', 'Custer'),
('Missoula', 'Missoula'),
('Molt', 'Yellowstone'),
('Montana City', 'Jefferson'),
('Moore', 'Fergus'),
('Philipsburg', 'Granite'),
('Plentywood', 'Sheridan'),
('Polson', 'Lake'),
('Pompeys Pillar', 'Yellowstone'),
('Rapelje', 'Stillwater'),
('Red Lodge', 'Carbon'),
('Reed Point', 'Stillwater'),
('Ringling', 'Meagher'),
('Roberts', 'Carbon'),
('Ronan', 'Lake'),
('Roundup', 'Musselshell'),
('Rudyard', 'Hill'),
('Saint Ignatius', 'Lake'),
('Scobey', 'Daniels'),
('Seeley Lake', 'Missoula'),
('Shelby', 'Richland'),
('Sheridan', 'Madison'),
('Sidney', 'Richland'),
('Silesia', 'Carbon'),
('Simms', 'Cascade'),
('St Ignatius', 'Lake'),
('Stevensville', 'Ravalli'),
('Stockett', 'Cascade'),
('Sun River', 'Cascade'),
('Sunburst', 'Toole'),
('Superior', 'Mineral'),
('Thompson Falls', 'Sanders'),
('Three Forks', 'Gallatin'),
('Townsend', 'Broadwater'),
('Trout Creek', 'Sanders'),
('Valier', 'Pondera'),
('Vaughn', 'Cascade'),
('Victor', 'Ravalli'),
('White Sulphur Springs', 'Meagher'),
('Whitefish', 'Flathead'),
('Whitehall', 'Jefferson'),
('Wibaux', 'Wibaux'),
('Winifred', 'Fergus'),
('Winston', 'Broadwater'),
('Wise River', 'Beaverhead')
) AS CITY_COUNTY(CITY, COUNTY) ON PAV.CITY = CITY_COUNTY.CITY
WHERE ENROLL_CURRENT_STATUS IN ('New', 'Add')
AND (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
AND ENROLL_TERM = '2024FA'
AND STATE = 'MT'
AND COUNTY IS NULL
) AS X
PIVOT (COUNT(STUDENT_ID) FOR ADDRESS_TYPE IN (
        [AR],
       [CA],
       [CK],
       [H],
       [MAI],
       [PHY]
        )) AS X