Select SEC_TERM, 
	SEC_NAME, 
	SEC_SHORT_TITLE, 
	SEC_FACULTY_INFO, 
	COUNT_ACTIVE_STUDENTS
FROM COURSE_SECTIONS
	JOIN COURSE_SECTIONS_COUNT_VIEW ON COURSE_SECTIONS.COURSE_SECTIONS_ID = COURSE_SECTIONS_COUNT_VIEW.COURSE_SECTIONS_ID
WHERE SEC_START_DATE >= '2021-08-01'
ORDER BY SEC_START_DATE
