SELECT SUM(WEIGHT) AS FTE
FROM (
SELECT ID,
       LAST_NAME,
       FIRST_NAME,
       CASE
           WHEN STTR_STUDENT_LOAD IN ('F', 'O') THEN 1
            ELSE 1.0/3 END AS WEIGHT
FROM STUDENT_TERMS_VIEW AS STV
JOIN PERSON ON STV.STTR_STUDENT = PERSON.ID
WHERE STTR_TERM = '2025SP') AS X