SELECT SUM(WEIGHT) AS FTE
FROM (
SELECT CASE
           WHEN STTR_STUDENT_LOAD IN ('F', 'O') THEN 1
            ELSE 1.0/3 END AS WEIGHT
FROM STUDENT_TERMS_VIEW AS STV
WHERE STTR_TERM = '2025SP') AS X