SELECT ID, LAST_NAME, FIRST_NAME
FROM PERSON
WHERE 
(LAST_NAME = 'Appel' AND FIRST_NAME='Sidney')
OR (LAST_NAME = 'Arnold' AND FIRST_NAME='Mekenzie')
OR (LAST_NAME = 'Arthur' AND FIRST_NAME='Erika')
OR (LAST_NAME = 'Bahou' AND FIRST_NAME='Natalie')
OR (LAST_NAME = 'Boese' AND FIRST_NAME='Courtney')
OR (LAST_NAME = 'Bui' AND FIRST_NAME='Mailee')
OR (LAST_NAME = 'Rubio-Casanova' AND FIRST_NAME='Angie')
OR (LAST_NAME = 'Cossairt' AND FIRST_NAME='Jackson')
OR (LAST_NAME = 'Countryman' AND FIRST_NAME='Amber')
OR (LAST_NAME = 'Early' AND FIRST_NAME='Sarah')
OR (LAST_NAME = 'Edwards' AND FIRST_NAME='Trinity')
OR (LAST_NAME = 'Gleasman' AND FIRST_NAME='Gunner')
OR (LAST_NAME = 'Goodman' AND FIRST_NAME='Jonathan')
OR (LAST_NAME = 'Hansch' AND FIRST_NAME='Jakob')
OR (LAST_NAME = 'Hatfield' AND FIRST_NAME='Corinna')
OR (LAST_NAME = 'Koivu' AND FIRST_NAME='Isabel')
OR (LAST_NAME = 'Lewis' AND FIRST_NAME='Madison')
OR (LAST_NAME = 'Lord' AND FIRST_NAME='Deanna')
OR (LAST_NAME = 'Navarro' AND FIRST_NAME='Brianna')
OR (LAST_NAME = 'Patek' AND FIRST_NAME='Emma')
OR (LAST_NAME = 'Prendergast' AND FIRST_NAME='Tess')
OR (LAST_NAME = 'Prka' AND FIRST_NAME='Jack')
OR (LAST_NAME = 'Quinn' AND FIRST_NAME='Ryan')
OR (LAST_NAME = 'Ramsey' AND FIRST_NAME='Eleanor')
OR (LAST_NAME = 'Reiners' AND FIRST_NAME='Ashtyn')
OR (LAST_NAME = 'Romo' AND FIRST_NAME='Josiah')
OR (LAST_NAME = 'Ryan' AND FIRST_NAME='Reagan')
OR (LAST_NAME = 'Sempf' AND FIRST_NAME='Hannah')
OR (LAST_NAME = 'Smith' AND FIRST_NAME='Olivia')
OR (LAST_NAME = 'Vandehey' AND FIRST_NAME='Brooke')
OR (LAST_NAME = 'Vandehey' AND FIRST_NAME='Madeline')
OR (LAST_NAME = 'Venner' AND FIRST_NAME='Kennedy')
OR (LAST_NAME = 'Visser' AND FIRST_NAME='Madeline')
OR (LAST_NAME = 'Yochum' AND FIRST_NAME='Mason')
ORDER BY LAST_NAME