SELECT ID,
       STUDENT_OVERALL_CUM_GPA,
       STUDENT_TERM_GPA,
       COUNT(*) AS COUNT
FROM (SELECT PERSON.ID,
             STUDENT_OVERALL_CUM_GPA,
             STUDENT_TERM_GPA
      FROM [PERSON]
               JOIN [STUDENT_CUM_GPA_VIEW] ON PERSON.ID = STUDENT_CUM_GPA_VIEW.STUDENT_ID
               JOIN [STUDENT_TERM_GPA_VIEW] ON PERSON.ID = STUDENT_TERM_GPA_VIEW.STUDENT_ID
               Left JOIN [STA_OTHER_COHORTS_VIEW] ON PERSON.ID = STA_OTHER_COHORTS_VIEW.STA_STUDENT
      WHERE STUDENT_TERM_GPA_VIEW.TERM = '2024FA'
        and (
          STA_OTHER_COHORT_GROUPS IN
          ('HNRS', 'FOR', 'ROTC', 'VETS', 'INTL', 'ACCESS', 'CIC', 'GRSET', 'GRSUA', 'GRSMX') OR
          STA_OTHER_COHORT_GROUPS IS NULL OR
          STA_OTHER_COHORT_END_DATES < GETDATE()
          )) AS X
GROUP BY ID, STUDENT_OVERALL_CUM_GPA, STUDENT_TERM_GPA
HAVING COUNT(*) > 1