SELECT  TERM
		,MAJOR
		,COUNT(*) AS STUDENT_COUNT
		,AVG(CUMULATIVE_GPA) AS AVG_CUMULAIVE_GPA
FROM (
		SELECT PERSON.ID,
				LAST_NAME,
				FIRST_NAME,
				MAJORS.MAJ_DESC AS MAJOR,
				STTR_TERM AS TERM,
				GPA.STUDENT_OVERALL_CUM_GPA AS CUMULATIVE_GPA
		FROM PERSON
		JOIN (
				SELECT STTR_STUDENT
						,STTR_TERM
				FROM STUDENT_TERMS_VIEW
				WHERE STTR_TERM IN ('2021FA', '2022SP', '2022FA', '2023SP', '2023FA', '2024SP', '2024FA', '2025SP')
			) RECENT_STUDENTS ON PERSON.ID = RECENT_STUDENTS.STTR_STUDENT
		JOIN STUDENT_ACAD_PROGRAMS_VIEW AS SAPV ON PERSON.ID = SAPV.STUDENT_ID
		CROSS JOIN MAJORS
		JOIN STUDENT_CUM_GPA_VIEW AS GPA ON PERSON.ID = GPA.STUDENT_ID
		LEFT JOIN STPR_MAJOR_LIST_VIEW ON SAPV.STUDENT_ID = STPR_MAJOR_LIST_VIEW.STPR_STUDENT AND SAPV.STP_ACADEMIC_PROGRAM = STPR_MAJOR_LIST_VIEW.STPR_ACAD_PROGRAM
		LEFT JOIN MAJORS AS ADDNL_MAJOR ON STPR_MAJOR_LIST_VIEW.STPR_ADDNL_MAJORS = ADDNL_MAJOR.MAJORS_ID
		LEFT JOIN MAJORS AS MAIN_MAJOR ON SAPV.STP_MAJOR1 = MAIN_MAJOR.MAJORS_ID
		WHERE MAJORS.MAJ_DESC IN ('Business: Managmt and Marktng', 'Business: Financial Planning', 'Business: Acctng & Stratg Finc')
		AND (
				MAJORS.MAJ_DESC = MAIN_MAJOR.MAJ_DESC
				OR (
					MAJORS.MAJ_DESC = ADDNL_MAJOR.MAJ_DESC
					AND STPR_MAJOR_LIST_VIEW.STPR_ADDNL_MAJOR_END_DATE IS NULL
					)
			)

		GROUP BY ID, LAST_NAME, FIRST_NAME, MAJORS.MAJ_DESC, STTR_TERM, GPA.STUDENT_OVERALL_CUM_GPA
	) AS X
GROUP BY TERM, MAJOR
ORDER BY TERM, MAJOR
		
				
