

SELECT STTR_STUDENT,
       CASE WHEN STTR_STUDENT_LOAD IN ('F', 'O') THEN 'Full-Time'
        WHEN STTR_STUDENT_LOAD IN ('L') THEN 'Part-Time' END AS LOAD
FROM ODS_STUDENT_TERMS
WHERE STTR_TERM = '2025FA'
AND STATUS_DESC = 'Registered'


SELECT DISTINCT STC_PERSON_ID,
                STATUS_DESC
FROM SPT_STUDENT_ACAD_CRED AS AC
LEFT JOIN ODS_STUDENT_TERMS AS ST ON AC.STC_PERSON_ID = ST.STTR_STUDENT
WHERE STC_TERM = '2025FA'
AND STC_CRED_TYPE = 'INST'


SELECT *
FROM ODS_STUDENT_TERMS
WHERE STTR_STUDENT = '6184684'