	SELECT STUDENT_TYPE
			,COUNT(*) AS TERM_2025SP
	FROM (
	SELECT STTR_STUDENT
			,STT_DESC AS STUDENT_TYPE
	FROM STUDENT_TERMS_VIEW
	JOIN STUDENT_CURRENT_TYPE_VIEW ON STUDENT_TERMS_VIEW.STTR_STUDENT = STUDENT_CURRENT_TYPE_VIEW.STUDENTS_ID
	JOIN STUDENT_TYPES ON STUDENT_CURRENT_TYPE_VIEW.STUDENT_CURRENT_TYPE = STUDENT_TYPES.STUDENT_TYPES_ID
	WHERE STTR_TERM = '2025SP'
	) AS X
	GROUP BY STUDENT_TYPE