SELECT STUDENT_ID,
		LAST_NAME,
		FIRST_NAME,
		PERSON_EMAIL_ADDRESSES AS EMAIL,
		MAJOR
FROM (
		SELECT CURRENT_MAJORS.MAJ_DESC AS MAJOR,
			   STUDENT_ID
		FROM MAJORS AS CURRENT_MAJORS
		CROSS JOIN (SELECT * FROM STUDENT_ACAD_PROGRAMS_VIEW WHERE STP_CURRENT_STATUS = 'Active') AS SAPV
		LEFT JOIN STPR_MAJOR_LIST_VIEW ON SAPV.STUDENT_ID = STPR_MAJOR_LIST_VIEW.STPR_STUDENT AND SAPV.STP_ACADEMIC_PROGRAM = STPR_MAJOR_LIST_VIEW.STPR_ACAD_PROGRAM
		LEFT JOIN MAJORS AS ADDNL_MAJOR ON STPR_MAJOR_LIST_VIEW.STPR_ADDNL_MAJORS = ADDNL_MAJOR.MAJORS_ID
		LEFT JOIN MAJORS AS MAIN_MAJOR ON SAPV.STP_MAJOR1 = MAIN_MAJOR.MAJORS_ID
		WHERE (
				CURRENT_MAJORS.MAJ_DESC = MAIN_MAJOR.MAJ_DESC
		OR (
			CURRENT_MAJORS.MAJ_DESC = ADDNL_MAJOR.MAJ_DESC
			AND STPR_MAJOR_LIST_VIEW.STPR_ADDNL_MAJOR_END_DATE IS NULL
			)
		)
		AND STP_START_DATE < '2025-05-01'
		GROUP BY CURRENT_MAJORS.MAJ_DESC, STUDENT_ID, STP_START_DATE
	) AS STUDENT_MAJORS
JOIN PERSON ON STUDENT_MAJORS.STUDENT_ID = PERSON.ID
JOIN PEOPLE_EMAIL ON STUDENT_MAJORS.STUDENT_ID = PEOPLE_EMAIL.ID
WHERE PERSON_PREFERRED_EMAIL = 'Y'
ORDER BY MAJOR, LAST_NAME, FIRST_NAME
				
