--(Begin 1)-------------------------------------------------------------------------------------------------------------
                  SELECT Grad_Student,
                         CASE
                             WHEN GENDER = 'M' THEN 'Male'
                             WHEN GENDER = 'F' THEN 'Female'
                             WHEN DF.First_Name IN (
                                                    'Abigail',
                                                   'Alysha',
                                                   'Annemarie',
                                                   'Callie',
                                                   'Cynthia',
                                                   'Elizabeth',
                                                   'Emma',
                                                   'Eva',
                                                   'Hailey',
                                                   'Jasmine',
                                                   'Julie',
                                                   'Macy',
                                                   'Madelin',
                                                   'Shelley'
                                                   ) THEN 'Female'
                                 WHEN DF.First_Name IN (
                                                        'Jacob Colter',
                                                        'Timothy'
                                                        )  THEN 'Male'
                                ELSE 'Unknown' END AS GENDER
FROM (VALUES ('Sophia', 'A', 'McAdam', 'Sophia A McAdam', 'BA', NULL, NULL, NULL, 'Portland, Oregon', '6177677', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Isaac', 'Robert', 'Schilter', 'Isaac Robert Schilter', 'BA', NULL, NULL, NULL, 'Olympia, Washington', '6177146', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Allison', 'Clare', 'Bullman', 'Allison Clare Bullman', 'BA', NULL, NULL, NULL, 'Billings, Montana', '6179703', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Wade', 'S', 'Luly', 'Wade S Luly', 'BA', NULL, NULL, NULL, 'Shelby, Montana', '5885610', 'Biology', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kieran', 'J', 'McGuire', 'Kieran McGuire', 'BA', NULL, NULL, NULL, 'Colorado Springs, Colorado', '6180918', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jack', 'Nichols', 'Snouwaert', 'Jack Nichols Snouwaert', 'BA', NULL, NULL, NULL, 'Palmer Lake, Colorado', '6164295', 'Catholic Studies', 'Communication Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Benjamin', 'Alexander', 'Mehlhaff', 'Benjamin Alexander Mehlhaff', 'BS', NULL, NULL, NULL, 'Eugene, Oregon', '6170318', 'Civil Engineering', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Courtney', 'Elizabeth', 'Boese', 'Courtney Elizabeth Boese', 'BA', 'Summa Cum Laude', NULL, NULL, 'Deer Lodge, Montana', '5972340', 'Elementary Education', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Corinna', 'R', 'Hatfield', 'Corinna R Hatfield', 'BA', NULL, NULL, NULL, 'McCall, Idaho', '6171903', 'Elementary Education', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mildred', 'A', 'Elbert', 'Mildred A Elbert', 'BA', NULL, NULL, NULL, 'Clancy, Montana', '6134290', 'English Literature', 'English Writing', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Coulter', 'G', 'Cloninger', 'Coulter G Cloninger', 'BA', NULL, NULL, NULL, 'Spokane, Washington', '6096603', 'Health Sciences', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Robert', 'J', 'Hague', 'R. Jackson Hague', 'BA', NULL, NULL, NULL, 'Idaho Falls, Idaho', '6175797', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Zachary', 'Andrew', 'Rector', 'Zachary Andrew Rector', 'BA', NULL, NULL, NULL, 'Portland, Oregon', '6165379', 'Health Sciences', 'Public Health', NULL, NULL, 'Men''s Cross Country', 'Outdoor Men''s Track', 'Indoor Men''s Track', NULL, NULL),
('Ryan', 'J', 'Cain', 'Ryan James Cain', 'BA', NULL, NULL, NULL, 'Helena, Montana', '5416882', 'Mathematics', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jack', 'Henry', 'McDonald Garrity', 'Jack McDonald Garrity', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6180007', 'Political Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sheerley', 'Veronikah', 'Ugarte Arostegui', 'Veronikah Ugarte Arostegui', 'BA', NULL, NULL, 'Y', 'Salt Lake City, Utah', '6179092', 'Political Science', 'Philosophy', NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Audrey', 'Marie', 'Benge', 'Audrey Marie Benge', 'BA', NULL, NULL, NULL, 'Wenatchee, Washington', '6180885', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Katie', 'Elizabeth', 'Benevides', 'Katie Elizabeth Benevides', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6176057', 'Self-Designed Major', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Anna', 'R', 'Russell', 'Anna Rose Russell', 'BA', NULL, NULL, NULL, 'Anaconda, Montana', '6175183', 'Sociology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jesica', 'May', 'Masshardt', 'Jesica May Masshardt', 'BA', NULL, NULL, NULL, 'Sheridan, Montana', '6174260', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Landen', 'Rey', 'Conner', 'Landen Rey Conner', 'BA', 'Magna Cum Laude', NULL, NULL, 'Corvallis, Montana', '6173815', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, 'Outdoor Men''s Track', 'ROTC Participants', 'Indoor Men''s Track', NULL, NULL),
('Daxon', 'Arlo', 'Graham', 'Daxon Arlo Graham', 'BA', 'Cum Laude', NULL, NULL, 'Dillon, Montana', '6176405', 'Biology', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Denavion', 'Mohammed', 'Ali', 'Denavion Mohammed Ali', 'BA', NULL, NULL, NULL, 'Denver, Colorado', '6177754', 'Business: Management and Marketing', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Elijah', 'Cole', 'Larson', 'Elijah Cole Larson', 'BA', NULL, NULL, NULL, 'Spokane, Washington', '6177273', 'Business: Management and Marketing', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Benjamin', 'Francisco Jose', 'Paz', 'Benjamin Francisco Jose Paz', 'BA', NULL, NULL, NULL, 'Bellingham, Washington', '6170677', 'Business: Management and Marketing', 'Business: Acctng & Stratg Finc', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Quinn', 'Carter', 'Stamps', 'Quinn Carter Stamps', 'BA', NULL, NULL, NULL, 'Chelan, Washington', '6153597', 'Business: Management and Marketing', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Christopher', 'Ross', 'Akulschin', 'Christopher Ross Akulschin', 'BS', NULL, NULL, NULL, 'Gig Harbor, Washington', '6176608', 'Civil Engineering', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Daniel', NULL, 'Koralewski', 'Daniel Koralewski', 'BS', NULL, NULL, NULL, 'Murfreesboro, Tennessee', '6173844', 'Civil Engineering', NULL, NULL, NULL, 'Outdoor Men''s Track', 'Indoor Men''s Track', 'Men''s Cross Country', NULL, NULL),
('Brooke', 'Mary', 'Vandehey', 'Brooke Mary Vandehey', 'BA', 'Summa Cum Laude', NULL, NULL, 'North Plains, Oregon', '6179868', 'Elementary Education', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Madeline', 'Nancy', 'Vandehey', 'Madeline Nancy Vandehey', 'BA', 'Summa Cum Laude', NULL, NULL, 'North Plains, Oregon', '6179869', 'Elementary Education', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Danait', 'Getahun', 'Kassa', 'Danait Kassa', 'BA', NULL, NULL, NULL, 'Mekelle, Ethiopia', '6181488', 'English Writing', NULL, NULL, NULL, 'Global Refugee Ethiopia', 'International Student', NULL, NULL, NULL),
('Jonathan', 'M D', 'Rose', 'Jonathan M D Rose', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6180801', 'History', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Julian', NULL, 'Arias', 'Julian Arias', 'BA', NULL, NULL, NULL, 'Spokane, Washington', '6174498', 'Health Sciences', NULL, NULL, NULL, 'Indoor Men''s Track', NULL, NULL, NULL, NULL),
('Maxwell', 'Jeffery', 'Lehman', 'Maxwell Jeffery Lehman', 'BA', NULL, NULL, NULL, 'Meridian, Idaho', '6174389', 'Health Sciences', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Carson', 'Charles', 'Ochoa', 'Carson J Charles Ochoa', 'BA', NULL, NULL, NULL, 'Yorba Linda, California', '6170489', 'Health Sciences', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Andrew', 'Douglas', 'Devine', 'Andrew Douglas Devine', 'BA', NULL, NULL, NULL, 'Wasilla, Alaska', '6176927', 'Philosophy', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Ann', 'Marie', 'Mirkin', 'Annie Marie Mirkin', 'BA', NULL, NULL, NULL, 'Seattle, Washington', '6175832', 'Public Health', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Elizabeth', 'Ramey', 'Heuiser', 'Elizabeth Ramey Heuiser', 'BS', 'Cum Laude', NULL, NULL, 'Helena, Montana', '6174904', 'Nursing', 'Public Health', NULL, NULL, 'Women''s Volleyball - JV', 'Women''s Volleyball', NULL, NULL, NULL),
('Grace', 'M', 'Arend', 'Grace Madison Arend', 'BA', 'Summa Cum Laude', NULL, NULL, 'Flagstaff, Arizona', '6178210', 'Sociology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Andrew', 'W', 'Denegar', 'Andrew W Denegar', 'BA', 'Summa Cum Laude', NULL, NULL, 'Great Falls, Montana', '6175150', 'Business: Accounting and Strategic Finance', 'Data Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kaitlyn', 'Heather', 'Fellows', 'Kaitlyn Heather Fellows', 'BA', 'Summa Cum Laude', NULL, NULL, 'Great Falls, Montana', '6175364', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, 'Dance', NULL, NULL, NULL, NULL),
('Avery', 'E', 'Kelly', 'Avery E Kelly', 'BA', 'Cum Laude', NULL, NULL, 'Butte, Montana', '6175421', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, 'Women''s Volleyball', 'Women''s Volleyball - JV', NULL, NULL, NULL),
('James', 'Matthew', 'Lang', 'James Matthew Lang', 'BA', 'Magna Cum Laude', NULL, NULL, 'Portland, Oregon', '6175378', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, 'Men''s Basketball', NULL, NULL, NULL, NULL),
('Camyrn', 'Dawn', 'Larson', 'Camyrn Larson', 'BA', 'Magna Cum Laude', NULL, NULL, 'White Sulphur Springs, Montana', '6176418', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jaden', 'Helene', 'Mueller', 'Jaden Helene Mueller', 'BA', NULL, NULL, NULL, 'Maple Grove, Minnesota', '6168895', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, 'Women''s Volleyball - JV', 'Women''s Volleyball', NULL, NULL, NULL),
('Savannah', 'K', 'Rydalch', 'Savannah K Rydalch', 'BA', 'Summa Cum Laude', NULL, NULL, 'Saint Anthony, Idaho', '6174611', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sydney', NULL, 'Snyder', 'Sydney Snyder', 'BA', NULL, NULL, NULL, 'Minneapolis, Minnesota', '6167542', 'Business: Accounting and Strategic Finance', 'Business: Financial Planning', 'Business: Managmt and Marktng', NULL, NULL, NULL, NULL, NULL, NULL),
('Elizabeth', 'Catherine', 'Ybarra', 'Elizabeth Catherine Ybarra', 'BA', NULL, NULL, NULL, 'Fullerton, California', '6182071', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, 'Women''s Softball', NULL, NULL, NULL, NULL),
('Kaylee', 'Anne', 'Broderick', 'Kaylee Anne Broderick', 'BA', 'Cum Laude', NULL, NULL, 'Palm City, Florida', '6180377', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Aubrey', 'Rose', 'Damm', 'Aubrey Rose Damm', 'BA', 'Cum Laude', NULL, NULL, 'Silver Springs, Nevada', '6180384', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Julianna', NULL, 'Hopper', 'Julianna Hopper', 'BA', 'Magna Cum Laude', NULL, NULL, 'Hillsborough, North Carolina', '6175372', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sarah', 'Eseta', 'Hoyt', 'Sarah E. Hoyt', 'BA', 'Cum Laude', NULL, NULL, 'Port Orchard, Washington', '6178330', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Sydney', 'Jane', 'Lamb', 'Sydney Jane Lamb', 'BA', NULL, NULL, NULL, 'Spokane, Washington', '6181169', 'Anthrozoology', NULL, NULL, NULL, 'Outdoor Women''s Track', 'Indoor Women''s Track', 'Women''s Cross Country', NULL, NULL),
('Mariah', 'A', 'Moran', 'Mariah A Moran', 'BA', 'Magna Cum Laude', NULL, NULL, 'Washougal, Washington', '6175475', 'Anthrozoology', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Natalie', 'Floreine', 'Powell', 'Natalie Floreine Powell', 'BA', 'Cum Laude', NULL, NULL, 'Everett, Washington', '6174826', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('John Paul', NULL, 'Robertson', 'John Paul Robertson', 'BA', NULL, 'Y', 'Y', 'Spokane, Washington', '6173870', 'Anthrozoology', NULL, NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Alyssa', 'L', 'Rubio', 'Alyssa L Rubio', 'BA', 'Magna Cum Laude', NULL, NULL, 'Happy Valley, Oregon', '6175858', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Morgan', 'E', 'Tekorius', 'Morgan E Tekorius', 'BA', NULL, NULL, NULL, 'Oregon City, Oregon', '6174788', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kylee', 'Brooke', 'Wilcox', 'Kylee Brooke Wilcox', 'BA', NULL, NULL, NULL, 'Simsbury, Connecticut', '6174278', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Margaret', 'Elizabeth', 'Young', 'Margaret Elizabeth Young', 'BA', NULL, NULL, NULL, 'Las Vegas, Nevada', '6176191', 'Anthrozoology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Katherine', 'M', 'Bold', 'Katherine Mary Bold', 'BA', 'Magna Cum Laude', 'Y', NULL, 'Big Sandy, Montana', '6175773', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mila', 'Isabelle', 'Duncan', 'Mila Isabelle Duncan', 'BA', NULL, NULL, NULL, 'Seattle, Washington', '6175787', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Macie', 'C', 'Frans', 'Macie C Frans', 'BA', 'Cum Laude', NULL, NULL, 'Boise, Idaho', '6174717', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Rachel', 'Rosemary', 'Kaiser', 'Rachel Rosemary Kaiser', 'BA', 'Summa Cum Laude', NULL, NULL, 'Bozeman, Montana', '6174481', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Carson', 'T', 'Lewis', 'Carson Lewis', 'BA', 'Summa Cum Laude', NULL, NULL, 'Lewistown, Montana', '6176617', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Adisyn', 'Grace Margarette', 'O''Connor', 'Adisyn Grace Margarette O''Connor', 'BA', 'Summa Cum Laude', NULL, NULL, 'Billings, Montana', '6175175', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Vicente', 'Mora', 'Ortega', 'Vicente Mora Ortega', 'BA', NULL, 'Y', NULL, 'Ronan, Montana', '6175843', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, 'Forensics Team', NULL, NULL, NULL, NULL),
('Zackery', 'James', 'Prokopyschyn', 'Zackery James Prokopyschyn', 'BA', NULL, NULL, NULL, 'Arvada, Colorado', '6173867', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mederise', 'Michelle', 'Tooke', 'Mederise Michelle Tooke', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6173999', 'Biochemistry/Molecular Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Corinne', 'Simone', 'Anderko', 'Corinne Simone Anderko', 'BA', NULL, NULL, NULL, 'Danielsville, Pennsylvania', '6183031', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Emma', 'Jinshi', 'Boharski', 'Emma Jin Shi Boharski', 'BA', 'Cum Laude', NULL, NULL, 'Deer Park, Washington', '6175771', 'Biology', NULL, NULL, NULL, 'Dance', NULL, NULL, NULL, NULL),
('Clara', 'Marie', 'Carpenter', 'Clara Marie Carpenter', 'BA', NULL, NULL, NULL, 'Coeur d''Alene, Idaho', '6177856', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Marrin', 'F', 'Chapman', 'Marrin Frances Bertoglio Chapman', 'BA', 'Summa Cum Laude', NULL, NULL, 'Montana City, Montana', '6174711', 'Biology', 'Catholic Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Laura', 'K', 'DeBowes', 'Laura Katherine DeBowes', 'BA', 'Cum Laude', NULL, NULL, 'Spokane, Washington', '6176329', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Michael', 'R', 'Deguzman', 'Michael R Deguzman', 'BA', NULL, NULL, NULL, 'Lewistown, Montana', '6177003', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Josie', 'C', 'Gale', 'Josie Carolyn Gale', 'BA', NULL, NULL, 'Y', 'Minneapolis, Minnesota', '6176710', 'Biology', NULL, NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Terra', 'M', 'Hurt', 'Terra Hurt', 'BA', 'Magna Cum Laude', NULL, NULL, 'Colorado Springs, Colorado', '6180923', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Chloe', 'P', 'Jones', 'Chloe P Jones', 'BA', 'Summa Cum Laude', NULL, NULL, 'Newport, Washington', '6174562', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Edouard', 'Gregory', 'Karleskind', 'Edouard Gregory Karleskind', 'BA', NULL, NULL, NULL, 'Alamo, California', '6170309', 'Biology', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Maximilien', 'Marie', 'Karleskind', 'Maximilien Marie Karleskind', 'BA', NULL, NULL, NULL, 'Alamo, California', '6171088', 'Biology', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Serena', 'Nicole', 'Keil-Hoye', 'Serena Keil-Hoye', 'BA', NULL, NULL, NULL, 'Kalispell, Montana', '6175374', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('June', 'Margaret', 'Lepage', 'June Margaret LePage', 'BA', 'Magna Cum Laude', NULL, 'Y', 'Lewistown, Montana', '6174101', 'Biology', 'Hispanic Studies and Languages', NULL, NULL, 'Forensics Team', 'Honors Scholars', NULL, NULL, NULL),
('Trey', 'James', 'Melton', 'Trey James Melton', 'BA', 'Summa Cum Laude', NULL, 'Y', 'Helena, Montana', '6177869', 'Biology', NULL, NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Michal', 'Melichar', 'Mojzis', 'Michal Melichar Mojzis', 'BA', NULL, 'Y', NULL, 'Bratislava, Slovakia', '6184427', 'Biology', NULL, NULL, NULL, 'International Student', 'Men''s Soccer', NULL, NULL, NULL),
('Megan', 'Lucienne', 'Olsen', 'Megan Lucienne Olsen', 'BA', 'Magna Cum Laude', NULL, 'Y', 'Bozeman, Montana', '6175842', 'Biology', 'Hispanic Studies and Languages', NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Hunter', 'Bruce', 'Peck', 'Hunter Bruce Peck', 'BA', 'Cum Laude', NULL, NULL, 'Windsor, Colorado', '6173270', 'Biology', NULL, NULL, NULL, 'Military Veterans', 'Football', NULL, NULL, NULL),
('Nathan', 'A', 'Stalder', 'Nathan Anton Stalder', 'BA', 'Cum Laude', NULL, NULL, 'Issaquah, Washington', '6176124', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kenna', 'L', 'Thomas', 'Kenna L Thomas', 'BA', 'Summa Cum Laude', NULL, NULL, 'Belgrade, Montana', '6176683', 'Biology', NULL, NULL, NULL, 'Women''s Softball', NULL, NULL, NULL, NULL),
('Quinn', 'W', 'Belcher', 'Quinn W Belcher', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6176504', 'Business: Management and Marketing', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Kyle', 'David', 'Bender', 'Kyle David Bender', 'BA', NULL, NULL, NULL, 'Saginaw, Michigan', '6181143', 'Business: Management and Marketing', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Abigail', 'Marie', 'Brown', 'Abigail Marie Brown', 'BA', NULL, NULL, NULL, 'Olympia, Washington', '6181635', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jamie', 'Rae', 'Burbank', 'Jamie Burbank', 'BA', 'Cum Laude', NULL, NULL, 'Helena, Montana', '6174112', 'Business: Management and Marketing', 'Communication Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Logan', 'David', 'Hill', 'Logan David Hill', 'BA', 'Cum Laude', NULL, NULL, 'Billings, Montana', '6180981', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kyndall', 'S', 'Keller', 'Kyndall S Keller', 'BA', 'Magna Cum Laude', NULL, NULL, 'Havre, Montana', '6168685', 'Business: Management and Marketing', NULL, NULL, NULL, 'Women''s Basketball', NULL, NULL, NULL, NULL),
('Derek', 'Albert', 'Kramer', 'Derek Albert Kramer', 'BA', NULL, NULL, NULL, 'Bellevue, Washington', '6181168', 'Business: Management and Marketing', NULL, NULL, NULL, 'Men''s Basketball', NULL, NULL, NULL, NULL),
('Anna', 'Claire', 'Kretzschmar', 'Anna Claire Kretzschmar', 'BA', NULL, NULL, NULL, 'Anchorage, Alaska', '6173845', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Henry', 'Bruce', 'Lauerman', 'Henry Bruce Lauerman', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6174257', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Britlyn', 'Haze', 'Mailey', 'Britlyn Haze Mailey', 'BA', NULL, NULL, NULL, 'Bozeman, Montana', '6177279', 'Business: Management and Marketing', NULL, NULL, NULL, 'Outdoor Women''s Track', 'Indoor Women''s Track', 'Women''s Volleyball - JV', NULL, NULL),
('Emilie', 'G', 'Munguia', 'Emilie Grace Munguia', 'BA', 'Magna Cum Laude', NULL, NULL, 'Yakima, Washington', '6176118', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kolbe', 'John', 'Olmes', 'Kolbe John Olmes', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6176427', 'Business: Management and Marketing', NULL, NULL, NULL, 'Cheerleading', NULL, NULL, NULL, NULL),
('Ryan', 'J', 'Rickman', 'Ryan Rickman', 'BA', NULL, NULL, NULL, 'Sublimity, Oregon', '6169592', 'Business: Management and Marketing', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Griffin', NULL, 'Teuber', 'Griffin Teuber', 'BA', NULL, NULL, NULL, 'Boise, Idaho', '6184323', 'Business: Management and Marketing', NULL, NULL, NULL, 'Men''s Soccer', NULL, NULL, NULL, NULL),
('Tysen', 'Eugene', 'Thatcher', 'Tysen Eugene Thatcher', 'BA', 'Cum Laude', NULL, NULL, 'Helena, Montana', '6154595', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Isadora', 'G', 'Tomazeli', 'Isadora Tomazeli', 'BA', NULL, NULL, NULL, 'Sao Paulo, Brazil', '6166831', 'Business: Management and Marketing', NULL, NULL, NULL, 'Women''s Golf', 'International Student', NULL, NULL, NULL),
('Chayton', 'James', 'Winkle', 'Chayton James Winkle', 'BA', 'Magna Cum Laude', NULL, NULL, 'Helena, Montana', '6176356', 'Business: Management and Marketing', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Sofia', 'Marie', 'Frongillo', 'Sofia Marie Frongillo', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6173688', 'Catholic Studies', 'Theology', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Luke', 'Stephen', 'Ostberg', 'Luke Stephen Ostberg', 'BA', 'Summa Cum Laude', 'Y', 'Y', 'Fairfield, Montana', '6174261', 'Catholic Studies', 'Philosophy', NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Christopher', 'Andrew', 'Szpilka', 'Christopher Andrew Szpilka', 'BA', 'Summa Cum Laude', NULL, NULL, 'Helena, Montana', '5521385', 'Catholic Studies', 'Physics', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jared', 'C', 'Ball', 'Jared Ball', 'BS', 'Cum Laude', NULL, NULL, 'Yakima, Washington', '6176921', 'Civil Engineering', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Tristan', 'Reid', 'Gallagher', 'Tristan Reid Gallagher', 'BS', 'Cum Laude', NULL, 'Y', 'Austin, Texas', '6175507', 'Civil Engineering', NULL, NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Bryan', 'P', 'Holland', 'Bryan Patrick Holland', 'BS', 'Magna Cum Laude', NULL, NULL, 'Butte, Montana', '6176207', 'Civil Engineering', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Thomas', 'Jay', 'Klepps', 'Thomas Jay Klepps', 'BS', 'Magna Cum Laude', NULL, NULL, 'Billings, Montana', '6175516', 'Civil Engineering', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cameron', 'Scott', 'Pruitt', 'Cameron Scott Pruitt', 'BS', NULL, NULL, NULL, 'Boise, Idaho', '6169487', 'Civil Engineering', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Joshua', NULL, 'Smalley', 'Joshua Smalley', 'BS', 'Summa Cum Laude', NULL, NULL, 'Missoula, Montana', '6177824', 'Civil Engineering', NULL, NULL, NULL, 'Outdoor Men''s Track', 'Indoor Men''s Track', NULL, NULL, NULL),
('Laura', 'Ann', 'Fontaine', 'Laura Ann Fontaine', 'BA', 'Cum Laude', NULL, NULL, 'Darien Center, New York', '6176613', 'Chemistry', 'Hispanic Studies and Languages', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Charles', 'Benson', 'Markham', 'Charles Benson Markham', 'BA', 'Cum Laude', NULL, NULL, 'Spokane, Washington', '6174102', 'Chemistry', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Katie', 'Marie', 'Bell', 'Katie Marie Bell', 'BA', NULL, NULL, NULL, 'Bellingham, Washington', '6177305', 'Communication Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kacy', 'Stevens', 'Clements', 'Kacy Stevens Clements', 'BA', 'Cum Laude', NULL, NULL, 'Nederland, Colorado', '6175000', 'Communication Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jonathen', 'T', 'Reiser', 'Jonathen T Reiser', 'BA', 'Cum Laude', NULL, NULL, 'Dillon, Montana', '6176666', 'Communication Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kaitlyn', 'Mae', 'Wenzel', 'Kaitlyn Ruch Wenzel', 'BA', 'Magna Cum Laude', NULL, NULL, 'Helena, Montana', '6178523', 'Communication Studies', 'Catholic Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('John', 'J', 'Botonakis', 'John J Botonakis', 'BA', NULL, NULL, NULL, 'Chicago, Illinois', '6178357', 'Computer Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Abigail', 'Maureen', 'Brown', 'Abigail Maureen Brown', 'BA', 'Summa Cum Laude', 'Y', NULL, 'Kennewick, Washington', '6173809', 'Computer Science', 'Data Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Justin', 'M', 'Forseth', 'Justin Forseth', 'BA', 'Summa Cum Laude', NULL, NULL, 'Fairfield, Montana', '6174901', 'Computer Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jack', 'Alexander', 'Holy', 'Jack Alexander Holy', 'BA', 'Magna Cum Laude', NULL, NULL, 'Calgary, Alberta', '6176493', 'Computer Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Adrian', 'Alexander', 'Rincon-Jimenez', 'Adrian Alexander Rincon Jimenez', 'BA', NULL, NULL, NULL, 'Helena, Montana', '5521374', 'Computer Science', 'Data Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Aidan', 'Clinton', 'Scott', 'Aidan Clinton Scott', 'BA', 'Magna Cum Laude', NULL, NULL, 'Townsend, Montana', '5944244', 'Computer Information Systems', 'Business: Financial Planning', 'Computer Science', NULL, NULL, NULL, NULL, NULL, NULL),
('Murat', 'Can', 'Guzelocak', 'Murat Can Guzelocak', 'BA', NULL, NULL, NULL, 'Istanbul, Turkey', '6171063', 'Data Science', NULL, NULL, NULL, 'International Student', 'Men''s Basketball', NULL, NULL, NULL),
('Cole', 'C', 'Odegard', 'Cole C Odegard', 'BA', 'Summa Cum Laude', 'Y', NULL, 'Beaverton, Oregon', '6174594', 'Data Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Charles', NULL, 'Said', 'Charles Said', 'BA', 'Magna Cum Laude', 'Y', NULL, 'Woodinville, Washington', '6180802', 'Data Science', 'Political Science', NULL, NULL, 'Forensics Team', NULL, NULL, NULL, NULL),
('Amber', 'Lynn', 'Countryman', 'Amber Lynn Countryman', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6178125', 'Elementary Education', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Jonathan', 'Martin', 'Goodman', 'Jonathan Martin Goodman', 'BA', NULL, NULL, NULL, 'Newport, Washington', '6167100', 'Elementary Education', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Jack', 'W', 'Prka', 'Jack William Prka', 'BA', NULL, NULL, NULL, 'Coeur d''Alene, Idaho', '6174941', 'Elementary Education', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Angelique', 'C', 'Rubio-Casanova', 'Angelique C Rubio-Casanova', 'BA', 'Magna Cum Laude', NULL, NULL, 'Kent, Washington', '6180562', 'Elementary Education', NULL, NULL, NULL, 'Cheerleading', NULL, NULL, NULL, NULL),
('Mekenzie', 'Grace', 'Arnold', 'Mekenzie Grace Arnold', 'BA', NULL, NULL, NULL, 'La Habra, California', '6174232', 'Elementary Educ & Special Educ', NULL, NULL, NULL, 'Cheerleading', NULL, NULL, NULL, NULL),
('Erika', 'J', 'Arthur', 'Erika J Arthur', 'BA', 'Cum Laude', NULL, NULL, 'Soldotna, Alaska', '6176062', 'Elementary Education K-8 & Special Education K-12', NULL, NULL, NULL, 'Indoor Women''s Track', 'Outdoor Women''s Track', NULL, NULL, NULL),
('Madeline', 'Faith', 'Visser', 'Madeline Faith Visser', 'BA', 'Summa Cum Laude', NULL, NULL, 'Manhattan, Montana', '6175393', 'Elementary Education K-8 & Special Education K-12', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Anna', 'E', 'Brown', 'Anna Elizabeth Brown', 'BA', 'Summa Cum Laude', NULL, 'Y', 'Olympia, Washington', '6174709', 'English Literature', 'Political Science', NULL, NULL, 'Forensics Team', 'Honors Scholars', NULL, NULL, NULL),
('Mailee', 'Tran', 'Bui', 'Mailee Tran Bui', 'BA', 'Magna Cum Laude', NULL, NULL, 'Kennewick, Washington', '6174081', 'English Education (5-12)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Madeline', 'G', 'De Leo', 'Madeline Grace De Leo', 'BA', 'Magna Cum Laude', NULL, NULL, 'Corvallis, Montana', '6162541', 'English Writing', 'English Literature', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Nathaniel', 'Kai', 'Gong', 'Nathaniel Gong', 'BA', 'Summa Cum Laude', NULL, NULL, 'Hillsboro, Oregon', '6173828', 'Environmental Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Norbert', 'Joseph', 'Karczewski', 'Norbert Joseph Karczewski IV', 'BA', 'Magna Cum Laude', NULL, NULL, 'Pensacola, Florida', '6180890', 'Environmental Science', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Garrett', 'A', 'Oleson', 'Garrett A Oleson', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6164497', 'Environmental Science', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Caleb', 'J', 'Smith', 'Caleb J Smith', 'BA', NULL, NULL, NULL, 'Columbia Falls, Montana', '6175187', 'Environmental Science', 'Biology', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Margaret', 'Louise', 'Todd', 'Margaret Louise Todd', 'BA', 'Magna Cum Laude', NULL, NULL, 'Polson, Montana', '6176369', 'Environmental Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Willem', 'Michael', 'Trainor', 'Willem Michael Trainor', 'BA', NULL, NULL, NULL, 'Cleveland, Ohio', '6186990', 'Environmental Science', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ellee', 'Grace', 'Page', 'Ellee Grace Page', 'BA', NULL, NULL, NULL, 'Lamar, Colorado', '6178245', 'Business: Financial Planning', NULL, NULL, NULL, 'Cheerleading', NULL, NULL, NULL, NULL),
('Keel', 'John', 'Potter', 'Keel John Potter', 'BA', 'Magna Cum Laude', NULL, NULL, 'Coeur d''Alene, Idaho', '6174825', 'Business: Financial Planning', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Thomas', 'Henry', 'Carty', 'Thomas Henry Carty', 'BA', 'Magna Cum Laude', NULL, NULL, 'Sandpoint, Idaho', '6173811', 'History', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('James', 'Michael', 'Peruzzi', 'James Michael Peruzzi', 'BA', NULL, NULL, NULL, 'North Weymouth, Massachusetts', '6175846', 'History', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Taylor', 'Lela Tyson', 'Plant', 'Taylor Lela Tyson Plant', 'BA', NULL, NULL, NULL, 'Helena, Montana', '5856480', 'History', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mikenna', 'K', 'Deschamps', 'Mikenna K Deschamps', 'BA', NULL, NULL, NULL, 'Missoula, Montana', '6173677', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Addison', 'Grace', 'Ekstrom', 'Addison Ekstrom', 'BA', 'Summa Cum Laude', NULL, NULL, 'Bozeman, Montana', '6175363', 'Health Sciences', 'Public Health', NULL, NULL, 'Women''s Basketball', NULL, NULL, NULL, NULL),
('Jack', 'Robert', 'England', 'Jack Robert England', 'BA', 'Cum Laude', NULL, NULL, 'Meridian, Idaho', '6175789', 'Health Sciences', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Kailen', 'L', 'Herbstritt', 'Kailen L Herbstritt', 'BA', 'Magna Cum Laude', NULL, NULL, 'Corvallis, Montana', '6175416', 'Health Sciences', NULL, NULL, NULL, 'Outdoor Women''s Track', 'Indoor Women''s Track', NULL, NULL, NULL),
('Alyssa', 'Jocelyn', 'Lybbert', 'Alyssa Jocelyn Lybbert', 'BA', 'Cum Laude', NULL, NULL, 'Las Vegas, Nevada', '6174259', 'Health Sciences', NULL, NULL, NULL, 'Women''s Softball', NULL, NULL, NULL, NULL),
('Leah', 'Therese', 'Manning', 'Leah Therese Manning', 'BA', 'Cum Laude', NULL, NULL, 'Mission Viejo, California', '6176420', 'Health Sciences', NULL, NULL, NULL, 'Women''s Basketball - JV', NULL, NULL, NULL, NULL),
('Mitchell', 'Ross', 'Muralt', 'Mitchell Ross Muralt', 'BA', NULL, NULL, NULL, 'Missoula, Montana', '6176083', 'Health Sciences', NULL, NULL, NULL, 'Football', NULL, NULL, NULL, NULL),
('Riley', 'J', 'Navarro', 'Riley J Navarro', 'BA', NULL, NULL, NULL, 'Carson City, Nevada', '6174589', 'Health Sciences', NULL, NULL, NULL, 'Men''s Basketball - JV', 'Men''s Basketball', NULL, NULL, NULL),
('Mason', 'P', 'Pereira', 'Mason Paul Pereira', 'BA', NULL, NULL, NULL, 'Altadena, California', '6174787', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Maddy', NULL, 'Quigley', 'Madison Quigley', 'BA', 'Magna Cum Laude', NULL, NULL, 'Coeur d''Alene, Idaho', '6179539', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Aysia', 'M', 'Rogne', 'Aysia M Rogne', 'BA', NULL, NULL, NULL, 'Helena, Montana', '5521173', 'Health Sciences', 'Public Health', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Gabrielle', NULL, 'Sheridan', 'Gabrielle Anne Sheridan', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6177442', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Isabella', 'S', 'Sweet', 'Isabella Sophia Sweet', 'BA', 'Cum Laude', NULL, NULL, 'West Palm Beach, Florida', '6175450', 'Health Sciences', NULL, NULL, NULL, 'Women''s Volleyball', 'Women''s Volleyball - JV', NULL, NULL, NULL),
('Kelly', 'Ann', 'White', 'Kelly Ann White', 'BA', NULL, NULL, NULL, 'Butte, Montana', '6174277', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Zachary', 'Scott', 'Wickens', 'Zachary Scott Wickens', 'BA', NULL, NULL, NULL, 'Townsend, Montana', '6132398', 'Health Sciences', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Josephine', 'Elise', 'Stevenson', 'Josephine Elise Stevenson', 'BA', 'Cum Laude', NULL, 'Y', 'Redmond, Oregon', '6180836', 'International Relations', 'Political Science', NULL, NULL, 'Honors Scholars', NULL, NULL, NULL, NULL),
('Jackson', 'M', 'Cossairt', 'Jackson M Cossairt', 'BA', 'Cum Laude', 'Y', NULL, 'Westmont, Illinois', '6174516', 'Mathematics Education (5-12)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Trinity', 'E', 'Edwards', 'Trinity Elise Edwards', 'BA', 'Summa Cum Laude', 'Y', NULL, 'Winifred, Montana', '6177584', 'Mathematics Education (5-12)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Reagan', 'Bourquin', 'Ryan', 'Reagan Bourquin Ryan', 'BA', 'Summa Cum Laude', 'Y', NULL, 'Great Falls, Montana', '6173872', 'Mathematics Education (5-12)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Clare', 'A', 'Daley', 'Clare A Daley', 'BA', 'Magna Cum Laude', 'Y', NULL, 'West Yellowstone, Montana', '6176445', 'Mathematics', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Abraham', 'J', 'Montalvo', 'Abraham J Montalvo', 'BA', 'Summa Cum Laude', 'Y', NULL, 'Terry, Montana', '6176214', 'Mathematics', 'Data Science', NULL, NULL, 'Outdoor Men''s Track', 'Indoor Men''s Track', 'Military Veterans', NULL, NULL),
('Aubrey', 'L', 'Baker', 'Aubrey L Baker', 'BS', NULL, NULL, NULL, 'Mission Viejo, California', '6174501', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Miranda', 'Roi', 'Bruhn', 'Miranda Roi Bruhn', 'BS', NULL, NULL, NULL, 'Santa Ynez, California', '6180886', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Addie', 'G', 'Butler', 'Addie  Butler', 'BS', 'Cum Laude', NULL, NULL, 'Freedom, Wyoming', '6176063', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Alexa', 'Rose', 'Dreyer', 'Alexa Rose Dreyer', 'BS', NULL, NULL, NULL, 'Bozeman, Montana', '6175360', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Delaney', 'Derzay', 'Hasquet', 'Delaney Derzay Hasquet', 'BS', 'Magna Cum Laude', NULL, NULL, 'Butte, Montana', '6173834', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Stephanie', 'A', 'Hodges', 'Stephanie A Hodges', 'BS', 'Cum Laude', NULL, NULL, 'Sammamish, Washington', '6080634', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Tessa', 'A', 'Hoover', 'Tessa A Hoover', 'BS', 'Magna Cum Laude', NULL, NULL, 'Bothell, Washington', '6173838', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Alexzandria', 'Nicole', 'Hutchison', 'Alexzandria Nicole Hutchison', 'BS', 'Cum Laude', NULL, NULL, 'Paul, Idaho', '6176337', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jensen', 'Elise', 'Keller', 'Jensen Elise Keller', 'BS', NULL, NULL, NULL, 'Billings, Montana', '6165895', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Elizabeth', 'G', 'Koerber', 'Elizabeth G Koerber', 'BS', 'Cum Laude', NULL, NULL, 'Billings, Montana', '6175162', 'Nursing', NULL, NULL, NULL, 'Women''s Softball', NULL, NULL, NULL, NULL),
('Katarina', 'Rene Gerard', 'Kosiewicz', 'Katarina Rene Gerard Kosiewicz', 'BS', NULL, NULL, NULL, 'Keizer, Oregon', '6029556', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Laura', 'Grace', 'Ley', 'Laura Grace Ley', 'BS', 'Cum Laude', NULL, NULL, 'Huntley, Montana', '6173847', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Haley', 'G', 'Luchini', 'Haley G Luchini', 'BS', NULL, NULL, NULL, 'Bend, Oregon', '6181472', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Catherine', 'E', 'Mack', 'Catherine Elizabeth Mack', 'BS', NULL, NULL, NULL, 'Coeur d''Alene, Idaho', '6170375', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jacquelene', 'Gomes', 'Malheiros', 'Jacquelene Gomes Malheiros', 'BS', NULL, NULL, NULL, 'Helena, Montana', '6163738', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Mary', 'Marlisa', 'Meijerink', 'Mary Marlisa Meijerink', 'BS', NULL, NULL, NULL, 'La Habra, California', '6175466', 'Nursing', NULL, NULL, NULL, 'Women''s Volleyball - JV', NULL, NULL, NULL, NULL),
('Payton', 'Jean', 'Mitchum', 'Payton Jean Mitchum', 'BS', 'Magna Cum Laude', NULL, NULL, 'Columbus, Montana', '6177339', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Weston', 'R', 'Mitchum', 'Weston R Mitchum', 'BS', 'Magna Cum Laude', NULL, NULL, 'Columbus, Montana', '6174582', 'Nursing', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Audrey', 'Grace', 'Narum', 'Audrey Grace Narum', 'BS', 'Cum Laude', NULL, NULL, 'Damascus, Oregon', '6174106', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Miya', 'L', 'Nettleton', 'Miya L Nettleton', 'BS', NULL, NULL, NULL, 'Helena, Montana', '5949366', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Elaina', 'C', 'Patten', 'Elaina C Patten', 'BS', 'Cum Laude', NULL, NULL, 'Helena, Montana', '6170007', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jasmine', 'Angelina', 'Pearson', 'Jasmine Angelina Pearson', 'BS', 'Cum Laude', NULL, NULL, 'Thompson Falls, Montana', '6174109', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jamie', 'N', 'Pickens', 'Jamie N Pickens', 'BS', 'Cum Laude', NULL, NULL, 'Helena, Montana', '6096897', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Rebecca', 'Mary', 'Rich', 'Rebecca Mary Rich', 'BS', 'Cum Laude', NULL, NULL, 'Agoura Hills, California', '6180624', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Andrea', 'Kate', 'Robinson', 'Andrea Kate Robinson', 'BS', 'Cum Laude', NULL, NULL, 'Yelm, Washington', '6175855', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Keetyn', 'Nicole', 'Sayers', 'Keetyn Nicole Sayers', 'BS', 'Cum Laude', NULL, NULL, 'Helena, Montana', '6174114', 'Nursing', NULL, NULL, NULL, 'Women''s Basketball', 'Women''s Basketball - JV', NULL, NULL, NULL),
('Jaymee', 'Anne', 'Sheridan', 'Jaymee Anne Sheridan', 'BS', NULL, NULL, NULL, 'Helena, Montana', '6174920', 'Nursing', NULL, NULL, NULL, 'Women''s Soccer', NULL, NULL, NULL, NULL),
('Stephanie', 'G', 'Smith', 'Stephanie G Smith', 'BS', NULL, NULL, NULL, 'Oakland, California', '6174623', 'Nursing', NULL, NULL, NULL, 'Women''s Soccer', NULL, NULL, NULL, NULL),
('Natalie', 'Jo', 'Soll', 'Natalie Jo Soll', 'BS', 'Magna Cum Laude', NULL, NULL, 'Pendleton, Oregon', '6174395', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Emma', 'G', 'Stachofsky', 'Emma Grace Stachofsky', 'BS', 'Cum Laude', NULL, NULL, 'Spokane, Washington', '6174625', 'Nursing', NULL, NULL, NULL, 'Indoor Women''s Track', 'Outdoor Women''s Track', NULL, NULL, NULL),
('Dylan', 'F', 'Stearns', 'Dylan F Stearns', 'BS', 'Magna Cum Laude', NULL, NULL, 'Spokane, Washington', '6079363', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Noel', 'Kateri', 'Teders', 'Noel Kateri Teders', 'BS', NULL, NULL, NULL, 'Helena, Montana', '6173998', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Avery', 'Paige', 'Tripp', 'Avery Paige Tripp', 'BS', 'Magna Cum Laude', NULL, NULL, 'Spokane, Washington', '6173885', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Emilie', 'E', 'Turpen', 'Emilie E Turpen', 'BS', 'Magna Cum Laude', NULL, NULL, 'Sisters, Oregon', '6174750', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Caitlyn', 'Marie', 'Vermulm', 'Caitlyn Marie Vermulm', 'BS', 'Summa Cum Laude', NULL, NULL, 'Cut Bank, Montana', '6173888', 'Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jesse', NULL, 'Windle', 'Jesse Windle', 'BS', 'Cum Laude', NULL, NULL, 'Trout Creek, Montana', '6176944', 'Nursing', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Hanna', 'W', 'Ziegenhagen', 'Hanna W Ziegenhagen', 'BS', NULL, NULL, NULL, 'The Dalles, Oregon', '6174754', 'Nursing', NULL, NULL, NULL, 'Outdoor Women''s Track', 'Indoor Women''s Track', 'Women''s Cross Country', NULL, NULL),
('Brooke', 'Ellen', 'McClenning', 'Brooke McClenning', 'BA', NULL, NULL, NULL, 'Huntley, Montana', '6173851', 'Theatre', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kara', 'Ann Therese', 'Donahue', 'Kara Ann Therese Donahue', 'BA', NULL, NULL, NULL, 'Kalispell, Montana', '6179994', 'Philosophy', 'Catholic Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ryan', 'L', 'Frampton', 'Ryan L Frampton', 'BA', 'Magna Cum Laude', NULL, NULL, 'Whitefish, Montana', '6174538', 'Philosophy', 'Catholic Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Maclain', 'John', 'Holland', 'Maclain John Holland', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6184022', 'Political Science', 'International Relations', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Spencer', 'Madison-Judith', 'McDonald', 'Spencer McDonald', 'BA', NULL, NULL, NULL, 'Missoula, Montana', '6173852', 'Political Science', NULL, NULL, NULL, 'Forensics Team', NULL, NULL, NULL, NULL),
('Maci', 'Kei', 'Sakaguchi', 'Maci Kei Sakaguchi', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6174113', 'Political Science', 'International Relations', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Riley', 'J', 'Stansberry', 'Riley J Stansberry', 'BA', NULL, NULL, NULL, 'Spokane, Washington', '6174744', 'Political Science', NULL, NULL, NULL, 'Men''s Golf', NULL, NULL, NULL, NULL),
('Sofia', 'Michaela', 'Wright', 'Sofia Michaela Wright', 'BA', NULL, NULL, NULL, 'Renton, Washington', '6177330', 'Political Science', 'International Relations', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Emma', 'Catherine', 'Chaffin', 'Emma Catherine Chaffin', 'BA', NULL, NULL, NULL, 'Duvall, Washington', '6175355', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Isabella', 'Merittia', 'Chalmers', 'Isabella Merittia Chalmers', 'BA', NULL, NULL, NULL, 'Happy Valley, Oregon', '6173813', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Brittney', 'Lynn', 'Chapman', 'Brittney Lynn Chapman', 'BA', 'Magna Cum Laude', NULL, NULL, 'Tumwater, Washington', '6174512', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Samuel', 'Christopher', 'Conner', 'Samuel Christopher Conner', 'BA', 'Cum Laude', NULL, NULL, 'Salt Lake City, Utah', '6175782', 'Psychology', NULL, NULL, NULL, 'Men''s Golf', NULL, NULL, NULL, NULL),
('Alexa', 'Marie', 'Hanser', 'Alexa Marie Hanser', 'BA', NULL, NULL, NULL, 'Billings, Montana', '6174093', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Patrick', 'Harrison', 'Keeley', 'Patrick Keeley', 'BA', 'Magna Cum Laude', NULL, NULL, 'Littleton, Colorado', '6175464', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Tucker', 'William', 'Monaco', 'Tucker William Monaco', 'BA', NULL, NULL, NULL, 'Bakersfield, California', '6182177', 'Psychology', NULL, NULL, NULL, 'Outdoor Men''s Track', 'Indoor Men''s Track', NULL, NULL, NULL),
('Jared', 'James Henry', 'Nelson', 'Jared James Henry Nelson', 'BA', 'Summa Cum Laude', NULL, NULL, 'Helena, Montana', '6173859', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Brodie', 'D', 'Sayre', 'Brodie D Sayre', 'BA', 'Cum Laude', NULL, NULL, 'Battle Mountain, Nevada', '6176460', 'Psychology', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Morgan', NULL, 'Sunchild', 'Morgan Sunchild', 'BA', NULL, NULL, NULL, 'Great Falls, Montana', '6186772', 'Psychology', NULL, NULL, NULL, 'Women''s Softball', NULL, NULL, NULL, NULL),
('William', NULL, 'Dominguez', 'William Dominguez', 'BA', NULL, NULL, NULL, 'Mattawa, Washington', '6184599', 'Self-Designed Major', NULL, NULL, NULL, 'Men''s Soccer', NULL, NULL, NULL, NULL),
('Abigail', 'Frances', 'Robo', 'Abigail Frances Robo', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6174264', 'Self-Designed Major', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Veronika', NULL, 'Fomishyna', 'Veronika Potts', 'BA', 'Magna Cum Laude', NULL, NULL, 'Ukraine', '6183814', 'Sociology', NULL, NULL, NULL, 'Global Refugee Ukraine', NULL, NULL, NULL, NULL),
('Isaac', 'C', 'Goudy', 'Isaac C Goudy', 'BA', 'Cum Laude', NULL, NULL, 'Billings, Montana', '6176112', 'Sociology', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Madelin', NULL, 'Barbee', 'Madelin Barbee', 'MSW', NULL, NULL, NULL, 'Helena, Montana', '6188797', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Alysha', NULL, 'Bruss', 'Alysha Nicole Bruss', 'MSW', NULL, NULL, NULL, 'San Bernardino, California', '6184977', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Skyler', 'Bradley', 'Carroll', 'Skyler Bradley Carroll', 'MSW', NULL, NULL, NULL, 'Livingston, Montana', '6184661', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Caitlin', NULL, 'Cooper', 'Caitlin Cooper', 'MSW', NULL, NULL, NULL, 'Dillon, Montana', '6181160', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Alexandria', NULL, 'Corbett', 'Alexandra Corbett', 'MSW', NULL, NULL, NULL, 'Helena, Montana', '5237081', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Michael', NULL, 'Elliott', 'Michael Elliott', 'MSW', NULL, NULL, NULL, 'Helena, Montana', '5227432', 'Master of Social Work', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Angela', 'C', 'Evans', 'Angela C Evans', 'MSW', NULL, NULL, NULL, 'Ronan, Montana', '6189421', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Katon', 'Michael', 'Gerky', 'Katon Michael Gerky', 'MSW', NULL, NULL, NULL, 'Chinook, Montana', '6184704', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Madysen', NULL, 'Hachler', 'Madysen Hachler', 'MSW', NULL, NULL, NULL, 'Helena, Montana', '5826771', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jasmine', 'S', 'Hansen', 'Jasmine Hansen', 'MSW', NULL, NULL, NULL, 'Billings, Montana', '6184697', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Lea', 'R', 'Jefson', 'Lea R Jefson', 'MSW', NULL, NULL, NULL, 'Rexburg, Idaho', '6092685', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Emily', 'J', 'Kreis', 'Emily Jae Kreis', 'MSW', NULL, NULL, NULL, 'Huson, Montana', '6189461', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Marina', 'Helene', 'LaRocque', 'Marina Helene LaRocque', 'MSW', NULL, NULL, NULL, 'Great Falls, Montana', '5691450', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Bailey', NULL, 'Lyman', 'Bailey Lyman', 'MSW', NULL, NULL, NULL, 'Logan, Utah', '6184107', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Erika', 'Jade', 'Mad Plume', 'Erika Jade Mad Plume', 'MSW', NULL, NULL, NULL, 'Browning, Montana', '6189222', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kyra', 'Lee', 'McGarr', 'Kyra Lee McGarr', 'MSW', NULL, NULL, NULL, 'Great Falls, Montana', '6184414', 'Master of Social Work', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Christina', NULL, 'Noel', 'Christina Noel', 'MSW', NULL, NULL, NULL, 'Helena, Montana', '6186232', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Macy', NULL, 'Pinon', 'Macy Piñon', 'MSW', NULL, NULL, NULL, 'Missoula, Montana', '6189523', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Megan', NULL, 'Rennich', 'Megan Rennich', 'MSW', NULL, NULL, NULL, 'Polson, Montana', '6189365', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Nancy', 'A', 'Reynolds', 'Nancy Asiata', 'MSW', NULL, NULL, NULL, 'Helena, Montana', '5857372', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Shelley', 'L', 'Rigby', 'Shelley Lynn Rigby', 'MSW', NULL, NULL, NULL, 'Corvallis, Montana', '6185039', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Baylee', 'M', 'Rook', 'Baylee M Rook', 'MSW', NULL, NULL, NULL, 'Nampa, Idaho', '5601942', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kevin', NULL, 'Sandoval', 'Kevin Dale Sandoval', 'MSW', NULL, NULL, NULL, 'Hardin, Montana', '6185026', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Cynthia', 'Marie', 'Schmidt', 'Cynthia Marie Schmidt', 'MSW', NULL, NULL, NULL, 'Missoula, Montana', '6188544', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Jacob Colter', 'J', 'Schroeder', 'Jacob Colter John Schroeder', 'MSW', NULL, NULL, NULL, 'Livingston, Montana', '6186217', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Chloe', 'R.', 'Stevens', 'Chloe R. Stevens', 'MSW', NULL, NULL, NULL, 'Kalispell, Montana', '5421790', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Elizabeth', NULL, 'Vaughan', 'Elizabeth Vaughan', 'MSW', NULL, NULL, NULL, 'Jourdanton, Texas', '6186670', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Joseph', 'Eugene', 'Wagner', 'Joseph Eugene Wagner', 'MSW', NULL, NULL, NULL, 'Moses Lake, Washington', '6183192', 'Master of Social Work', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Sunni', 'R', 'Warner', 'Sunni Rae Warner', 'MSW', NULL, NULL, NULL, 'Whitefish, Montana', '6189126', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Becky', NULL, 'Wooten', 'Becky Wooten', 'MSW', NULL, NULL, NULL, 'Farmington, Utah', '6186787', 'Master of Social Work', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Megan', 'Riley', 'Baxter', 'Megan Riley Baxter', 'BA', 'Summa Cum Laude', NULL, NULL, 'Thompson Falls, Montana', '6176396', 'Business: Accounting and Strategic Finance', NULL, NULL, NULL, 'Women''s Basketball', 'Women''s Golf', 'Women''s Basketball - JV', NULL, NULL),
('Aura', 'Fernanda', 'Arroyo', 'Aura Fernanda Arroyo', 'BS', NULL, NULL, NULL, 'Porterville, California', '6166260', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Julian', 'M', 'Betz', 'Julian M Betz', 'BS', NULL, NULL, NULL, 'Fall City, Washington', '6177288', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Hailey', NULL, 'Blatchford', 'Hailey Blatchford', 'BS', NULL, NULL, NULL, 'Tacoma, Washington', '6188940', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Eva', 'N', 'Bunger', 'Eva Noel Bunger', 'BS', 'Magna Cum Laude', NULL, NULL, 'Portland, Oregon', '6187470', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Kyla', 'M', 'Dane', 'Kyla M Dane', 'BS', NULL, NULL, NULL, 'Great Falls, Montana', '5906903', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Julia', 'C', 'Devine', 'Julia Caroline Devine', 'BS', 'Summa Cum Laude', NULL, NULL, 'Seattle, Washington', '6051831', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Laura', 'M', 'Dias', 'Laura Michelle Dias', 'BS', NULL, NULL, NULL, 'Clovis, California', '6181767', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Courtney', 'G', 'Gragg', 'Courtney Geraldine Gragg', 'BS', NULL, NULL, NULL, 'Lincoln, California', '6188732', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Callie', NULL, 'Johnson', 'Callie Johnson', 'BS', NULL, NULL, NULL, 'Puyallup, Washington', '6187467', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Abigail', 'M', 'Kolstad', 'Abigail M Kolstad', 'BS', NULL, NULL, NULL, 'Glasgow, Montana', '6188731', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Timothy', 'J', 'Larson', 'Timothy John Larson', 'BS', NULL, NULL, NULL, 'East Helena, Montana', '6187468', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Brennan', 'Reece', 'Nelson', 'Brennan Reece Nelson', 'BS', NULL, NULL, NULL, 'Salem, Oregon', '6184990', 'Accelerated Nursing', NULL, NULL, NULL, 'Military Veterans', NULL, NULL, NULL, NULL),
('Elizabeth', 'A', 'Olsen', 'Elizabeth Ann Olsen', 'BS', 'Magna Cum Laude', NULL, NULL, 'Helena, Montana', '6189084', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Daria', 'Lorene', 'Peck', 'Daria Lorene Peck', 'BS', NULL, NULL, NULL, 'Windsor, Colorado', '6182111', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Emma', 'E', 'Richards', 'Emma Elizabeth Richards', 'BS', 'Magna Cum Laude', NULL, NULL, 'Portland, Oregon', '6188541', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Julie', 'D', 'Shriver', 'Julie D Shriver', 'BS', NULL, NULL, NULL, 'San Diego, California', '6188264', 'Accelerated Nursing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Bryce', 'A', 'Hall', 'Bryce A Hall', 'BA', NULL, NULL, NULL, 'Great Falls, Montana', '6177373', 'Biology', NULL, NULL, NULL, 'ROTC Participants', NULL, NULL, NULL, NULL),
('Jacob', 'R', 'Demmons', 'Jacob R Demmons', 'BA', NULL, NULL, NULL, 'Helena, Montana', '6176640', 'Business: Management and Marketing', NULL, NULL, NULL, 'Men''s Soccer', NULL, NULL, NULL, NULL),
('Justin', NULL, 'Denson', 'Justin Denson', 'BA', NULL, NULL, NULL, 'Portland, Oregon', '6184847', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Ryan', 'P', 'Harvey', 'Ryan Phillip Harvey', 'BA', 'Magna Cum Laude', NULL, NULL, 'Missoula, Montana', '6168425', 'Business: Management and Marketing', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Juan', 'Carlos', 'Muniz Navarrete', 'Juan Carlos Muniz Navarrete', 'BA', NULL, NULL, NULL, 'Hermiston, Oregon', '6184684', 'Business: Management and Marketing', NULL, NULL, NULL, 'Men''s Soccer', 'Global Refugee Mexico', NULL, NULL, NULL),
('Blake', 'A', 'Waldmann', 'Blake A Waldmann', 'BA', NULL, NULL, NULL, 'Boise, Idaho', '6175394', 'Business: Management and Marketing', 'Hispanic Studies and Languages', NULL, NULL, 'Men''s Soccer', NULL, NULL, NULL, NULL),
('Tatem', 'Hannah', 'Schweikert', 'Tatem Hannah Hurricane Schweikert', 'BS', 'Summa Cum Laude', NULL, NULL, 'Columbia Falls, Montana', '6174115', 'Civil Engineering', NULL, NULL, NULL, 'Women''s Volleyball - JV', 'Women''s Volleyball', NULL, NULL, NULL),
('Landon', 'James Ross', 'Humphrey', 'Landon James Ross Humphrey', 'BA', NULL, NULL, NULL, 'Clovis, California', '6177885', 'Communication Studies', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Steven', 'Xavier', 'Sanders', 'Steven Xavier Sanders', 'BA', NULL, NULL, NULL, 'Hemet, California', '6176366', 'History', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Abigail', 'G', 'Merz', 'Abigail G Merz', 'BA', NULL, NULL, NULL, 'Richland, Washington', '6175169', 'Theatre', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Lily', 'Marie', 'Oats', 'Lily Marie Oats', 'BA', NULL, NULL, NULL, 'Helena, Montana', '5734939', 'Public Health', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Annemarie', 'Abigail', 'Johnson', 'AnneMarie Abigail Johnson', 'BA', NULL, NULL, NULL, 'Sheridan, Oregon, USA', '0', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL))
    AS DF(First_Name, Middle_Name, Last_Name, Grad_Diploma_Name, Degree_Type, Latin_Honors, With_Distinction, Honors_Scholars, Grad_Hometown, Grad_Student, Major1, Major2, Major3, Major4, Cohort1, Cohort2, Cohort3, Cohort4, Cohort5)
    LEFT JOIN PERSON ON DF.Grad_Student = PERSON.ID
