--(Begin 2)-------------------------------------------------------------------------------------------------------------
SELECT HONORS,
       COUNT(*) AS COUNT
FROM (
--(Begin 1)-------------------------------------------------------------------------------------------------------------
         SELECT Latin_Honors AS HONORS
         FROM (VALUES ('Madelin', NULL, 'Barbee', 'Madelin Barbee', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Helena, Montana'),
                      ('Alysha', NULL, 'Bruss', 'Alysha Nicole Bruss', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'San Bernardino, California'),
                      ('Skyler', 'Bradley', 'Carroll', 'Skyler Bradley Carroll', 'SOWK.MSW', 'Master of Social Work',
                       'MSW', NULL, NULL, NULL, 'Livingston, Montana'),
                      ('Caitlin', NULL, 'Cooper', 'Caitlin Cooper', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Dillon, Montana'),
                      ('Alexandria', NULL, 'Corbett', 'Alexandra Corbett', 'SOWK.MSW', 'Master of Social Work', 'MSW',
                       NULL, NULL, NULL, 'Helena, Montana'),
                      ('Michael', NULL, 'Elliott', 'Michael Elliott', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Helena, Montana'),
                      ('Angela', 'C', 'Evans', 'Angela C Evans', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Ronan, Montana'),
                      ('Katon', 'Michael', 'Gerky', 'Katon Michael Gerky', 'SOWK.MSW', 'Master of Social Work', 'MSW',
                       NULL, NULL, NULL, 'Chinook, Montana'),
                      ('Madysen', NULL, 'Hachler', 'Madysen Hachler', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Helena, Montana'),
                      ('Jasmine', 'S', 'Hansen', 'Jasmine Hansen', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Billings, Montana'),
                      ('Lea', 'R', 'Jefson', 'Lea R Jefson', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Rexburg, Idaho'),
                      ('Emily', 'J', 'Kreis', 'Emily Jae Kreis', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Huson, Montana'),
                      ('Marina', 'Helene', 'LaRocque', 'Marina Helene LaRocque', 'SOWK.MSW', 'Master of Social Work',
                       'MSW', NULL, NULL, NULL, 'Great Falls, Montana'),
                      ('Bailey', NULL, 'Lyman', 'Bailey Lyman', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Logan, Utah'),
                      ('Erika', 'Jade', 'Mad Plume', 'Erika Jade Mad Plume', 'SOWK.MSW', 'Master of Social Work', 'MSW',
                       NULL, NULL, NULL, 'Browning, Montana'),
                      ('Kyra', 'Lee', 'McGarr', 'Kyra Lee McGarr', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Great Falls, Montana'),
                      ('Christina', NULL, 'Noel', 'Christina Noel', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Helena, Montana'),
                      ('Macy', NULL, 'Pinon', 'Macy Piñon', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Missoula, Montana'),
                      ('Megan', NULL, 'Rennich', 'Megan Rennich', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Polson, Montana'),
                      ('Nancy', 'A', 'Reynolds', 'Nancy Asiata', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Helena, Montana'),
                      ('Shelley', 'L', 'Rigby', 'Shelley Lynn Rigby', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Corvallis, Montana'),
                      ('Baylee', 'M', 'Rook', 'Baylee M Rook', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Nampa, Idaho'),
                      ('Kevin', NULL, 'Sandoval', 'Kevin Dale Sandoval', 'SOWK.MSW', 'Master of Social Work', 'MSW',
                       NULL, NULL, NULL, 'Hardin, Montana'),
                      ('Cynthia', 'Marie', 'Schmidt', 'Cynthia Marie Schmidt', 'SOWK.MSW', 'Master of Social Work',
                       'MSW', NULL, NULL, NULL, 'Missoula, Montana'),
                      ('Jacob Colter', 'J', 'Schroeder', 'Jacob Colter John Schroeder', 'SOWK.MSW',
                       'Master of Social Work', 'MSW', NULL, NULL, NULL, 'Livingston, Montana'),
                      ('Chloe', 'R.', 'Stevens', 'Chloe R. Stevens', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Kalispell, Montana'),
                      ('Elizabeth', NULL, 'Vaughan', 'Elizabeth Vaughan', 'SOWK.MSW', 'Master of Social Work', 'MSW',
                       NULL, NULL, NULL, 'Jourdanton, Texas'),
                      ('Joseph', 'Eugene', 'Wagner', 'Joseph Eugene Wagner', 'SOWK.MSW', 'Master of Social Work', 'MSW',
                       NULL, NULL, NULL, 'Moses Lake, Washington'),
                      ('Sunni', 'R', 'Warner', 'Sunni Rae Warner', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL,
                       NULL, NULL, 'Whitefish, Montana'),
                      ('Becky', NULL, 'Wooten', 'Becky Wooten', 'SOWK.MSW', 'Master of Social Work', 'MSW', NULL, NULL,
                       NULL, 'Farmington, Utah'),
                      ('Mariah', 'A', 'Moran', 'Mariah A Moran', 'ANZO.BA',
                       'Anthrozoology | Biochemistry/Molecular Biology', 'BA', 'Magna Cum Laude', NULL, NULL,
                       'Washougal, Washington'),
                      ('Kaylee', 'Anne', 'Broderick', 'Kaylee Anne Broderick', 'ANZO.BA', 'Anthrozoology', 'BA',
                       'Cum Laude', NULL, NULL, 'Palm City, Florida'),
                      ('Allison', 'Clare', 'Bullman', 'Allison Clare Bullman', 'ANZO.BA', 'Anthrozoology', 'BA', NULL,
                       NULL, NULL, 'Billings, Montana'),
                      ('Aubrey', 'Rose', 'Damm', 'Aubrey Rose Damm', 'ANZO.BA', 'Anthrozoology', 'BA', 'Cum Laude',
                       NULL, NULL, 'Silver Springs, Nevada'),
                      ('Julianna', NULL, 'Hopper', 'Julianna Hopper', 'ANZO.BA', 'Anthrozoology', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Hillsborough, North Carolina'),
                      ('Sarah', 'Eseta', 'Hoyt', 'Sarah E. Hoyt', 'ANZO.BA', 'Anthrozoology', 'BA', 'Cum Laude', NULL,
                       NULL, 'Port Orchard, Washington'),
                      ('Sydney', 'Jane', 'Lamb', 'Sydney Jane Lamb', 'ANZO.BA', 'Anthrozoology', 'BA', NULL, NULL, NULL,
                       'Spokane, Washington'),
                      ('Jesica', 'May', 'Masshardt', 'Jesica May Masshardt', 'ANZO.BA', 'Anthrozoology', 'BA', NULL,
                       NULL, NULL, 'Sheridan, Montana'),
                      ('Natalie', 'Floreine', 'Powell', 'Natalie Floreine Powell', 'ANZO.BA', 'Anthrozoology', 'BA',
                       'Cum Laude', NULL, NULL, 'Everett, Washington'),
                      ('John Paul', NULL, 'Robertson', 'John Paul Robertson', 'ANZO.BA', 'Anthrozoology', 'BA', NULL,
                       'Y', 'Y', 'Spokane, Washington'),
                      ('Alyssa', 'L', 'Rubio', 'Alyssa L Rubio', 'ANZO.BA', 'Anthrozoology', 'BA', 'Magna Cum Laude',
                       NULL, NULL, 'Happy Valley, Oregon'),
                      ('Morgan', 'E', 'Tekorius', 'Morgan E Tekorius', 'ANZO.BA', 'Anthrozoology', 'BA', NULL, NULL,
                       NULL, 'Oregon City, Oregon'),
                      ('Kylee', 'Brooke', 'Wilcox', 'Kylee Brooke Wilcox', 'ANZO.BA', 'Anthrozoology', 'BA', NULL, NULL,
                       NULL, 'Simsbury, Connecticut'),
                      ('Margaret', 'Elizabeth', 'Young', 'Margaret Elizabeth Young', 'ANZO.BA', 'Anthrozoology', 'BA',
                       NULL, NULL, NULL, 'Las Vegas, Nevada'),
                      ('Katherine', 'M', 'Bold', 'Katherine Mary Bold', 'BCMB.BA', 'Biochemistry/Molecular Biology',
                       'BA', 'Magna Cum Laude', 'Y', NULL, 'Big Sandy, Montana'),
                      ('Landen', 'Rey', 'Conner', 'Landen Rey Conner', 'BCMB.BA', 'Biochemistry/Molecular Biology',
                       'BA', 'Magna Cum Laude', NULL, NULL, 'Corvallis, Montana'),
                      ('Mila', 'Isabelle', 'Duncan', 'Mila Isabelle Duncan', 'BCMB.BA',
                       'Biochemistry/Molecular Biology', 'BA', NULL, NULL, NULL, 'Seattle, Washington'),
                      ('Macie', 'C', 'Frans', 'Macie C Frans', 'BCMB.BA', 'Biochemistry/Molecular Biology', 'BA',
                       'Cum Laude', NULL, NULL, 'Boise, Idaho'),
                      ('Rachel', 'Rosemary', 'Kaiser', 'Rachel Rosemary Kaiser', 'BCMB.BA',
                       'Biochemistry/Molecular Biology', 'BA', 'Summa Cum Laude', NULL, NULL, 'Bozeman, Montana'),
                      ('Carson', 'T', 'Lewis', 'Carson Lewis', 'BCMB.BA', 'Biochemistry/Molecular Biology', 'BA',
                       'Summa Cum Laude', NULL, NULL, 'Lewistown, Montana'),
                      ('Adisyn', 'Grace Margarette', 'O''Connor', 'Adisyn Grace Margarette O''Connor', 'BCMB.BA',
                       'Biochemistry/Molecular Biology', 'BA', 'Summa Cum Laude', NULL, NULL, 'Billings, Montana'),
                      ('Vicente', 'Mora', 'Ortega', 'Vicente Mora Ortega', 'BCMB.BA', 'Biochemistry/Molecular Biology',
                       'BA', NULL, 'Y', NULL, 'Ronan, Montana'),
                      ('Zackery', 'James', 'Prokopyschyn', 'Zackery James Prokopyschyn', 'BCMB.BA',
                       'Biochemistry/Molecular Biology', 'BA', NULL, NULL, NULL, 'Arvada, Colorado'),
                      ('Mederise', 'Michelle', 'Tooke', 'Mederise Michelle Tooke', 'BCMB.BA',
                       'Biochemistry/Molecular Biology', 'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Marrin', 'F', 'Chapman', 'Marrin Frances Bertoglio Chapman', 'BIOL.BA',
                       'Biology | Catholic Studies', 'BA', 'Summa Cum Laude', NULL, NULL, 'Montana City, Montana'),
                      ('June', 'Margaret', 'Lepage', 'June Margaret LePage', 'BIOL.BA',
                       'Biology | Hispanic Studies and Languages', 'BA', 'Magna Cum Laude', NULL, 'Y',
                       'Lewistown, Montana'),
                      ('Megan', 'Lucienne', 'Olsen', 'Megan Lucienne Olsen', 'BIOL.BA',
                       'Biology | Hispanic Studies and Languages', 'BA', 'Magna Cum Laude', NULL, 'Y',
                       'Bozeman, Montana'),
                      ('Wade', 'S', 'Luly', 'Wade S Luly', 'BIOL.BA', 'Biology | Health Sciences', 'BA', NULL, NULL,
                       NULL, 'Shelby, Montana'),
                      ('Corinne', 'Simone', 'Anderko', 'Corinne Simone Anderko', 'BIOL.BA', 'Biology', 'BA', NULL, NULL,
                       NULL, 'Danielsville, Pennsylvania'),
                      ('Emma', 'Jinshi', 'Boharski', 'Emma Jin Shi Boharski', 'BIOL.BA', 'Biology', 'BA', 'Cum Laude',
                       NULL, NULL, 'Deer Park, Washington'),
                      ('Clara', 'Marie', 'Carpenter', 'Clara Marie Carpenter', 'BIOL.BA', 'Biology', 'BA', NULL, NULL,
                       NULL, 'Coeur d''Alene, Idaho'),
                      ('Laura', 'K', 'DeBowes', 'Laura Katherine DeBowes', 'BIOL.BA', 'Biology', 'BA', 'Cum Laude',
                       NULL, NULL, 'Spokane, Washington'),
                      ('Michael', 'R', 'Deguzman', 'Michael R Deguzman', 'BIOL.BA', 'Biology', 'BA', NULL, NULL, NULL,
                       'Lewistown, Montana'),
                      ('Josie', 'C', 'Gale', 'Josie Carolyn Gale', 'BIOL.BA', 'Biology', 'BA', NULL, NULL, 'Y',
                       'Minneapolis, Minnesota'),
                      ('Daxon', 'Arlo', 'Graham', 'Daxon Arlo Graham', 'BIOL.BA', 'Biology', 'BA', 'Cum Laude', NULL,
                       NULL, 'Dillon, Montana'),
                      ('Bryce', 'A', 'Hall', 'Bryce A Hall', 'BIOL.BA', 'Biology', 'BA', NULL, NULL, NULL,
                       'Great Falls, Montana'),
                      ('Terra', 'M', 'Hurt', 'Terra Hurt', 'BIOL.BA', 'Biology', 'BA', 'Magna Cum Laude', NULL, NULL,
                       'Colorado Springs, Colorado'),
                      ('Chloe', 'P', 'Jones', 'Chloe P Jones', 'BIOL.BA', 'Biology', 'BA', 'Summa Cum Laude', NULL,
                       NULL, 'Newport, Washington'),
                      ('Edouard', 'Gregory', 'Karleskind', 'Edouard Gregory Karleskind', 'BIOL.BA', 'Biology', 'BA',
                       NULL, NULL, NULL, 'Alamo, California'),
                      ('Maximilien', 'Marie', 'Karleskind', 'Maximilien Marie Karleskind', 'BIOL.BA', 'Biology', 'BA',
                       NULL, NULL, NULL, 'Alamo, California'),
                      ('Serena', 'Nicole', 'Keil-Hoye', 'Serena Keil-Hoye', 'BIOL.BA', 'Biology', 'BA', NULL, NULL,
                       NULL, 'Kalispell, Montana'),
                      ('Kieran', 'J', 'McGuire', 'Kieran McGuire', 'BIOL.BA', 'Biology', 'BA', NULL, NULL, NULL,
                       'Colorado Springs, Colorado'),
                      ('Trey', 'James', 'Melton', 'Trey James Melton', 'BIOL.BA', 'Biology', 'BA', 'Summa Cum Laude',
                       NULL, 'Y', 'Helena, Montana'),
                      ('Michal', 'Melichar', 'Mojzis', 'Michal Melichar Mojzis', 'BIOL.BA', 'Biology', 'BA', NULL, 'Y',
                       NULL, 'Bratislava, Slovakia'),
                      ('Hunter', 'Bruce', 'Peck', 'Hunter Bruce Peck', 'BIOL.BA', 'Biology', 'BA', 'Cum Laude', NULL,
                       NULL, 'Windsor, Colorado'),
                      ('Nathan', 'A', 'Stalder', 'Nathan Anton Stalder', 'BIOL.BA', 'Biology', 'BA', 'Cum Laude', NULL,
                       NULL, 'Issaquah, Washington'),
                      ('Kenna', 'L', 'Thomas', 'Kenna L Thomas', 'BIOL.BA', 'Biology', 'BA', 'Summa Cum Laude', NULL,
                       NULL, 'Belgrade, Montana'),
                      ('Andrew', 'W', 'Denegar', 'Andrew W Denegar', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance | Data Science', 'BA', 'Summa Cum Laude', NULL, NULL,
                       'Great Falls, Montana'),
                      ('Sydney', NULL, 'Snyder', 'Sydney Snyder', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance | Business: Financial Planning | Business: Managmt and Marketing',
                       'BA', NULL, NULL, NULL, 'Minneapolis, Minnesota'),
                      ('Megan', 'Riley', 'Baxter', 'Megan Riley Baxter', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', 'Summa Cum Laude', NULL, NULL,
                       'Thompson Falls, Montana'),
                      ('Kaitlyn', 'Heather', 'Fellows', 'Kaitlyn Heather Fellows', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', 'Summa Cum Laude', NULL, NULL,
                       'Great Falls, Montana'),
                      ('Avery', 'E', 'Kelly', 'Avery E Kelly', 'ACSF.BA', 'Business: Accounting and Strategic Finance',
                       'BA', 'Cum Laude', NULL, NULL, 'Butte, Montana'),
                      ('James', 'Matthew', 'Lang', 'James Matthew Lang', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', 'Magna Cum Laude', NULL, NULL,
                       'Portland, Oregon'),
                      ('Camyrn', 'Dawn', 'Larson', 'Camyrn Larson', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', 'Magna Cum Laude', NULL, NULL,
                       'White Sulphur Springs, Montana'),
                      ('Sophia', 'A', 'McAdam', 'Sophia A McAdam', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', NULL, NULL, NULL, 'Portland, Oregon'),
                      ('Jaden', 'Helene', 'Mueller', 'Jaden Helene Mueller', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', NULL, NULL, NULL, 'Maple Grove, Minnesota'),
                      ('Savannah', 'K', 'Rydalch', 'Savannah K Rydalch', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', 'Summa Cum Laude', NULL, NULL,
                       'Saint Anthony, Idaho'),
                      ('Isaac', 'Robert', 'Schilter', 'Isaac Robert Schilter', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', NULL, NULL, NULL, 'Olympia, Washington'),
                      ('Elizabeth', 'Catherine', 'Ybarra', 'Elizabeth Catherine Ybarra', 'ACSF.BA',
                       'Business: Accounting and Strategic Finance', 'BA', NULL, NULL, NULL, 'Fullerton, California'),
                      ('Ellee', 'Grace', 'Page', 'Ellee Grace Page', 'FNPL.BA', 'Business: Financial Planning', 'BA',
                       NULL, NULL, NULL, 'Lamar, Colorado'),
                      ('Keel', 'John', 'Potter', 'Keel John Potter', 'FNPL.BA', 'Business: Financial Planning', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Coeur d''Alene, Idaho'),
                      ('Jamie', 'Rae', 'Burbank', 'Jamie Burbank', 'BSMM.BA',
                       'Business: Management and Marketing | Communication Studies', 'BA', 'Cum Laude', NULL, NULL,
                       'Helena, Montana'),
                      ('Benjamin', 'Francisco Jose', 'Paz', 'Benjamin Francisco Jose Paz', 'BSMM.BA',
                       'Business: Management and Marketing | Business: Accountng & Strategic Finance', 'BA', NULL, NULL,
                       NULL, 'Bellingham, Washington'),
                      ('Blake', 'A', 'Waldmann', 'Blake A Waldmann', 'BSMM.BA',
                       'Business: Management and Marketing | Hispanic Studies and Languages', 'BA', NULL, NULL, NULL,
                       'Boise, Idaho'),
                      ('Denavion', 'Mohammed', 'Ali', 'Denavion Mohammed Ali', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Denver, Colorado'),
                      ('Quinn', 'W', 'Belcher', 'Quinn W Belcher', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Kyle', 'David', 'Bender', 'Kyle David Bender', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', NULL, NULL, NULL, 'Saginaw, Michigan'),
                      ('Abigail', 'Marie', 'Brown', 'Abigail Marie Brown', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Olympia, Washington'),
                      ('Jacob', 'R', 'Demmons', 'Jacob R Demmons', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Justin', NULL, 'Denson', 'Justin Denson', 'BSMM.BA', 'Business: Management and Marketing', 'BA',
                       NULL, NULL, NULL, 'Portland, Oregon'),
                      ('Ryan', 'P', 'Harvey', 'Ryan Phillip Harvey', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', 'Magna Cum Laude', NULL, NULL, 'Missoula, Montana'),
                      ('Logan', 'David', 'Hill', 'Logan David Hill', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', 'Cum Laude', NULL, NULL, 'Billings, Montana'),
                      ('Kyndall', 'S', 'Keller', 'Kyndall S Keller', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', 'Magna Cum Laude', NULL, NULL, 'Havre, Montana'),
                      ('Derek', 'Albert', 'Kramer', 'Derek Albert Kramer', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Bellevue, Washington'),
                      ('Anna', 'Claire', 'Kretzschmar', 'Anna Claire Kretzschmar', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Anchorage, Alaska'),
                      ('Elijah', 'Cole', 'Larson', 'Elijah Cole Larson', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Spokane, Washington'),
                      ('Henry', 'Bruce', 'Lauerman', 'Henry Bruce Lauerman', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Britlyn', 'Haze', 'Mailey', 'Britlyn Haze Mailey', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Bozeman, Montana'),
                      ('Emilie', 'G', 'Munguia', 'Emilie Grace Munguia', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', 'Magna Cum Laude', NULL, NULL, 'Yakima, Washington'),
                      ('Juan', 'Carlos', 'Muniz Navarrete', 'Juan Carlos Muniz Navarrete', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Hermiston, Oregon'),
                      ('Kolbe', 'John', 'Olmes', 'Kolbe John Olmes', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Ryan', 'J', 'Rickman', 'Ryan Rickman', 'BSMM.BA', 'Business: Management and Marketing', 'BA',
                       NULL, NULL, NULL, 'Sublimity, Oregon'),
                      ('Quinn', 'Carter', 'Stamps', 'Quinn Carter Stamps', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', NULL, NULL, NULL, 'Chelan, Washington'),
                      ('Griffin', NULL, 'Teuber', 'Griffin Teuber', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', NULL, NULL, NULL, 'Boise, Idaho'),
                      ('Tysen', 'Eugene', 'Thatcher', 'Tysen Eugene Thatcher', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', 'Cum Laude', NULL, NULL, 'Helena, Montana'),
                      ('Isadora', 'G', 'Tomazeli', 'Isadora Tomazeli', 'BSMM.BA', 'Business: Management and Marketing',
                       'BA', NULL, NULL, NULL, 'Sao Paulo, Brazil'),
                      ('Chayton', 'James', 'Winkle', 'Chayton James Winkle', 'BSMM.BA',
                       'Business: Management and Marketing', 'BA', 'Magna Cum Laude', NULL, NULL, 'Helena, Montana'),
                      ('Sofia', 'Marie', 'Frongillo', 'Sofia Marie Frongillo', 'CATH.BA', 'Catholic Studies | Theology',
                       'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Luke', 'Stephen', 'Ostberg', 'Luke Stephen Ostberg', 'CATH.BA', 'Catholic Studies | Philosophy',
                       'BA', 'Summa Cum Laude', 'Y', 'Y', 'Fairfield, Montana'),
                      ('Jack', 'Nichols', 'Snouwaert', 'Jack Nichols Snouwaert', 'CATH.BA',
                       'Catholic Studies | Communication Studies', 'BA', NULL, NULL, NULL, 'Palmer Lake, Colorado'),
                      ('Christopher', 'Andrew', 'Szpilka', 'Christopher Andrew Szpilka', 'CATH.BA',
                       'Catholic Studies | Physics', 'BA', 'Summa Cum Laude', NULL, NULL, 'Helena, Montana'),
                      ('Laura', 'Ann', 'Fontaine', 'Laura Ann Fontaine', 'CHEM.BA',
                       'Chemistry | Hispanic Studies and Languages', 'BA', 'Cum Laude', NULL, NULL,
                       'Darien Center, New York'),
                      ('Charles', 'Benson', 'Markham', 'Charles Benson Markham', 'CHEM.BA', 'Chemistry', 'BA',
                       'Cum Laude', NULL, NULL, 'Spokane, Washington'),
                      ('Kacy', 'Stevens', 'Clements', 'Kacy Stevens Clements', 'COMM.BA',
                       'Communication Studies: Public Relations & Social Media', 'BA', 'Cum Laude', NULL, NULL,
                       'Nederland, Colorado'),
                      ('Landon', 'James Ross', 'Humphrey', 'Landon James Ross Humphrey', 'COMM.BA',
                       'Communication Studies: Interpersonal Communication', 'BA', NULL, NULL, NULL,
                       'Clovis, California'),
                      ('Katie', 'Marie', 'Bell', 'Katie Marie Bell', 'COMM.BA', 'Communication Studies', 'BA', NULL,
                       NULL, NULL, 'Bellingham, Washington'),
                      ('Jonathen', 'T', 'Reiser', 'Jonathen T Reiser', 'COMM.BA', 'Communication Studies', 'BA',
                       'Cum Laude', NULL, NULL, 'Dillon, Montana'),
                      ('Kaitlyn', 'Mae', 'Wenzel', 'Kaitlyn Ruch Wenzel', 'COMM.BA',
                       'Communication Studies | Catholic Studies', 'BA', 'Magna Cum Laude', NULL, NULL,
                       'Helena, Montana'),
                      ('Aidan', 'Clinton', 'Scott', 'Aidan Clinton Scott', 'CSIS.BA',
                       'Computer Science | Computer Information Systems | Business: Financial Planning', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Townsend, Montana'),
                      ('Abigail', 'Maureen', 'Brown', 'Abigail Maureen Brown', 'CSCI.BA',
                       'Computer Science | Data Science', 'BA', 'Summa Cum Laude', 'Y', NULL, 'Kennewick, Washington'),
                      ('Adrian', 'Alexander', 'Rincon-Jimenez', 'Adrian Alexander Rincon Jimenez', 'CSCI.BA',
                       'Computer Science | Data Science', 'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('John', 'J', 'Botonakis', 'John J Botonakis', 'CSCI.BA', 'Computer Science', 'BA', NULL, NULL,
                       NULL, 'Chicago, Illinois'),
                      ('Justin', 'M', 'Forseth', 'Justin Forseth', 'CSCI.BA', 'Computer Science', 'BA',
                       'Summa Cum Laude', NULL, NULL, 'Fairfield, Montana'),
                      ('Jack', 'Alexander', 'Holy', 'Jack Alexander Holy', 'CSCI.BA', 'Computer Science', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Calgary, Alberta'),
                      ('Charles', NULL, 'Said', 'Charles Said', 'DSCI.BA', 'Data Science | Political Science', 'BA',
                       'Magna Cum Laude', 'Y', NULL, 'Woodinville, Washington'),
                      ('Murat', 'Can', 'Guzelocak', 'Murat Can Guzelocak', 'DSCI.BA', 'Data Science', 'BA', NULL, NULL,
                       NULL, 'Istanbul, Turkey'),
                      ('Cole', 'C', 'Odegard', 'Cole C Odegard', 'DSCI.BA', 'Data Science', 'BA', 'Summa Cum Laude',
                       'Y', NULL, 'Beaverton, Oregon'),
                      ('Jonathan', 'Martin', 'Goodman', 'Jonathan Martin Goodman', 'ELED.BA',
                       'Elementary Education: Middle School Concentration', 'BA', NULL, NULL, NULL,
                       'Newport, Washington'),
                      ('Courtney', 'Elizabeth', 'Boese', 'Courtney Elizabeth Boese', 'ELED.BA', 'Elementary Education',
                       'BA', 'Summa Cum Laude', NULL, NULL, 'Deer Lodge, Montana'),
                      ('Amber', 'Lynn', 'Countryman', 'Amber Lynn Countryman', 'ELED.BA', 'Elementary Education', 'BA',
                       NULL, NULL, NULL, 'Helena, Montana'),
                      ('Corinna', 'R', 'Hatfield', 'Corinna R Hatfield', 'ELED.BA', 'Elementary Education', 'BA', NULL,
                       NULL, NULL, 'McCall, Idaho'),
                      ('Jack', 'W', 'Prka', 'Jack William Prka', 'ELED.BA', 'Elementary Education', 'BA', NULL, NULL,
                       NULL, 'Coeur d''Alene, Idaho'),
                      ('Angelique', 'C', 'Rubio-Casanova', 'Angelique C Rubio-Casanova', 'ELED.BA',
                       'Elementary Education', 'BA', 'Magna Cum Laude', NULL, NULL, 'Kent, Washington'),
                      ('Brooke', 'Mary', 'Vandehey', 'Brooke Mary Vandehey', 'ELED.BA', 'Elementary Education', 'BA',
                       'Summa Cum Laude', NULL, NULL, 'North Plains, Oregon'),
                      ('Madeline', 'Nancy', 'Vandehey', 'Madeline Nancy Vandehey', 'ELED.BA', 'Elementary Education',
                       'BA', 'Summa Cum Laude', NULL, NULL, 'North Plains, Oregon'),
                      ('Mekenzie', 'Grace', 'Arnold', 'Mekenzie Grace Arnold', 'ELSP.BA',
                       'Elementary Education K-8 & Special Education K-12', 'BA', NULL, NULL, NULL,
                       'La Habra, California'),
                      ('Erika', 'J', 'Arthur', 'Erika J Arthur', 'ELSP.BA',
                       'Elementary Education K-8 & Special Education K-12', 'BA', 'Cum Laude', NULL, NULL,
                       'Soldotna, Alaska'),
                      ('Madeline', 'Faith', 'Visser', 'Madeline Faith Visser', 'ELSP.BA',
                       'Elementary Education K-8 & Special Education K-12', 'BA', 'Summa Cum Laude', NULL, NULL,
                       'Manhattan, Montana'),
                      ('Mailee', 'Tran', 'Bui', 'Mailee Tran Bui', 'ENSE.BA', 'English Education (5-12)', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Kennewick, Washington'),
                      ('Jackson', 'M', 'Cossairt', 'Jackson M Cossairt', 'MASE.BA', 'Mathematics Education (5-12)',
                       'BA', 'Cum Laude', 'Y', NULL, 'Westmont, Illinois'),
                      ('Trinity', 'E', 'Edwards', 'Trinity Elise Edwards', 'MASE.BA', 'Mathematics Education (5-12)',
                       'BA', 'Summa Cum Laude', 'Y', NULL, 'Winifred, Montana'),
                      ('Reagan', 'Bourquin', 'Ryan', 'Reagan Bourquin Ryan', 'MASE.BA', 'Mathematics Education (5-12)',
                       'BA', 'Summa Cum Laude', 'Y', NULL, 'Great Falls, Montana'),
                      ('Anna', 'E', 'Brown', 'Anna Elizabeth Brown', 'ENLT.BA',
                       'English Literature | Political Science: Law and Politics', 'BA', 'Summa Cum Laude', NULL, 'Y',
                       'Olympia, Washington'),
                      ('Mildred', 'A', 'Elbert', 'Mildred A Elbert', 'ENLT.BA', 'English Literature | English Writing',
                       'BA', NULL, NULL, NULL, 'Clancy, Montana'),
                      ('Madeline', 'G', 'De Leo', 'Madeline Grace De Leo', 'ENWR.BA',
                       'English Writing | English Literature', 'BA', 'Magna Cum Laude', NULL, NULL,
                       'Corvallis, Montana'),
                      ('Danait', 'Getahun', 'Kassa', 'Danait Kassa', 'ENWR.BA', 'English Writing', 'BA', NULL, NULL,
                       NULL, 'Mekelle, Ethiopia'),
                      ('Caleb', 'J', 'Smith', 'Caleb J Smith', 'EVSS.BA', 'Environmental Science | Biology', 'BA', NULL,
                       NULL, NULL, 'Columbia Falls, Montana'),
                      ('Nathaniel', 'Kai', 'Gong', 'Nathaniel Gong', 'EVSS.BA', 'Environmental Science', 'BA',
                       'Summa Cum Laude', NULL, NULL, 'Hillsboro, Oregon'),
                      ('Norbert', 'Joseph', 'Karczewski', 'Norbert Joseph Karczewski IV', 'EVSS.BA',
                       'Environmental Science', 'BA', 'Magna Cum Laude', NULL, NULL, 'Pensacola, Florida'),
                      ('Garrett', 'A', 'Oleson', 'Garrett A Oleson', 'EVSS.BA', 'Environmental Science', 'BA', NULL,
                       NULL, NULL, 'Helena, Montana'),
                      ('Margaret', 'Louise', 'Todd', 'Margaret Louise Todd', 'EVSS.BA', 'Environmental Science', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Polson, Montana'),
                      ('Willem', 'Michael', 'Trainor', 'Willem Michael Trainor', 'EVSS.BA', 'Environmental Science',
                       'BA', NULL, NULL, NULL, 'Cleveland, Ohio'),
                      ('Addison', 'Grace', 'Ekstrom', 'Addison Ekstrom', 'HSCI.BA', 'Health Sciences | Public Health',
                       'BA', 'Summa Cum Laude', NULL, NULL, 'Bozeman, Montana'),
                      ('Zachary', 'Andrew', 'Rector', 'Zachary Andrew Rector', 'HSCI.BA',
                       'Health Sciences | Public Health', 'BA', NULL, NULL, NULL, 'Portland, Oregon'),
                      ('Aysia', 'M', 'Rogne', 'Aysia M Rogne', 'HSCI.BA', 'Health Sciences | Public Health', 'BA', NULL,
                       NULL, NULL, 'Helena, Montana'),
                      ('Julian', NULL, 'Arias', 'Julian Arias', 'HSCI.BA', 'Health Sciences', 'BA', NULL, NULL, NULL,
                       'Spokane, Washington'),
                      ('Coulter', 'G', 'Cloninger', 'Coulter G Cloninger', 'HSCI.BA', 'Health Sciences', 'BA', NULL,
                       NULL, NULL, 'Spokane, Washington'),
                      ('Mikenna', 'K', 'Deschamps', 'Mikenna K Deschamps', 'HSCI.BA', 'Health Sciences', 'BA', NULL,
                       NULL, NULL, 'Missoula, Montana'),
                      ('Jack', 'Robert', 'England', 'Jack Robert England', 'HSCI.BA', 'Health Sciences', 'BA',
                       'Cum Laude', NULL, NULL, 'Meridian, Idaho'),
                      ('Robert', 'J', 'Hague', 'R. Jackson Hague', 'HSCI.BA', 'Health Sciences', 'BA', NULL, NULL, NULL,
                       'Idaho Falls, Idaho'),
                      ('Kailen', 'L', 'Herbstritt', 'Kailen L Herbstritt', 'HSCI.BA', 'Health Sciences', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Corvallis, Montana'),
                      ('Maxwell', 'Jeffery', 'Lehman', 'Maxwell Jeffery Lehman', 'HSCI.BA', 'Health Sciences', 'BA',
                       NULL, NULL, NULL, 'Meridian, Idaho'),
                      ('Alyssa', 'Jocelyn', 'Lybbert', 'Alyssa Jocelyn Lybbert', 'HSCI.BA', 'Health Sciences', 'BA',
                       'Cum Laude', NULL, NULL, 'Las Vegas, Nevada'),
                      ('Leah', 'Therese', 'Manning', 'Leah Therese Manning', 'HSCI.BA', 'Health Sciences', 'BA',
                       'Cum Laude', NULL, NULL, 'Mission Viejo, California'),
                      ('Mitchell', 'Ross', 'Muralt', 'Mitchell Ross Muralt', 'HSCI.BA', 'Health Sciences', 'BA', NULL,
                       NULL, NULL, 'Missoula, Montana'),
                      ('Riley', 'J', 'Navarro', 'Riley J Navarro', 'HSCI.BA', 'Health Sciences', 'BA', NULL, NULL, NULL,
                       'Carson City, Nevada'),
                      ('Carson', 'Charles', 'Ochoa', 'Carson J Charles Ochoa', 'HSCI.BA', 'Health Sciences', 'BA', NULL,
                       NULL, NULL, 'Yorba Linda, California'),
                      ('Mason', 'P', 'Pereira', 'Mason Paul Pereira', 'HSCI.BA', 'Health Sciences', 'BA', NULL, NULL,
                       NULL, 'Altadena, California'),
                      ('Maddy', NULL, 'Quigley', 'Madison Quigley', 'HSCI.BA', 'Health Sciences', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Coeur d''Alene, Idaho'),
                      ('Gabrielle', NULL, 'Sheridan', 'Gabrielle Anne Sheridan', 'HSCI.BA', 'Health Sciences', 'BA',
                       NULL, NULL, NULL, 'Helena, Montana'),
                      ('Isabella', 'S', 'Sweet', 'Isabella Sophia Sweet', 'HSCI.BA', 'Health Sciences', 'BA',
                       'Cum Laude', NULL, NULL, 'West Palm Beach, Florida'),
                      ('Kelly', 'Ann', 'White', 'Kelly Ann White', 'HSCI.BA', 'Health Sciences', 'BA', NULL, NULL, NULL,
                       'Butte, Montana'),
                      ('Zachary', 'Scott', 'Wickens', 'Zachary Scott Wickens', 'HSCI.BA', 'Health Sciences', 'BA', NULL,
                       NULL, NULL, 'Townsend, Montana'),
                      ('Thomas', 'Henry', 'Carty', 'Thomas Henry Carty', 'HIST.BA', 'History', 'BA', 'Magna Cum Laude',
                       NULL, NULL, 'Sandpoint, Idaho'),
                      ('James', 'Michael', 'Peruzzi', 'James Michael Peruzzi', 'HIST.BA', 'History', 'BA', NULL, NULL,
                       NULL, 'North Weymouth, Massachusetts'),
                      ('Taylor', 'Lela Tyson', 'Plant', 'Taylor Lela Tyson Plant', 'HIST.BA', 'History', 'BA', NULL,
                       NULL, NULL, 'Helena, Montana'),
                      ('Jonathan', 'M D', 'Rose', 'Jonathan M D Rose', 'HIST.BA', 'History', 'BA', NULL, NULL, NULL,
                       'Helena, Montana'),
                      ('Steven', 'Xavier', 'Sanders', 'Steven Xavier Sanders', 'HIST.BA', 'History', 'BA', NULL, NULL,
                       NULL, 'Hemet, California'),
                      ('Josephine', 'Elise', 'Stevenson', 'Josephine Elise Stevenson', 'INTR.BA',
                       'International Relations | Political Science', 'BA', 'Cum Laude', NULL, 'Y', 'Redmond, Oregon'),
                      ('Ryan', 'J', 'Cain', 'Ryan James Cain', 'MATH.BA', 'Mathematics', 'BA', NULL, NULL, NULL,
                       'Helena, Montana'),
                      ('Clare', 'A', 'Daley', 'Clare A Daley', 'MATH.BA', 'Mathematics: Business/Economics', 'BA',
                       'Magna Cum Laude', 'Y', NULL, 'West Yellowstone, Montana'),
                      ('Abraham', 'J', 'Montalvo', 'Abraham J Montalvo', 'MATH.BA', 'Mathematics | Data Science', 'BA',
                       'Summa Cum Laude', 'Y', NULL, 'Terry, Montana'),
                      ('Kara', 'Ann Therese', 'Donahue', 'Kara Ann Therese Donahue', 'PHIL.BA',
                       'Philosophy | Catholic Studies', 'BA', NULL, NULL, NULL, 'Kalispell, Montana'),
                      ('Ryan', 'L', 'Frampton', 'Ryan L Frampton', 'PHIL.BA', 'Philosophy | Catholic Studies', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Whitefish, Montana'),
                      ('Andrew', 'Douglas', 'Devine', 'Andrew Douglas Devine', 'PHIL.BA', 'Philosophy', 'BA', NULL,
                       NULL, NULL, 'Wasilla, Alaska'),
                      ('Maclain', 'John', 'Holland', 'Maclain John Holland', 'POLS.BA',
                       'Political Science | International Relations', 'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Sofia', 'Michaela', 'Wright', 'Sofia Michaela Wright', 'POLS.BA',
                       'Political Science | International Relations', 'BA', NULL, NULL, NULL, 'Renton, Washington'),
                      ('Maci', 'Kei', 'Sakaguchi', 'Maci Kei Sakaguchi', 'POLS.BA',
                       'Political Science: Law and Politics | International Relations', 'BA', NULL, NULL, NULL,
                       'Helena, Montana'),
                      ('Sheerley', 'Veronikah', 'Ugarte Arostegui', 'Veronikah Ugarte Arostegui', 'POLS.BA',
                       'Political Science | Philosophy', 'BA', NULL, NULL, 'Y', 'Salt Lake City, Utah'),
                      ('Spencer', 'Madison-Judith', 'McDonald', 'Spencer McDonald', 'POLS.BA', 'Political Science',
                       'BA', NULL, NULL, NULL, 'Missoula, Montana'),
                      ('Jack', 'Henry', 'McDonald Garrity', 'Jack McDonald Garrity', 'POLS.BA', 'Political Science',
                       'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Riley', 'J', 'Stansberry', 'Riley J Stansberry', 'POLS.BA', 'Political Science', 'BA', NULL,
                       NULL, NULL, 'Spokane, Washington'),
                      ('Katie', 'Elizabeth', 'Benevides', 'Katie Elizabeth Benevides', 'SDMJ.BA',
                       'Self-Designed Major: Mental Health and Substance Related Disorders', 'BA', NULL, NULL, NULL,
                       'Helena, Montana'),
                      ('William', NULL, 'Dominguez', 'William Dominguez', 'SDMJ.BA',
                       'Self-Designed Major: Strategic Behavioral Health', 'BA', NULL, NULL, NULL,
                       'Mattawa, Washington'),
                      ('Annemarie', 'Abigail', 'Johnson', 'AnneMarie Abigail Johnson', 'SDMJ.BA',
                       'Self-Designed Major: Mental and Physical Well-Being', 'BA', NULL, NULL, NULL,
                       'Sheridan, Oregon, USA'),
                      ('Audrey', 'Marie', 'Benge', 'Audrey Marie Benge', 'PSYC.BA', 'Psychology', 'BA', NULL, NULL,
                       NULL, 'Wenatchee, Washington'),
                      ('Emma', 'Catherine', 'Chaffin', 'Emma Catherine Chaffin', 'PSYC.BA', 'Psychology', 'BA', NULL,
                       NULL, NULL, 'Duvall, Washington'),
                      ('Isabella', 'Merittia', 'Chalmers', 'Isabella Merittia Chalmers', 'PSYC.BA', 'Psychology', 'BA',
                       NULL, NULL, NULL, 'Happy Valley, Oregon'),
                      ('Brittney', 'Lynn', 'Chapman', 'Brittney Lynn Chapman', 'PSYC.BA', 'Psychology', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Tumwater, Washington'),
                      ('Samuel', 'Christopher', 'Conner', 'Samuel Christopher Conner', 'PSYC.BA', 'Psychology', 'BA',
                       'Cum Laude', NULL, NULL, 'Salt Lake City, Utah'),
                      ('Alexa', 'Marie', 'Hanser', 'Alexa Marie Hanser', 'PSYC.BA', 'Psychology', 'BA', NULL, NULL,
                       NULL, 'Billings, Montana'),
                      ('Patrick', 'Harrison', 'Keeley', 'Patrick Keeley', 'PSYC.BA', 'Psychology', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Littleton, Colorado'),
                      ('Tucker', 'William', 'Monaco', 'Tucker William Monaco', 'PSYC.BA', 'Psychology', 'BA', NULL,
                       NULL, NULL, 'Bakersfield, California'),
                      ('Jared', 'James Henry', 'Nelson', 'Jared James Henry Nelson', 'PSYC.BA', 'Psychology', 'BA',
                       'Summa Cum Laude', NULL, NULL, 'Helena, Montana'),
                      ('Brodie', 'D', 'Sayre', 'Brodie D Sayre', 'PSYC.BA', 'Psychology', 'BA', 'Cum Laude', NULL, NULL,
                       'Battle Mountain, Nevada'),
                      ('Morgan', NULL, 'Sunchild', 'Morgan Sunchild', 'PSYC.BA', 'Psychology', 'BA', NULL, NULL, NULL,
                       'Great Falls, Montana'),
                      ('Ann', 'Marie', 'Mirkin', 'Annie Marie Mirkin', 'PUBH.BA', 'Public Health', 'BA', NULL, NULL,
                       NULL, 'Seattle, Washington'),
                      ('Lily', 'Marie', 'Oats', 'Lily Marie Oats', 'PUBH.BA', 'Public Health', 'BA', NULL, NULL, NULL,
                       'Helena, Montana'),
                      ('Abigail', 'Frances', 'Robo', 'Abigail Frances Robo', 'SDMJ.BA',
                       'Self-Designed Major: Gender Studies', 'BA', NULL, NULL, NULL, 'Helena, Montana'),
                      ('Grace', 'M', 'Arend', 'Grace Madison Arend', 'SOCI.BA', 'Sociology: Criminology', 'BA',
                       'Summa Cum Laude', NULL, NULL, 'Flagstaff, Arizona'),
                      ('Veronika', NULL, 'Fomishyna', 'Veronika Potts', 'SOCI.BA', 'Sociology: Criminology', 'BA',
                       'Magna Cum Laude', NULL, NULL, 'Ukraine'),
                      ('Isaac', 'C', 'Goudy', 'Isaac C Goudy', 'SOCI.BA', 'Sociology: Criminology', 'BA', 'Cum Laude',
                       NULL, NULL, 'Billings, Montana'),
                      ('Anna', 'R', 'Russell', 'Anna Rose Russell', 'SOCI.BA', 'Sociology: Criminology', 'BA', NULL,
                       NULL, NULL, 'Anaconda, Montana'),
                      ('Brooke', 'Ellen', 'McClenning', 'Brooke McClenning', 'PATH.BA', 'Theatre: Performance', 'BA',
                       NULL, NULL, NULL, 'Huntley, Montana'),
                      ('Abigail', 'G', 'Merz', 'Abigail G Merz', 'PATH.BA', 'Theatre: Performance', 'BA', NULL, NULL,
                       NULL, 'Richland, Washington'),
                      ('Christopher', 'Ross', 'Akulschin', 'Christopher Ross Akulschin', 'CEGR.BS', 'Civil Engineering',
                       'BS', NULL, NULL, NULL, 'Gig Harbor, Washington'),
                      ('Jared', 'C', 'Ball', 'Jared Ball', 'CEGR.BS', 'Civil Engineering', 'BS', 'Cum Laude', NULL,
                       NULL, 'Yakima, Washington'),
                      ('Tristan', 'Reid', 'Gallagher', 'Tristan Reid Gallagher', 'CEGR.BS', 'Civil Engineering', 'BS',
                       'Cum Laude', NULL, 'Y', 'Austin, Texas'),
                      ('Bryan', 'P', 'Holland', 'Bryan Patrick Holland', 'CEGR.BS', 'Civil Engineering', 'BS',
                       'Magna Cum Laude', NULL, NULL, 'Butte, Montana'),
                      ('Thomas', 'Jay', 'Klepps', 'Thomas Jay Klepps', 'CEGR.BS', 'Civil Engineering', 'BS',
                       'Magna Cum Laude', NULL, NULL, 'Billings, Montana'),
                      ('Daniel', NULL, 'Koralewski', 'Daniel Koralewski', 'CEGR.BS', 'Civil Engineering', 'BS', NULL,
                       NULL, NULL, 'Murfreesboro, Tennessee'),
                      ('Benjamin', 'Alexander', 'Mehlhaff', 'Benjamin Alexander Mehlhaff', 'CEGR.BS',
                       'Civil Engineering', 'BS', NULL, NULL, NULL, 'Eugene, Oregon'),
                      ('Cameron', 'Scott', 'Pruitt', 'Cameron Scott Pruitt', 'CEGR.BS', 'Civil Engineering', 'BS', NULL,
                       NULL, NULL, 'Boise, Idaho'),
                      ('Tatem', 'Hannah', 'Schweikert', 'Tatem Hannah Hurricane Schweikert', 'CEGR.BS',
                       'Civil Engineering', 'BS', 'Summa Cum Laude', NULL, NULL, 'Columbia Falls, Montana'),
                      ('Joshua', NULL, 'Smalley', 'Joshua Smalley', 'CEGR.BS', 'Civil Engineering', 'BS',
                       'Summa Cum Laude', NULL, NULL, 'Missoula, Montana'),
                      ('Jamie', 'N', 'Pickens', 'Jamie N Pickens', 'NURS.BS', 'Nursing | Health Sciences', 'BS',
                       'Cum Laude', NULL, NULL, 'Helena, Montana'),
                      ('Aura', 'Fernanda', 'Arroyo', 'Aura Fernanda Arroyo', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL,
                       NULL, 'Porterville, California'),
                      ('Aubrey', 'L', 'Baker', 'Aubrey L Baker', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Mission Viejo, California'),
                      ('Julian', 'M', 'Betz', 'Julian M Betz', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Fall City, Washington'),
                      ('Hailey', NULL, 'Blatchford', 'Hailey Blatchford', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Tacoma, Washington'),
                      ('Miranda', 'Roi', 'Bruhn', 'Miranda Roi Bruhn', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Santa Ynez, California'),
                      ('Eva', 'N', 'Bunger', 'Eva Noel Bunger', 'ANUR.BS', 'Nursing', 'BS', 'Magna Cum Laude', NULL,
                       NULL, 'Portland, Oregon'),
                      ('Addie', 'G', 'Butler', 'Addie  Butler', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude', NULL, NULL,
                       'Freedom, Wyoming'),
                      ('Kyla', 'M', 'Dane', 'Kyla M Dane', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Great Falls, Montana'),
                      ('Julia', 'C', 'Devine', 'Julia Caroline Devine', 'ANUR.BS', 'Nursing', 'BS', 'Summa Cum Laude',
                       NULL, NULL, 'Seattle, Washington'),
                      ('Laura', 'M', 'Dias', 'Laura Michelle Dias', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Clovis, California'),
                      ('Alexa', 'Rose', 'Dreyer', 'Alexa Rose Dreyer', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Bozeman, Montana'),
                      ('Courtney', 'G', 'Gragg', 'Courtney Geraldine Gragg', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL,
                       NULL, 'Lincoln, California'),
                      ('Delaney', 'Derzay', 'Hasquet', 'Delaney Derzay Hasquet', 'NURS.BS', 'Nursing', 'BS',
                       'Magna Cum Laude', NULL, NULL, 'Butte, Montana'),
                      ('Elizabeth', 'Ramey', 'Heuiser', 'Elizabeth Ramey Heuiser', 'NURS.BS', 'Nursing', 'BS',
                       'Cum Laude', NULL, NULL, 'Helena, Montana'),
                      ('Stephanie', 'A', 'Hodges', 'Stephanie A Hodges', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude', NULL,
                       NULL, 'Sammamish, Washington'),
                      ('Tessa', 'A', 'Hoover', 'Tessa A Hoover', 'NURS.BS', 'Nursing', 'BS', 'Magna Cum Laude', NULL,
                       NULL, 'Bothell, Washington'),
                      ('Alexzandria', 'Nicole', 'Hutchison', 'Alexzandria Nicole Hutchison', 'NURS.BS', 'Nursing', 'BS',
                       'Cum Laude', NULL, NULL, 'Paul, Idaho'),
                      ('Callie', NULL, 'Johnson', 'Callie Johnson', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Puyallup, Washington'),
                      ('Jensen', 'Elise', 'Keller', 'Jensen Elise Keller', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Billings, Montana'),
                      ('Elizabeth', 'G', 'Koerber', 'Elizabeth G Koerber', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude',
                       NULL, NULL, 'Billings, Montana'),
                      ('Abigail', 'M', 'Kolstad', 'Abigail M Kolstad', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Glasgow, Montana'),
                      ('Katarina', 'Rene Gerard', 'Kosiewicz', 'Katarina Rene Gerard Kosiewicz', 'NURS.BS', 'Nursing',
                       'BS', NULL, NULL, NULL, 'Keizer, Oregon'),
                      ('Timothy', 'J', 'Larson', 'Timothy John Larson', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'East Helena, Montana'),
                      ('Laura', 'Grace', 'Ley', 'Laura Grace Ley', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude', NULL, NULL,
                       'Huntley, Montana'),
                      ('Haley', 'G', 'Luchini', 'Haley G Luchini', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Bend, Oregon'),
                      ('Catherine', 'E', 'Mack', 'Catherine Elizabeth Mack', 'NURS.BS', 'Nursing', 'BS', NULL, NULL,
                       NULL, 'Coeur d''Alene, Idaho'),
                      ('Jacquelene', 'Gomes', 'Malheiros', 'Jacquelene Gomes Malheiros', 'NURS.BS', 'Nursing', 'BS',
                       NULL, NULL, NULL, 'Helena, Montana'),
                      ('Mary', 'Marlisa', 'Meijerink', 'Mary Marlisa Meijerink', 'NURS.BS', 'Nursing', 'BS', NULL, NULL,
                       NULL, 'La Habra, California'),
                      ('Payton', 'Jean', 'Mitchum', 'Payton Jean Mitchum', 'NURS.BS', 'Nursing', 'BS',
                       'Magna Cum Laude', NULL, NULL, 'Columbus, Montana'),
                      ('Weston', 'R', 'Mitchum', 'Weston R Mitchum', 'NURS.BS', 'Nursing', 'BS', 'Magna Cum Laude',
                       NULL, NULL, 'Columbus, Montana'),
                      ('Audrey', 'Grace', 'Narum', 'Audrey Grace Narum', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude', NULL,
                       NULL, 'Damascus, Oregon'),
                      ('Brennan', 'Reece', 'Nelson', 'Brennan Reece Nelson', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL,
                       NULL, 'Salem, Oregon'),
                      ('Miya', 'L', 'Nettleton', 'Miya L Nettleton', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Helena, Montana'),
                      ('Elizabeth', 'A', 'Olsen', 'Elizabeth Ann Olsen', 'ANUR.BS', 'Nursing', 'BS', 'Magna Cum Laude',
                       NULL, NULL, 'Helena, Montana'),
                      ('Elaina', 'C', 'Patten', 'Elaina C Patten', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude', NULL, NULL,
                       'Helena, Montana'),
                      ('Jasmine', 'Angelina', 'Pearson', 'Jasmine Angelina Pearson', 'NURS.BS', 'Nursing', 'BS',
                       'Cum Laude', NULL, NULL, 'Thompson Falls, Montana'),
                      ('Daria', 'Lorene', 'Peck', 'Daria Lorene Peck', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Windsor, Colorado'),
                      ('Rebecca', 'Mary', 'Rich', 'Rebecca Mary Rich', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude', NULL,
                       NULL, 'Agoura Hills, California'),
                      ('Emma', 'E', 'Richards', 'Emma Elizabeth Richards', 'ANUR.BS', 'Nursing', 'BS',
                       'Magna Cum Laude', NULL, NULL, 'Portland, Oregon'),
                      ('Andrea', 'Kate', 'Robinson', 'Andrea Kate Robinson', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude',
                       NULL, NULL, 'Yelm, Washington'),
                      ('Keetyn', 'Nicole', 'Sayers', 'Keetyn Nicole Sayers', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude',
                       NULL, NULL, 'Helena, Montana'),
                      ('Jaymee', 'Anne', 'Sheridan', 'Jaymee Anne Sheridan', 'NURS.BS', 'Nursing', 'BS', NULL, NULL,
                       NULL, 'Helena, Montana'),
                      ('Julie', 'D', 'Shriver', 'Julie D Shriver', 'ANUR.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'San Diego, California'),
                      ('Stephanie', 'G', 'Smith', 'Stephanie G Smith', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Oakland, California'),
                      ('Natalie', 'Jo', 'Soll', 'Natalie Jo Soll', 'NURS.BS', 'Nursing', 'BS', 'Magna Cum Laude', NULL,
                       NULL, 'Pendleton, Oregon'),
                      ('Emma', 'G', 'Stachofsky', 'Emma Grace Stachofsky', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude',
                       NULL, NULL, 'Spokane, Washington'),
                      ('Dylan', 'F', 'Stearns', 'Dylan F Stearns', 'NURS.BS', 'Nursing', 'BS', 'Magna Cum Laude', NULL,
                       NULL, 'Spokane, Washington'),
                      ('Noel', 'Kateri', 'Teders', 'Noel Kateri Teders', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'Helena, Montana'),
                      ('Avery', 'Paige', 'Tripp', 'Avery Paige Tripp', 'NURS.BS', 'Nursing', 'BS', 'Magna Cum Laude',
                       NULL, NULL, 'Spokane, Washington'),
                      ('Emilie', 'E', 'Turpen', 'Emilie E Turpen', 'NURS.BS', 'Nursing', 'BS', 'Magna Cum Laude', NULL,
                       NULL, 'Sisters, Oregon'),
                      ('Caitlyn', 'Marie', 'Vermulm', 'Caitlyn Marie Vermulm', 'NURS.BS', 'Nursing', 'BS',
                       'Summa Cum Laude', NULL, NULL, 'Cut Bank, Montana'),
                      ('Jesse', NULL, 'Windle', 'Jesse Windle', 'NURS.BS', 'Nursing', 'BS', 'Cum Laude', NULL, NULL,
                       'Trout Creek, Montana'),
                      ('Hanna', 'W', 'Ziegenhagen', 'Hanna W Ziegenhagen', 'NURS.BS', 'Nursing', 'BS', NULL, NULL, NULL,
                       'The Dalles, Oregon'))
                  AS DF(First_Name, Middle_Name, Last_Name, Grad_Diploma_Name, Grad_Acad_Program, Major1, Degree_Type,
                        Latin_Honors, With_Distinction, Honors_Scholars, Grad_Hometown)
--(End 1)---------------------------------------------------------------------------------------------------------------
     ) AS X
JOIN (VALUES ('Summa Cum Laude', 1), ('Magna Cum Laude', 2), ('Cum Laude', 3))
    AS MY_ORDER(LABEL, N) ON X.HONORS = MY_ORDER.LABEL
GROUP BY HONORS, MY_ORDER.N
--(End 2)---------------------------------------------------------------------------------------------------------------
ORDER BY MY_ORDER.N