    SELECT DISTINCT Major
    FROM (VALUES ('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Anthrozoology'),
('Biology'),
('Biology'),
('Catholic Studies'),
('Civil Engineering'),
('Elementary Education'),
('Elementary Education'),
('English Literature'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Mathematics'),
('Political Science'),
('Political Science'),
('Psychology'),
('Self-Designed Major'),
('Sociology'),
('Anthrozoology'),
('Biochemistry/Molecular Biology'),
('Biology'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Civil Engineering'),
('Civil Engineering'),
('Elementary Education'),
('Elementary Education'),
('English Writing'),
('History'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Philosophy'),
('Public Health'),
('Nursing'),
('Sociology'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Business: Accounting and Strategic Finance'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Anthrozoology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biochemistry/Molecular Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Biology'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Catholic Studies'),
('Catholic Studies'),
('Catholic Studies'),
('Civil Engineering'),
('Civil Engineering'),
('Civil Engineering'),
('Civil Engineering'),
('Civil Engineering'),
('Civil Engineering'),
('Chemistry'),
('Chemistry'),
('Communication Studies'),
('Communication Studies'),
('Communication Studies'),
('Communication Studies'),
('Computer Science'),
('Computer Science'),
('Computer Science'),
('Computer Science'),
('Computer Science'),
('Computer Information Systems'),
('Data Science'),
('Data Science'),
('Data Science'),
('Elementary Education'),
('Elementary Education'),
('Elementary Education'),
('Elementary Education'),
('Elementary Educ & Special Educ'),
('Elementary Education K-8 & Special Education K-12'),
('Elementary Education K-8 & Special Education K-12'),
('English Literature'),
('English Education (5-12)'),
('English Writing'),
('Environmental Science'),
('Environmental Science'),
('Environmental Science'),
('Environmental Science'),
('Environmental Science'),
('Environmental Science'),
('Business: Financial Planning'),
('Business: Financial Planning'),
('History'),
('History'),
('History'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('Health Sciences'),
('International Relations'),
('Mathematics Education (5-12)'),
('Mathematics Education (5-12)'),
('Mathematics Education (5-12)'),
('Mathematics'),
('Mathematics'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Nursing'),
('Theatre'),
('Philosophy'),
('Philosophy'),
('Political Science'),
('Political Science'),
('Political Science'),
('Political Science'),
('Political Science'),
('Psychology'),
('Psychology'),
('Psychology'),
('Psychology'),
('Psychology'),
('Psychology'),
('Psychology'),
('Psychology'),
('Psychology'),
('Psychology'),
('Self-Designed Major'),
('Self-Designed Major'),
('Sociology'),
('Sociology'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Master of Social Work'),
('Business: Accounting and Strategic Finance'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Accelerated Nursing'),
('Biology'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Business: Management and Marketing'),
('Civil Engineering'),
('Communication Studies'),
('History'),
('Theatre'),
('Public Health'),
('Health Sciences'),
('Communication Studies'),
('English Writing'),
('Public Health'),
('Philosophy'),
('Business: Acctng & Stratg Finc'),
('Public Health'),
('Data Science'),
('Business: Financial Planning'),
('Biochemistry/Molecular Biology'),
('Catholic Studies'),
('Hispanic Studies and Languages'),
('Hispanic Studies and Languages'),
('Communication Studies'),
('Theology'),
('Philosophy'),
('Physics'),
('Hispanic Studies and Languages'),
('Catholic Studies'),
('Data Science'),
('Data Science'),
('Business: Financial Planning'),
('Political Science'),
('Political Science'),
('English Literature'),
('Biology'),
('Public Health'),
('Public Health'),
('Political Science'),
('Data Science'))
    AS DF(Major)