
--~~~~~~KALINA WELCH~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--She withdrew.----------------------
SELECT STUDENT_ID,
       STP_PROGRAM_TITLE,
       PROGRAM_STATUSES.VAL_EXTERNAL_REPRESENTATION

FROM STUDENT_ACAD_PROGRAMS_VIEW AS SAPV
JOIN STUDENT_ACAD_PROG_STATUS_VIEW AS STATUS ON STATUS.STUDENT_PROGRAMS_ID = SAPV.STUDENT_ID + '*' + SAPV.STP_ACADEMIC_PROGRAM
JOIN VALS AS PROGRAM_STATUSES ON VALCODE_ID = 'STUDENT.PROGRAM.STATUSES' AND VAL_MINIMUM_INPUT_STRING = STATUS.PROG_STATUS
WHERE STUDENT_ID = '5069269'


SELECT *
FROM STUDENT_ACAD_PROGRAMS_STATUS_VIEW
WHERE STUDENT_PROGRAMS_ID LIKE '%5069269%'


--~~~~~~JACOB SCHROEDER~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--Jacob is active, but he has not been enrolled in anything yet. ---

SELECT *
FROM STUDENT_ACAD_PROGRAMS_VIEW AS SAPV
WHERE STUDENT_ID = '5681424'

SELECT *
FROM STUDENT_ENROLLMENT_VIEW
WHERE STUDENT_ID = '5681424'

SELECT *
FROM STUDENT_ACAD_PROGRAMS_STATUS_VIEW
WHERE STUDENT_PROGRAMS_ID LIKE '%5681424%'


--~~~~~~KAYLA GIESEKE~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--She withdrew.----------------------

SELECT *
FROM STUDENT_ACAD_PROGRAMS_VIEW AS SAPV
WHERE STUDENT_ID = '6178378'


SELECT *
FROM STUDENT_ACAD_PROG_STATUS_VIEW


SELECT *
FROM STUDENT_ACAD_PROGRAMS_STATUS_VIEW
WHERE STUDENT_PROGRAMS_ID LIKE '%6178378%'

SELECT *
FROM VALS
WHERE VALCODE_ID = 'STUDENT.PROGRAM.STATUSES'


--~~~~~~ALL~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SELECT *
FROM STUDENT_ACAD_PROGRAMS_VIEW
WHERE STP_PROGRAM_TITLE = 'Master of Social Work'
AND STUDENT_ID IN ('5069269', '5681424', '6178378')


