SELECT CREDIT_STATUS,
       [T] AS TENURED,
       [O] AS ON_TENURE_TRACK,
       [N] AS ANNUAL_CONTRACT
FROM (
SELECT PERSTAT_HRP_ID,
       PERSTAT_TENURE_TYPE,
       CASE
           WHEN 1 = 1 THEN 'Exclusively Credit' END AS CREDIT_STATUS
FROM (SELECT PERSTAT_HRP_ID,
             PERSTAT_TENURE_TYPE

            FROM PERSTAT
             JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
             JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
            WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= (
              SELECT TOP 1 TERM_START_DATE
              FROM TERMS
              WHERE TERMS_ID = '2024FA'
              ))
              AND PERSTAT_START_DATE <= '2024-11-01'
              AND PERSTAT_STATUS = 'FT'
              AND POS_CLASS = 'FAC') AS X) AS X
PIVOT (
    COUNT(PERSTAT_HRP_ID) FOR PERSTAT_TENURE_TYPE IN ([T], [O], [N])
    ) AS X