SELECT DISTINCT STUDENT_ID,
                STUDENT_FIRST_NAME
FROM STUDENT_ENROLLMENT_VIEW AS SEV
JOIN Z01_ALL_RACE_ETHNIC_W_FLAGS AS RACE ON SEV.STUDENT_ID = RACE.ID
WHERE ENROLL_TERM = '2024FA'
AND ENROLL_CURRENT_STATUS IN ('New', 'Add')
AND (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
AND STUDENT_GENDER IS NULL