SELECT *
FROM PERSTAT


SELECT PERSTAT_HRP_ID,
       GENDER,
       IPEDS_RACE_ETHNIC_DESC,
       ISNULL(POS_EEO_RANK, 'Unknown') as POS_EEO_RANK,
       PERSTAT_STATUS,
       POS_CLASS,
       PERSTAT_TENURE_TYPE

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN Z01_ALL_RACE_ETHNIC_W_FLAGS AS RACE ON PERSTAT_HRP_ID = RACE.ID
WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= GETDATE())
