SELECT STTR_TERM,
        COUNT(STTR_STUDENT) AS STUDENT_COUNT
FROM (SELECT DISTINCT STTR_STUDENT,
             STTR_TERM,
             TERM_START_DATE
      FROM STUDENT_TERMS_VIEW AS STV
               JOIN TERMS ON STV.STTR_TERM = TERMS.TERMS_ID
      WHERE TERM_START_DATE > '2014-08-01'
        AND TERM_END_DATE < GETDATE()
      AND STTR_TERM LIKE '%FA') AS X
GROUP BY STTR_TERM, TERM_START_DATE
ORDER BY TERM_START_DATE