----------------------------------------------------------------------------------------------------------------------
SELECT ENROLL_TERM,
       COUNT(STUDENT_ID) AS STUDENT_COUNT
FROM (
SELECT DISTINCT STUDENT_ID, ENROLL_TERM
FROM STUDENT_ENROLLMENT_VIEW AS SEV
JOIN TERMS ON SEV.ENROLL_TERM = TERMS.TERMS_ID
WHERE ENROLL_CURRENT_STATUS IN ('New', 'Add')
AND  (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
AND TERM_START_DATE >= '2014-08-01'
AND ENROLL_TERM LIKE '%FA'
) AS X
GROUP BY ENROLL_TERM


SELECT *
FROM STUDENT_ENROLLMENT_VIEW AS SEV
JOIN TERMS ON SEV.ENROLL_TERM = TERMS.TERMS_ID
WHERE ENROLL_CURRENT_STATUS IN ('New', 'Add')
AND  (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
AND TERM_START_DATE >= '2014-08-01'
AND ENROLL_TERM LIKE '%FA'
