SELECT STTR_TERM,
        COUNT(STTR_STUDENT) AS STUDENT_COUNT
FROM (
        SELECT *
        FROM (
        SELECT STTR_STUDENT,
             STTR_TERM,
             TERM_START_DATE,
             STP_PROGRAM_TITLE,
             STP_CURRENT_STATUS,
             STP_START_DATE,
             STP_END_DATE,
             ROW_NUMBER() OVER (PARTITION BY STTR_STUDENT, STTR_TERM
                            ORDER BY CASE WHEN STP_END_DATE IS NULL THEN 0 ELSE 1 END, STP_END_DATE DESC) AS rn
      FROM STUDENT_TERMS_VIEW AS STV
      JOIN TERMS ON STV.STTR_TERM = TERMS.TERMS_ID
      JOIN (SELECT *
            FROM STUDENT_ACAD_PROGRAMS_VIEW
            )
          AS SAPV ON STV.STTR_STUDENT = SAPV.STUDENT_ID
      WHERE TERM_START_DATE > '2014-08-01'
      AND TERM_END_DATE < GETDATE()
      AND STTR_TERM LIKE '%FA'
      AND SAPV.STP_START_DATE <= TERMS.TERM_END_DATE
      ) AS X
      WHERE rn = 1
      AND STP_CURRENT_STATUS != 'Did Not Enroll'
      AND EXISTS (
      SELECT 1
      FROM STUDENT_ENROLLMENT_VIEW
      WHERE (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
      AND ENROLL_TERM = STTR_TERM
      AND STUDENT_ID = STTR_STUDENT
      AND ENROLL_CURRENT_STATUS IN ('Add', 'New'))
          ) AS X
GROUP BY STTR_TERM, TERM_START_DATE
ORDER BY TERM_START_DATE
----------------------------------------------------------------------------------------------------------------------



SELECT * FROM STUDENT_ENROLLMENT_VIEW

SELECT ENROLL_TERM,
       COUNT(STUDENT_ID) AS STUDENT_COUNT
FROM (
SELECT DISTINCT STUDENT_ID, ENROLL_TERM
FROM STUDENT_ENROLLMENT_VIEW AS SEV
JOIN TERMS ON SEV.ENROLL_TERM = TERMS.TERMS_ID
WHERE ENROLL_CURRENT_STATUS IN ('New', 'Add')
AND  (ENROLL_SCS_PASS_AUDIT != 'A' OR ENROLL_SCS_PASS_AUDIT IS NULL)
AND TERM_START_DATE >= '2014-08-01'
AND ENROLL_TERM LIKE '%FA') AS X
GROUP BY ENROLL_TERM
