SELECT STTR_STUDENT,
       LAST_NAME,
       FIRST_NAME,
       ADDRESS.ADDRESS_ID,
       CITY,
       STATE,
       ZIP,
       ADDRESS_LINES
FROM (
SELECT STTR_STUDENT,
       LAST_NAME,
       FIRST_NAME,
       ADDRESS_ID
FROM (
SELECT STTR_STUDENT,
       P.LAST_NAME,
       P.FIRST_NAME,
       ADDRESS.ADDRESS_ID,
       ROW_NUMBER() OVER (PARTITION BY STTR_STUDENT ORDER BY ADDRESS_ADD_DATE DESC) AS rn

FROM STUDENT_TERMS_VIEW AS STV
JOIN PERSON AS P ON STV.STTR_STUDENT = P.ID
JOIN Z01_AAV_STUDENT_FIRST_MATRIC AS FM ON STV.STTR_STUDENT = FM.ID
JOIN TERMS AS STARTING_TERM ON FM.TERM = STARTING_TERM.TERMS_ID
JOIN PERSON_ADDRESSES_VIEW AS PAV  ON STV.STTR_STUDENT = PAV.ID
JOIN ADDRESS ON PAV.ADDRESS_ID = ADDRESS.ADDRESS_ID
WHERE STTR_TERM = '2024FA'
AND ADDRESS_TYPE = 'H'
AND ADDRESS_ADD_DATE < STARTING_TERM.TERM_START_DATE) AS X WHERE rn = 1) AS X
JOIN ADDRESS ON X.ADDRESS_ID = ADDRESS.ADDRESS_ID
JOIN ADDRESS_LS ON X.ADDRESS_ID = ADDRESS_LS.ADDRESS_ID
WHERE POS = 1