
SELECT TERM,
       COUNT(*) AS FIRST_TIME_UG_COUNT,
       SUM(GRADUATED_IN_4_YEARS) AS FOUR_YEAR_GRADUATION_COUNT,
       SUM(GRADUATED_IN_6_YEARS) AS SIX_YEAR_GRADUATION_COUNT
FROM (
SELECT TERM,
       TERM_START_DATE,
       ID,
       CASE
           WHEN EXISTS (
               SELECT 1
               FROM STUDENT_ACAD_PROGRAMS_VIEW
               WHERE STUDENT_ID = ID
               AND STP_CURRENT_STATUS = 'Graduated'
               AND STP_END_DATE BETWEEN TERM_START_DATE AND DATEADD(year, 4, TERM_START_DATE)
           ) THEN 1 ELSE 0 END AS GRADUATED_IN_4_YEARS,
        CASE
           WHEN EXISTS (
               SELECT 1
               FROM STUDENT_ACAD_PROGRAMS_VIEW
               WHERE STUDENT_ID = ID
               AND STP_CURRENT_STATUS = 'Graduated'
               AND STP_END_DATE BETWEEN TERM_START_DATE AND DATEADD(year, 6, TERM_START_DATE)
           ) THEN 1 ELSE 0 END AS GRADUATED_IN_6_YEARS
FROM (
SELECT TERM,
       COHORT.TERM_START_DATE,
       ID,
       SAPV.STP_PROGRAM_TITLE,
       SAPV.STP_ACAD_LEVEL,
       FIRST_ADMIT.STPR_ADMIT_STATUS,
       ROW_NUMBER() OVER (PARTITION BY ID
        ORDER BY CASE WHEN STP_END_DATE IS NULL THEN 0 ELSE 1 END, STP_END_DATE DESC) AS PROGRAM_RANK
FROM Z01_AAV_STUDENT_FIRST_MATRIC AS FM
JOIN TERMS AS COHORT ON FM.TERM = COHORT.TERMS_ID
JOIN (SELECT STUDENT_ID,
        STP_PROGRAM_TITLE,
        STP_ACAD_LEVEL,
        STP_CURRENT_STATUS,
        STP_START_DATE,
        STP_END_DATE
        FROM STUDENT_ACAD_PROGRAMS_VIEW
        WHERE STP_CURRENT_STATUS != 'Changed Program'
        ) AS SAPV ON FM.ID = SAPV.STUDENT_ID
LEFT JOIN (SELECT DISTINCT STPR_STUDENT, STPR_ADMIT_STATUS, STUDENT_PROGRAMS_ADDDATE
           FROM (
               SELECT   STPR_STUDENT,
                        STPR_ADMIT_STATUS,
                        STUDENT_PROGRAMS_ADDDATE,
                        ROW_NUMBER() OVER (PARTITION BY STPR_STUDENT
                        ORDER BY STUDENT_PROGRAMS_ADDDATE) AS rn
               FROM STUDENT_PROGRAMS_VIEW
               ) ranked
               WHERE rn = 1)
    AS FIRST_ADMIT ON FM.ID = FIRST_ADMIT.STPR_STUDENT
WHERE STP_START_DATE < COHORT.TERM_END_DATE
AND COHORT.TERM_START_DATE >= DATEADD(year, -10, '2024-08-01')
AND COHORT.TERM_START_DATE <= DATEADD(year, -4, '2024-09-01')
) AS X
WHERE PROGRAM_RANK = 1
AND STP_PROGRAM_TITLE != 'Non-Degree Seeking Students'
AND STP_ACAD_LEVEL = 'UG'
AND STPR_ADMIT_STATUS = 'FY') AS X
GROUP BY TERM, TERM_START_DATE
ORDER BY TERM_START_DATE




SELECT *
FROM TERMS