SELECT TERM,
       ID
FROM Z01_AAV_STUDENT_FIRST_MATRIC AS FM
JOIN TERMS ON FM.TERM = TERMS.TERMS_ID
JOIN (SELECT STUDENT_ID,
            STP_ACADEMIC_PROGRAM,
            STP_PROGRAM_TITLE,
            STP_CURRENT_STATUS
                 FROM STUDENT_ACAD_PROGRAMS_VIEW
                 WHERE STP_CURRENT_STATUS != 'Changed Program'
                 ) AS X)
            AS SAPV ON STUDENT_TERMS_VIEW.STTR_STUDENT = SAPV.STUDENT_ID


                        ROW_NUMBER() OVER (PARTITION BY STUDENT_ID
                            ORDER BY CASE WHEN STP_END_DATE IS NULL THEN 0 ELSE 1 END, STP_END_DATE DESC) AS rn