SELECT RACE_ETHNICITY,
       [T] AS TENURED,
       [O] AS ON_TENURE_TRACK,
       [N] AS ANNUAL_CONTRACT
FROM
(SELECT
        PERSTAT_HRP_ID,
        PERSTAT_TENURE_TYPE,
        IPEDS_RACE_ETHNIC_DESC AS RACE_ETHNICITY

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN Z01_ALL_RACE_ETHNIC_W_FLAGS AS RACE ON PERSTAT_HRP_ID = RACE.ID
WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= (
          SELECT TOP 1 TERM_START_DATE
          FROM TERMS
          WHERE TERMS_ID = '2024FA'
          ))
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND PERSTAT_START_DATE BETWEEN '2023-11-02' AND '2024-11-01'
AND GENDER = 'M'
) AS X
PIVOT (COUNT(PERSTAT_HRP_ID) FOR PERSTAT_TENURE_TYPE IN ([T], [O], [N])) AS X --Men
-----------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
SELECT RACE_ETHNICITY,
       [T] AS TENURED,
       [O] AS ON_TENURE_TRACK,
       [N] AS ANNUAL_CONTRACT
FROM
(SELECT
        PERSTAT_HRP_ID,
        PERSTAT_TENURE_TYPE,
        IPEDS_RACE_ETHNIC_DESC AS RACE_ETHNICITY

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN Z01_ALL_RACE_ETHNIC_W_FLAGS AS RACE ON PERSTAT_HRP_ID = RACE.ID
WHERE (PERSTAT_END_DATE IS NULL OR PERSTAT_END_DATE >= (
          SELECT TOP 1 TERM_START_DATE
          FROM TERMS
          WHERE TERMS_ID = '2024FA'
          ))
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND PERSTAT_START_DATE BETWEEN '2023-11-02' AND '2024-11-01'
AND GENDER = 'F'
) AS X
PIVOT (COUNT(PERSTAT_HRP_ID) FOR PERSTAT_TENURE_TYPE IN ([T], [O], [N])) AS X --Women

