
SELECT IPEDS_RACE_ETHNIC_DESC,
       [T] AS TENURED,
       [O] AS ON_TENURE_TRACK,
       [N] AS ANNUAL_CONTRACT
FROM
(SELECT PERSTAT_TENURE_TYPE,
       IPEDS_RACE_ETHNIC_DESC,
       COUNT(*) AS COUNT
FROM
(SELECT
        PERSTAT_HRP_ID,
        PERSON.LAST_NAME,
        PERSON.FIRST_NAME,
        PERSTAT_TENURE_TYPE,
        IPEDS_RACE_ETHNIC_DESC

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN Z01_ALL_RACE_ETHNIC_W_FLAGS AS RACE ON PERSTAT_HRP_ID = RACE.ID
WHERE PERSTAT_END_DATE IS NULL
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND PERSTAT_START_DATE BETWEEN '2023-11-02' AND '2024-11-01'
AND GENDER = 'M'
) AS Q1
GROUP BY PERSTAT_TENURE_TYPE, IPEDS_RACE_ETHNIC_DESC) AS Q2
PIVOT (SUM(COUNT) FOR PERSTAT_TENURE_TYPE IN ([T], [O], [N])) AS Q3 --Men


SELECT IPEDS_RACE_ETHNIC_DESC,
       [T] AS TENURED,
       [O] AS ON_TENURE_TRACK,
       [N] AS ANNUAL_CONTRACT
FROM
(SELECT PERSTAT_TENURE_TYPE,
       IPEDS_RACE_ETHNIC_DESC,
       COUNT(*) AS COUNT
FROM
(SELECT
        PERSTAT_HRP_ID,
        PERSON.LAST_NAME,
        PERSON.FIRST_NAME,
        PERSTAT_TENURE_TYPE,
        IPEDS_RACE_ETHNIC_DESC

FROM PERSTAT
JOIN PERSON ON PERSTAT.PERSTAT_HRP_ID = PERSON.ID
JOIN POSITION ON PERSTAT.PERSTAT_PRIMARY_POS_ID = POSITION.POSITION_ID
JOIN Z01_ALL_RACE_ETHNIC_W_FLAGS AS RACE ON PERSTAT_HRP_ID = RACE.ID
WHERE PERSTAT_END_DATE IS NULL
AND PERSTAT_STATUS = 'FT'
AND POS_CLASS = 'FAC'
AND PERSTAT_START_DATE BETWEEN '2023-11-02' AND '2024-11-01'
AND GENDER = 'F'
) AS Q1
GROUP BY PERSTAT_TENURE_TYPE, IPEDS_RACE_ETHNIC_DESC) AS Q2
PIVOT (SUM(COUNT) FOR PERSTAT_TENURE_TYPE IN ([T], [O], [N])) AS Q3 --Women

