SELECT * FROM (
SELECT STUDENT_ID
FROM PERSON
	JOIN (
			SELECT STUDENT_ID, STP_PROGRAM_TITLE, STP_CURRENT_STATUS, STP_END_DATE
			FROM (
				SELECT STUDENT_ID
				,STP_CURRENT_STATUS
				,STP_END_DATE
				,STP_PROGRAM_TITLE
				,ROW_NUMBER() OVER (PARTITION BY STUDENT_ID ORDER BY CASE WHEN STP_END_DATE IS NULL THEN 0 ELSE 1 END, STP_END_DATE DESC) AS rn
				FROM STUDENT_ACAD_PROGRAMS_VIEW
				WHERE STP_CURRENT_STATUS != 'Changed Program'
				AND STP_START_DATE IS NOT NULL
			) ranked
			WHERE rn = 1
			) AS LATEST_STATUS ON LATEST_STATUS.STUDENT_ID = PERSON.ID
WHERE STP_PROGRAM_TITLE = 'Master of Social Work'
AND STP_END_DATE IS NULL) AS X
JOIN PERSON ON X.STUDENT_ID = PERSON.ID