SELECT DISTINCT SAPV.STUDENT_ID AS ID,
                SAPV.STUDENT_LAST_NAME AS LAST_NAME,
                SAPV.STUDENT_FIRST_NAME AS FIRST_NAME,
                COALESCE(
                        (SELECT TOP 1 PERSON_EMAIL_ADDRESSES
                        FROM PEOPLE_EMAIL
                        WHERE ID = SAPV.STUDENT_ID
                        AND PERSON_EMAIL_TYPES = 'COL'), 'Unknown') AS SCHOOL_EMAIL
FROM STUDENT_ACAD_PROGRAMS_VIEW AS SAPV
WHERE STP_CURRENT_STATUS = 'Active'
AND STP_ACAD_LEVEL = 'UG'
AND STP_PROGRAM_TITLE NOT IN ('Accelerated Nursing', 'Non-Degree Seeking Students')
AND STP_START_DATE IS NOT NULL
AND STP_START_DATE <= GETDATE()
AND (STP_END_DATE IS NULL OR STP_END_DATE > GETDATE())
AND EXISTS (
            SELECT 1 FROM STUDENT_ENROLLMENT_VIEW AS SEV
                     WHERE SEV.STUDENT_ID = SAPV.STUDENT_ID
                     AND ENROLL_TERM = '2025SP'
            )
ORDER BY LAST_NAME, FIRST_NAME