SELECT STTR_STUDENT,
       PERSON.LAST_NAME,
       PERSON.FIRST_NAME,
       GENDER,
       STTR_ACAD_LEVEL
FROM STUDENT_TERMS_VIEW
JOIN PERSON ON STTR_STUDENT = PERSON.ID
WHERE STUDENT_TERMS_VIEW.STTR_TERM = '2024FA'

SELECT DISTINCT STUDENT_ID, LAST_NAME, FIRST_NAME, CSM_INSTR_METHOD, DISTANCE_STATUS
FROM (SELECT STUDENT_ID,
             LAST_NAME,
             FIRST_NAME,
             CSM_INSTR_METHOD,
             CASE
                 WHEN CSM_INSTR_METHOD IN ('REMOT', 'CYBER') THEN 'DISTANCE'
                 ELSE 'NON-DISTANCE'
             END AS DISTANCE_STATUS
      FROM STUDENT_ENROLLMENT_VIEW
               JOIN PERSON ON STUDENT_ENROLLMENT_VIEW.STUDENT_ID = PERSON.ID
               JOIN Z01_RHC_CLASS_SCHEDULE AS CLASSES
                    ON STUDENT_ENROLLMENT_VIEW.SECTION_COURSE_ID = CLASSES.COURSE_SECTIONS_ID
      WHERE ENROLL_TERM = '2024FA'
      ) AS X

SELECT *
FROM COURSE_SECTIONS
WHERE SEC_TERM = '2024FA'


SELECT COURSE_SECTIONS_ID, CSM_INSTR_METHOD
FROM Z01_RHC_CLASS_SCHEDULE
WHERE SEC_TERM = '2024FA'

SELECT INSTR_METHODS_ID, INM_DESC
FROM INSTR_METHODS
