SELECT DISTINCT PERSTAT_HRP_ID AS ID,
                FIRST_NAME,
                LAST_NAME,
                POS_TITLE,
       CASE WHEN PERSTAT_STATUS = 'FT' THEN 'Full-Time' ELSE 'Part-Time' END AS STATUS
FROM PERSTAT
JOIN POSITION ON PERSTAT_PRIMARY_POS_ID = POSITION_ID
JOIN PERSON ON PERSTAT_HRP_ID = PERSON.ID
WHERE POS_CLASS = 'FAC'
AND (COALESCE(POS_RANK, '') != 'A')
AND PERSTAT_START_DATE <= (
    SELECT TOP 1 TERM_END_DATE
    FROM TERMS
    WHERE TERMS_ID = '2025SP'
    )
AND (PERSTAT_END_DATE >= (
    SELECT TOP 1 TERM_START_DATE
    FROM TERMS
    WHERE TERMS_ID = '2025SP'
    ) OR PERSTAT_END_DATE IS NULL)