SELECT ROUND(AVG(CAST(IS_NULL AS FLOAT)), 3) AS NULL_PERCENTAGE
FROM (
    SELECT CASE WHEN ODS_STUDENT_ADVISEMENT.STAD_END_DATE IS NULL THEN 1 ELSE 0 END AS IS_NULL
    FROM ODS_STUDENT_ADVISEMENT
) AS X


SELECT *
FROM ODS_STUDENT_PROGRAMS